Repository MaterializeInc/materialize, pull requests merged in 2020-03, with the labels that each got.

#2161 docs: typos in get-started
  doc/user/get-started.md
Labels: A-docs

#2176 docs: add namespace docs
  doc/user/sql/create-database.md
  doc/user/sql/create-schema.md
  doc/user/sql/drop-database.md
  doc/user/sql/drop-schema.md
  doc/user/sql/namespaces.md
  doc/user/sql/show-databases.md
  doc/user/sql/show-schemas.md
  doc/user/sql/show-sources.md
  doc/user/sql/show-views.md
  www/layouts/partials/sql-grammar/bnf/create-database.bnf
  www/layouts/partials/sql-grammar/bnf/create-schema.bnf
  www/layouts/partials/sql-grammar/bnf/drop-database.bnf
  www/layouts/partials/sql-grammar/bnf/drop-schema.bnf
  www/layouts/partials/sql-grammar/bnf/show-databases.bnf
  www/layouts/partials/sql-grammar/bnf/show-schemas.bnf
  www/layouts/partials/sql-grammar/bnf/show-sources.bnf
  www/layouts/partials/sql-grammar/bnf/show-views.bnf
  www/layouts/partials/sql-grammar/rr-diagrams/create-database.html
  www/layouts/partials/sql-grammar/rr-diagrams/create-schema.html
  www/layouts/partials/sql-grammar/rr-diagrams/drop-database.html
  www/layouts/partials/sql-grammar/rr-diagrams/drop-schema.html
  www/layouts/partials/sql-grammar/rr-diagrams/show-databases.html
  www/layouts/partials/sql-grammar/rr-diagrams/show-schemas.html
  www/layouts/partials/sql-grammar/rr-diagrams/show-sources.html
  www/layouts/partials/sql-grammar/rr-diagrams/show-views.html
Labels: A-docs

#2226 docs: add closed known limitation section
  doc/user/known-limitations.md
  doc/user/release-notes.md
Labels: A-docs

#2252 Print panic stack trace to log file.
  doc/developer/sqllogictest.md
  doc/user/release-notes.md
  src/materialized/bin/materialized.rs
Labels: docs-impact

#2253 docs: consolidate conceptual docs around SQL components
  doc/user/overview/api-components.md
  doc/user/overview/architecture.md
  doc/user/overview/what-is-materialize.md
  doc/user/sql/create-index.md
  doc/user/sql/create-materialized-view.md
  doc/user/sql/create-source.md
  doc/user/sql/create-view.md
Labels: A-docs

#2292 docs: add materialize_logical_timestamp()
  www/data/sql_funcs.json
Labels: A-docs

#2214 Support single-threaded reading of multiple Kafka partitions
  Cargo.lock
  src/catalog/sql.rs
  src/coord/Cargo.toml
  src/coord/coord.rs
  src/coord/timestamp.rs
  src/dataflow/server.rs
  src/dataflow/source/kafka.rs
  src/dataflow/source/kinesis.rs
  src/testdrive/action/kafka.rs
  src/testdrive/action/mod.rs
  test/testdrive/sink.td
  test/testdrive/timestamps.td
  test/testdrive/timestamps_multi.td
Labels: T-UX, T-beta-customer-priority, docs-impact

#2306 sql: add SHOW CREATE SINK
  doc/user/sql/show-create-sink.md
  src/sql-parser/src/ast/mod.rs
  src/sql-parser/src/ast/visit_macro.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/sqlparser_common.rs
  src/sql/statement.rs
  test/testdrive/basic.td
  www/layouts/partials/sql-grammar/bnf/show-create-sink.bnf
  www/layouts/partials/sql-grammar/rr-diagrams/show-create-sink.html
Labels: A-sql, C-feature, docs-impact

#2277 docs: restructure create source, atomizing by data format
  doc/user/demos/log-parsing.md
  doc/user/overview/api-components.md
  doc/user/sql/create-source/_index.md
  doc/user/sql/create-source/avro-source.md
  doc/user/sql/create-source/csv-source.md
  doc/user/sql/create-source/protobuf-source.md
  doc/user/sql/create-source/text-source.md
  www/config.toml
  www/layouts/partials/sql-grammar/bnf/avro-schema-spec.bnf
  www/layouts/partials/sql-grammar/bnf/connector-spec.bnf
  www/layouts/partials/sql-grammar/bnf/create-source-avro.bnf
  www/layouts/partials/sql-grammar/bnf/create-source-csv.bnf
  www/layouts/partials/sql-grammar/bnf/create-source-protobuf.bnf
  www/layouts/partials/sql-grammar/bnf/create-source-text.bnf
  www/layouts/partials/sql-grammar/rr-diagrams/connector-spec.html
  www/layouts/partials/sql-grammar/rr-diagrams/create-source-avro.html
  www/layouts/partials/sql-grammar/rr-diagrams/create-source-csv.html
  www/layouts/partials/sql-grammar/rr-diagrams/create-source-protobuf.html
  www/layouts/partials/sql-grammar/rr-diagrams/create-source-text.html
Labels: A-docs

#2387 Kinesis docs
  doc/user/sql/create-source.md
  doc/user/sql/create-source/_index.md
  doc/user/sql/create-source/kinesis-source.md
  www/layouts/partials/sql-grammar/bnf/create-source-kinesis.bnf
  www/layouts/partials/sql-grammar/rr-diagrams/create-source-kinesis.html
Labels: A-docs

#2366 Refactor DATE, TIME, TIMESTAMP/TZ in strconv
  doc/user/sql/types/date.md
  doc/user/sql/types/timestamp.md
  src/repr/scalar/datetime.rs
  src/repr/scalar/strconv.rs
  test/sqllogictest/dates-times.slt
  test/sqllogictest/interval.slt
  www/layouts/partials/sql-grammar/bnf/type-date.bnf
  www/layouts/partials/sql-grammar/bnf/type-timestamp.bnf
  www/layouts/partials/sql-grammar/bnf/type-timestamptz.bnf
  www/layouts/partials/sql-grammar/rr-diagrams/avro-schema-spec.html
  www/layouts/partials/sql-grammar/rr-diagrams/create-sink.html
  www/layouts/partials/sql-grammar/rr-diagrams/type-date.html
  www/layouts/partials/sql-grammar/rr-diagrams/type-timestamp.html
  www/layouts/partials/sql-grammar/rr-diagrams/type-timestamptz.html
Labels: A-sql

#2430 sql: support CSVs with headers
  doc/user/known-limitations.md
  doc/user/release-notes.md
  src/dataflow-types/types.rs
  src/dataflow/decode/csv.rs
  src/dataflow/decode/mod.rs
  src/materialized/tests/sql.rs
  src/sql-parser/src/ast/mod.rs
  src/sql-parser/src/keywords.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/sqlparser_common.rs
  src/sql/statement.rs
Labels: A-dataflow

#2433 docs: document CSV sources with headers
  doc/user/sql/create-source/csv-source.md
  www/assets/sass/_docs_table.scss
  www/layouts/partials/sql-grammar/bnf/create-source-csv.bnf
  www/layouts/partials/sql-grammar/rr-diagrams/create-source-csv.html
Labels: A-docs
