Repository MaterializeInc/materialize, pull requests merged in 2021-12, with the labels that each got.

#9246 persist: seal errors must not allow the frontier to advance
  src/dataflow/src/render/sources.rs
  src/persist/src/operators/stream.rs
Labels: C-bug, A-persistence

#9229 persist: asynchronously retract in filter_and_retract_future_updates()
  src/persist/src/operators/stream.rs
  src/persist/src/operators/upsert.rs
Labels: C-bug, A-persistence

#9341 Fast follow-ups from #9000
  src/coord/src/coord.rs
  src/coord/src/coord/dataflow_builder.rs
  src/expr/src/linear.rs
  src/expr/src/relation/canonicalize.rs
  src/expr/src/relation/join_input_mapper.rs
  src/expr/src/relation/mod.rs
  src/expr/src/scalar/mod.rs
  src/transform/src/fusion/join.rs
  src/transform/src/fusion/reduce.rs
  src/transform/src/map_lifting.rs
  src/transform/src/nonnullable.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/reduction_pushdown.rs
Labels: A-coordinator, T-memory, A-optimization

#9400 sql: add pg_catalog.pg_tables view
  src/coord/src/catalog/builtin.rs
Labels: A-sql

#9445 mzbench-opt: add a Python package for optimizer benchmarks
  src/transform/benches/.gitignore
  src/transform/benches/README.md
  src/transform/benches/mzbench_opt/__init__.py
  src/transform/benches/mzbench_opt/cli.py
  src/transform/benches/mzbench_opt/schema/tpch.sql
  src/transform/benches/mzbench_opt/sql.py
  src/transform/benches/mzbench_opt/util.py
  src/transform/benches/mzbench_opt/workload/tpch.sql
  src/transform/benches/setup.py
Labels: A-optimization

#9481 optbench: move ` src/transform/benches/mzbench_opt` to `misc/python/materialize/optbench`
  bin/ci-builder
  bin/optbench
  ci/builder/.gitignore
  ci/builder/requirements-dev.txt
  ci/builder/requirements.txt
  misc/python/materialize/cli/optbench.py
  misc/python/materialize/optbench/README.md
  misc/python/materialize/optbench/__init__.py
  misc/python/materialize/optbench/schema/tpch.sql
  misc/python/materialize/optbench/sql.py
  misc/python/materialize/optbench/util.py
  misc/python/materialize/optbench/workload/tpch.sql
  misc/python/requirements-dev.txt
  misc/python/requirements.txt
  misc/python/setup.py
  src/transform/benches/.gitignore
  src/transform/benches/setup.py
Labels: A-infra, C-refactoring, A-optimization

#9444 coord, dataflow: Move TAIL row processing to coord
  src/coord/src/coord.rs
  src/coord/src/lib.rs
  src/coord/src/tail.rs
  src/dataflow-types/src/types.rs
  src/dataflow/src/sink/tail.rs
  src/materialized/tests/sql.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
Labels: A-dataflow, A-coordinator

#9581 doc: Update Redpanda page
  doc/user/content/third-party/redpanda.md
Labels: A-coordinator

#9682 expr,sql: support casts from timestamp/tz to time
  doc/user/content/release-notes.md
  doc/user/content/sql/types/time.md
  doc/user/content/sql/types/timestamp.md
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/timestamp.rs
  src/sql/src/plan/typeconv.rs
  test/sqllogictest/type-promotion.slt
Labels: A-sql

#9698 expr,sql: support casts from integer types to/from oid
  doc/user/content/release-notes.md
  doc/user/content/sql/types/integer.md
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/int16.rs
  src/expr/src/scalar/func/impls/int64.rs
  src/expr/src/scalar/func/impls/oid.rs
  src/expr/src/scalar/mod.rs
  src/sql/src/plan/typeconv.rs
  test/sqllogictest/type-promotion.slt
Labels: A-sql

#9728 coord: add `pronamespace` and `proargdefaults` to `pg_proc`
  doc/user/content/release-notes.md
  src/coord/src/catalog/builtin.rs
  test/sqllogictest/pg_catalog.slt
Labels: A-sql
