Repository MaterializeInc/materialize, pull requests merged in 2021-11, with the labels that each got.

#8801 Skeleton for QGM generation from Hir
  src/expr/src/lib.rs
  src/expr/src/relation/mod.rs
  src/ore/src/id_gen.rs
  src/ore/src/lib.rs
  src/sql/src/lib.rs
  src/sql/src/plan/explain.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/query_model/README.md
  src/sql/src/query_model/dot.rs
  src/sql/src/query_model/hir.rs
  src/sql/src/query_model/mod.rs
  src/sql/src/query_model/scalar_expr.rs
  src/sql/src/query_model/test.rs
  src/sql/tests/querymodel/basic
  src/transform/Cargo.toml
  src/transform/src/dataflow.rs
  src/transform/src/lib.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/update_let.rs
Labels: A-optimization

#8947 Enable dataflowd/coord to work in clustered mode
  ci/test/pipeline.template.yml
  misc/python/materialize/mzcompose.py
  src/coordtest/src/lib.rs
  src/dataflow/src/server.rs
  src/dataflowd/ci/.gitignore
  src/dataflowd/ci/Dockerfile
  src/dataflowd/ci/mzbuild.yml
  src/dataflowd/src/lib.rs
  src/dataflowd/src/main.rs
  src/materialized/ci/coordd/.gitignore
  src/materialized/ci/coordd/Dockerfile
  src/materialized/ci/coordd/mzbuild.yml
  src/materialized/src/bin/coordd.rs
  src/materialized/src/lib.rs
  test/cluster/insert-select.td
  test/cluster/mzcompose
  test/cluster/mzworkflows.py
Labels: C-feature, A-dataflow

#8969 Skeleton for QGM lowering into Mir
  src/sql/src/query_model/dot.rs
  src/sql/src/query_model/hir.rs
  src/sql/src/query_model/lowering.rs
  src/sql/src/query_model/mod.rs
  src/sql/src/query_model/scalar_expr.rs
  src/sql/src/query_model/test.rs
  src/sql/tests/querymodel/basic
  src/sql/tests/querymodel/lowering
Labels: A-optimization

#8990 Introduce a SET option to enable/disable QGM per connection
  src/coord/src/catalog.rs
  src/coord/src/coord.rs
  src/coord/src/session.rs
  src/coord/src/session/vars.rs
  src/sql/src/lib.rs
  src/sql/src/plan.rs
  src/sql/src/plan/optimize.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/query_model/dot.rs
  src/sql/src/query_model/mod.rs
  src/sql/src/query_model/scalar_expr.rs
Labels: C-feature, A-optimization

#9188 Make `MirRelationExpr::*visit*` methods and HIR ⇒ MIR lowering stack safe
  src/coord/src/coord.rs
  src/coord/src/coord/dataflow_builder.rs
  src/coord/src/error.rs
  src/expr/src/lib.rs
  src/expr/src/relation/mod.rs
  src/ore/src/stack.rs
  src/pgwire/src/message.rs
  src/sql/src/plan/lowering.rs
  src/transform/src/canonicalize_mfp.rs
  src/transform/src/cse/relation_cse.rs
  src/transform/src/dataflow.rs
  src/transform/src/fusion/join.rs
  src/transform/src/fusion/union.rs
  src/transform/src/inline_let.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/projection_extraction.rs
  src/transform/src/reduce_elision.rs
  src/transform/src/reduction.rs
  src/transform/src/reduction_pushdown.rs
  src/transform/src/topk_elision.rs
  src/transform/src/union_cancel.rs
  src/transform/src/update_let.rs
Labels: C-refactoring, A-optimization

#9293 Merge pull request #9293 from aalexandrov/stacker_transform
  doc/user/content/release-notes.md
  src/coord/src/coord.rs
  src/expr/src/relation/mod.rs
  src/transform/src/canonicalize_mfp.rs
  src/transform/src/column_knowledge.rs
  src/transform/src/cse/relation_cse.rs
  src/transform/src/dataflow.rs
  src/transform/src/demand.rs
  src/transform/src/fusion/filter.rs
  src/transform/src/fusion/join.rs
  src/transform/src/fusion/map.rs
  src/transform/src/fusion/negate.rs
  src/transform/src/fusion/project.rs
  src/transform/src/fusion/reduce.rs
  src/transform/src/fusion/top_k.rs
  src/transform/src/fusion/union.rs
  src/transform/src/inline_let.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/map_lifting.rs
  src/transform/src/monotonic.rs
  src/transform/src/nonnull_requirements.rs
  src/transform/src/nonnullable.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/projection_extraction.rs
  src/transform/src/projection_lifting.rs
  src/transform/src/reduce_elision.rs
  src/transform/src/reduction_pushdown.rs
  src/transform/src/redundant_join.rs
  src/transform/src/topk_elision.rs
  src/transform/src/update_let.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
Labels: C-refactoring, T-memory, A-optimization
