Repository MaterializeInc/materialize, pull requests merged in 2021-08, with the labels that each got.

#7634 (docs) Correct formatting in CREATE SINK example for EO sinks
  doc/user/content/sql/create-sink.md
Labels: A-docs

#7499 docs: Update Getting Started guide.
  doc/user/assets/sass/_content.scss
  doc/user/content/get-started.md
  doc/user/content/install.md
  doc/user/layouts/shortcodes/tab.html
  doc/user/layouts/shortcodes/tabs.html
Labels: A-docs

#7664 (docs) Add "Sinks" to "Connect" in the sidebar
  doc/user/config.toml
  doc/user/content/connect/materialize-cdc.md
  doc/user/content/sql/create-sink.md
Labels: A-docs

#7332 docs: Update CREATE SOURCE syntax for Protobuf over Kafka/Kinesis + Billing Demo
  doc/user/content/demos/microservice.md
  doc/user/content/sql/create-source/protobuf-kafka.md
  doc/user/content/sql/create-source/protobuf-kinesis.md
Labels: A-docs

#7698 (WIP) coord: refactor catalog content migrations
  src/build-info/src/lib.rs
  src/coord/src/catalog.rs
  src/coord/src/catalog/config.rs
  src/coord/src/catalog/error.rs
  src/coord/src/catalog/migrate.rs
  src/coord/src/catalog/storage.rs
  src/coord/src/coord.rs
  src/sql/src/pure.rs
  test/catalog-compat/catcompatck/Dockerfile
  test/catalog-compat/catcompatck/catcompatck
  test/catalog-compat/mzcompose.yml
  test/testdrive/kafka-avro-sources.td
Labels: A-sql, A-persistence

#7587 (docs) Node.js guide update
  doc/user/content/guides/node-js.md
Labels: A-docs

#6863 coord: err instead of panic when we have a negative multiplicity in constant result
  src/coord/src/coord.rs
  test/sqllogictest/table_func.slt
Labels: bugfix-day

#7998 (docs) Switch Contact link to Slack
  doc/user/content/install.md
Labels: A-docs

#7620 (docs) Update docs style
  doc/user/assets/sass/_content.scss
  doc/user/assets/sass/_fonts.scss
  doc/user/assets/sass/_layout.scss
  doc/user/assets/sass/_mixins.scss
  doc/user/assets/sass/_reset.scss
  doc/user/assets/sass/main.scss
  doc/user/content/_index.md
  doc/user/content/install.md
  doc/user/content/stylesheet.md
  doc/user/layouts/_default/baseof.html
  doc/user/layouts/_default/list.html
  doc/user/layouts/_default/single.html
  doc/user/layouts/partials/header.html
  doc/user/layouts/partials/sidebar.html
  doc/user/layouts/partials/toc.html
  doc/user/layouts/shortcodes/beta.html
  doc/user/layouts/shortcodes/callout.html
  doc/user/layouts/shortcodes/cloud-notice.html
  doc/user/layouts/shortcodes/cta.html
  doc/user/layouts/shortcodes/linkbox.html
  doc/user/layouts/shortcodes/multilinkbox.html
  doc/user/layouts/shortcodes/note.html
  doc/user/layouts/shortcodes/promo.html
  doc/user/layouts/shortcodes/warning.html
  doc/user/static/images/icon_book.png
  doc/user/static/images/icon_bulb.png
  doc/user/static/images/icon_doc.png
  doc/user/static/images/icon_external_link.svg
  doc/user/static/images/icon_sidebar_expanded.svg
  doc/user/static/images/icon_sidebar_minimized.svg
  doc/user/static/images/icon_touch.png
Labels: A-docs
