Repository MaterializeInc/materialize, pull requests merged in 2022-06, with the labels that each got.

#12880 doc/user: revamp `CREATE SOURCE` landing page
  doc/user/README.md
  doc/user/content/overview/_index.md
  doc/user/content/sql/create-source/_index.md
  doc/user/content/sql/create-source/kafka.md
  doc/user/content/sql/create-source/kinesis.md
  doc/user/content/sql/create-source/materialize-cdc.md
  doc/user/content/sql/create-source/postgres.md
  doc/user/content/sql/create-source/pubnub.md
  doc/user/content/sql/create-source/s3.md
  doc/user/content/sql/show-create-index.md
  doc/user/content/sql/show-create-sink.md
  doc/user/content/sql/show-create-source.md
  doc/user/layouts/partials/create-source/envelope/append-only/details.html
  doc/user/layouts/partials/create-source/envelope/debezium/details.html
  doc/user/layouts/partials/create-source/envelope/upsert/details.html
  doc/user/layouts/partials/create-source/format/avro-ccsr/details.html
  doc/user/layouts/partials/create-source/format/avro-ccsr/syntax.html
  doc/user/layouts/partials/create-source/format/bytes/details.html
  doc/user/layouts/partials/create-source/format/bytes/syntax.html
  doc/user/layouts/partials/create-source/format/csv/details.html
  doc/user/layouts/partials/create-source/format/csv/syntax.html
  doc/user/layouts/partials/create-source/format/json-bytes/details.html
  doc/user/layouts/partials/create-source/format/json-bytes/syntax.html
  doc/user/layouts/partials/create-source/format/none/details.html
  doc/user/layouts/partials/create-source/format/none/syntax.html
  doc/user/layouts/partials/create-source/format/protobuf/details.html
  doc/user/layouts/partials/create-source/format/protobuf/syntax.html
  doc/user/layouts/partials/create-source/format/regex/details.html
  doc/user/layouts/partials/create-source/format/regex/syntax.html
  doc/user/layouts/partials/create-source/format/text/details.html
  doc/user/layouts/partials/create-source/format/text/syntax.html
  doc/user/layouts/partials/create-source/intro.html
  doc/user/layouts/shortcodes/create-source/intro.html
  doc/user/layouts/shortcodes/create-source/syntax-details.html
Labels: A-docs

#12991 doc/user: hide s3 and Kinesis source pages + remove mentions
  doc/user/content/_index.md
  doc/user/content/integrations/_index.md
  doc/user/content/integrations/node-js.md
  doc/user/content/overview/_index.md
  doc/user/content/overview/volatility.md
  doc/user/content/sql/create-source/_index.md
  doc/user/content/sql/create-source/kinesis.md
  doc/user/content/sql/create-source/s3.md
  doc/user/content/sql/show-sources.md
  doc/user/content/sql/system-catalog.md
Labels: A-docs

#13016 compute: Ignore invalid protocol prefixes
  src/compute/src/server.rs
Labels: C-bug, A-COMPUTE

#13028 Add `101-query-compilation.md` overview doc
  doc/developer/101-query-compilation.md
  doc/developer/README.md
  doc/developer/command-and-response-binary-encoding.md
Labels: A-docs

#13027 Trace key compile-time stages
  Cargo.lock
  misc/opentelemetry/mzcompose.py
  src/dataflow-types/src/plan/mod.rs
  src/sql-parser/src/parser.rs
  src/sql/src/names.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/query.rs
  src/transform/Cargo.toml
  src/transform/src/dataflow.rs
  src/transform/src/lib.rs
Labels: A-optimization, A-ADAPTER

#13308 sql: Prepare new `EXPLAIN` structures
  src/coord/src/coord.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/explain
  src/sql/src/plan.rs
  src/sql/src/plan/explain.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/statement/dml.rs
Labels: C-refactoring, A-optimization, A-COMPUTE

#13325 doc/user: remove legacy Cloud documentation + make product direction clear
  doc/user/content/_index.md
  doc/user/content/cli.md
  doc/user/content/cloud/_index.md
  doc/user/content/cloud/account-limits.md
  doc/user/content/cloud/change-deployment-details.md
  doc/user/content/cloud/cloud-deployments.md
  doc/user/content/cloud/connect-to-cloud.md
  doc/user/content/cloud/create-deployments.md
  doc/user/content/cloud/destroy-deployments.md
  doc/user/content/cloud/get-started-with-cloud.md
  doc/user/content/cloud/maintenance-windows.md
  doc/user/content/cloud/manage-users.md
  doc/user/content/cloud/manage-workspaces.md
  doc/user/content/cloud/monitor-cloud.md
  doc/user/content/cloud/security.md
  doc/user/content/cloud/settings.md
  doc/user/content/cloud/support.md
  doc/user/content/cloud/troubleshoot-cloud.md
  doc/user/content/install.md
  doc/user/content/integrations/aws-aurora.md
  doc/user/content/integrations/aws-rds.md
  doc/user/content/integrations/azure-postgres.md
  doc/user/content/integrations/dbt.md
  doc/user/content/integrations/digitalocean-postgres.md
  doc/user/content/integrations/gcp-cloud-sql.md
  doc/user/content/integrations/golang.md
  doc/user/content/integrations/java-jdbc.md
  doc/user/content/integrations/node-js.md
  doc/user/content/integrations/php.md
  doc/user/content/integrations/python.md
  doc/user/content/integrations/ruby.md
  doc/user/content/ops/monitoring.md
  doc/user/content/overview/_index.md
  doc/user/content/overview/architecture.md
  doc/user/content/overview/key-concepts.md
  doc/user/content/stylesheet.md
  doc/user/layouts/shortcodes/cloud-connection-details.html
  doc/user/layouts/shortcodes/cloud-notice.html
Labels: A-docs

#13337 doc/user: remove mentions to volatility
  doc/user/content/overview/volatility.md
  doc/user/content/sql/show-sinks.md
  doc/user/content/sql/show-sources.md
  doc/user/content/sql/show-views.md
  doc/user/content/sql/system-catalog.md
  doc/user/layouts/shortcodes/volatility-warning.html
Labels: A-docs

#13323 sql-parser: Add new EXPLAIN code path.
  src/coord/src/coord.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/keywords.txt
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/explain
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
Labels: C-feature, A-optimization, A-COMPUTE

#12224 doc/user: Update MSK Title and Description
  doc/user/content/integrations/aws-msk.md
Labels: A-docs
