Repository MaterializeInc/materialize, pull requests merged in 2022-01, with the labels that each got.

#10201 Docs compaction withclause
  doc/user/content/release-notes.md
  doc/user/content/sql/alter-index.md
  doc/user/content/sql/copy-from.md
  doc/user/content/sql/copy-to.md
  doc/user/content/sql/create-index.md
  doc/user/content/sql/create-type.md
  doc/user/content/sql/fetch.md
  doc/user/content/sql/tail.md
  doc/user/layouts/partials/index-with-options.html
  doc/user/layouts/partials/sql-grammar/copy-from.svg
  doc/user/layouts/partials/sql-grammar/copy-to.svg
  doc/user/layouts/shortcodes/index-with-options.html
  doc/user/sql-grammar/sql-grammar.bnf
Labels: A-docs

#10215 qgm: factor out model-dependent methods
  src/sql/src/query_model/hir.rs
  src/sql/src/query_model/mod.rs
  src/sql/src/query_model/validator/quantifier.rs
Labels: C-refactoring, A-optimization

#10252 qgm: introduce `Rule::Match` and `ApplyRule`
  src/sql/src/query_model/rewrites/mod.rs
Labels: C-refactoring, A-optimization

#9819 expr,sql: add array_cat function + operator
  doc/user/content/release-notes.md
  doc/user/data/sql_funcs.yml
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/mod.rs
  src/sql/src/func.rs
  test/sqllogictest/arrays.slt
Labels: A-sql
