Repository MaterializeInc/materialize, pull requests merged in 2022-10, with the labels that each got.

#15139 `None` the initial `JoinClosure` when its MFP is identity
  src/compute-client/src/plan/join/linear_join.rs
  test/sqllogictest/github-9027.slt
Labels: T-performance, A-COMPUTE

#15119 adapter,repr: finalize `EXPLAIN AS TEXT` rendering (alternative)
  src/adapter/src/explain_new/hir/text.rs
  src/adapter/src/explain_new/lir/text.rs
  src/adapter/src/explain_new/mir/mod.rs
  src/adapter/src/explain_new/mir/text.rs
  src/ore/src/str.rs
  src/repr/src/explain_new/mod.rs
  test/sqllogictest/attributes/mir_arity.slt
  test/sqllogictest/attributes/mir_column_types.slt
  test/sqllogictest/attributes/mir_unique_keys.slt
  test/sqllogictest/explain/decorrelated_plan_as_json.slt
  test/sqllogictest/explain/decorrelated_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
Labels: A-optimization, A-COMPUTE

#15183 `tpch.slt` -- Remove PRIMARY KEY annotations and add explicit `pk_` indexes
  test/sqllogictest/tpch.slt
Labels: T-testing

#15312 sql: require SIZE option for sources and sinks
  doc/user/content/sql/create-sink.md
  doc/user/content/sql/create-source/_index.md
  doc/user/content/sql/create-source/kafka.md
  doc/user/content/sql/create-source/postgres.md
  src/adapter/src/catalog.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/error.rs
  src/environmentd/tests/server.rs
  src/pgwire/src/message.rs
Labels: M-release-blocker

#15316 adapter: Add system compute instances
  doc/developer/platform-checks.md
  doc/user/content/sql/show-cluster-replicas.md
  doc/user/content/sql/show-clusters.md
  doc/user/content/sql/system-catalog/mz_catalog.md
  misc/python/materialize/checks/mzcompose_actions.py
  misc/python/materialize/cloudtest/application.py
  misc/python/materialize/zippy/replica_actions.py
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/builtin.rs
  src/adapter/src/catalog/builtin_table_updates.rs
  src/adapter/src/catalog/error.rs
  src/adapter/src/catalog/storage.rs
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/coord/ddl.rs
  src/adapter/src/coord/sequencer.rs
  src/audit-log/src/lib.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/orchestrator.rs
  src/environmentd/src/bin/environmentd/main.rs
  src/environmentd/src/http/static/js/hierarchical-memory.jsx
  src/environmentd/src/http/static/js/memory.jsx
  src/environmentd/src/lib.rs
  src/environmentd/tests/util.rs
  src/orchestrator-process/src/lib.rs
  src/sql/src/names.rs
  src/sql/src/plan/statement/show.rs
  src/sqllogictest/src/runner.rs
  test/cloudtest/test_smoke.py
  test/cloudtest/test_upgrade.py
  test/feature-benchmark/mzcompose.py
  test/limits/mzcompose.py
  test/sqllogictest/audit_log.slt
  test/sqllogictest/cluster.slt
  test/sqllogictest/cluster_log_compaction.slt
  test/sqllogictest/cluster_log_drop.slt
  test/sqllogictest/cluster_log_sinks.slt
  test/sqllogictest/id_reuse.slt
  test/testdrive/catalog.td
Labels: M-release-blocker

#15325 Make show indexes consistent with other show commands
  doc/user/content/sql/drop-index.md
  doc/user/content/sql/show-indexes.md
  doc/user/layouts/partials/sql-grammar/show-indexes.svg
  doc/user/sql-grammar/sql-grammar.bnf
  misc/python/materialize/checks/rename_index.py
  src/environmentd/tests/server.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/show
  test/sqllogictest/cockroach/alter_table.slt
  test/sqllogictest/cockroach/case_sensitive_names.slt
  test/sqllogictest/cockroach/information_schema.slt
  test/sqllogictest/cockroach/pg_catalog.slt
  test/sqllogictest/cockroach/rename_column.slt
  test/sqllogictest/cockroach/table.slt
  test/testdrive/dependencies.td
  test/testdrive/indexes.td
  test/testdrive/rename.td
  test/testdrive/tables.td
  test/testdrive/temporary.td
Labels: M-release-blocker

#15314 replicated: track frontiers of arranged logs
  src/compute-client/src/controller/replicated.rs
  test/testdrive/introspection-sources.td
Labels: M-release-blocker

#15268 Fix some issues in `ColumnKnowledge`
  src/transform/src/column_knowledge.rs
Labels: C-bug, A-optimization, A-COMPUTE

#15329 sql-parser: parse subsources before WITH block
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
  test/cluster/pg-snapshot-resumption/02-create-sources.td
Labels: M-release-blocker

#15331 Tweaks in literal constraints detection
  src/transform/src/canonicalize_mfp.rs
Labels: A-optimization, A-COMPUTE

#15341 [storage] Heartbeat writer in storage persist sink
  src/storage/src/render/persist_sink.rs
Labels: A-STORAGE

#15418 Fix broken links in 101-query-compilation.md
  doc/developer/101-query-compilation.md
Labels: A-docs

#15338 Document the new `EXPLAIN` syntax
  doc/user/content/sql/explain.md
  doc/user/layouts/partials/sql-grammar/explain.svg
  doc/user/sql-grammar/sql-grammar.bnf
Labels: A-docs, A-COMPUTE

#15482 storage: bandaid over as_of panic
  src/storage/src/source/reclock.rs
  src/storage/src/source/source_reader_pipeline.rs
Labels: M-release-blocker

#15542 doc/user: Consolidate pagerank to 10-90 system
  doc/user/content/overview/key-concepts.md
  doc/user/content/sql/create-cluster-replica.md
  doc/user/content/sql/create-cluster.md
  doc/user/content/sql/create-connection.md
  doc/user/content/sql/create-materialized-view.md
  doc/user/content/sql/create-sink.md
  doc/user/content/sql/create-source/_index.md
  doc/user/content/sql/create-source/kafka.md
  doc/user/content/sql/create-source/postgres.md
Labels: A-docs

#15581 Include map prefix in the `column_types` passed to `column_knowledge::optimize`
  src/transform/src/column_knowledge.rs
  test/sqllogictest/column_knowledge.slt
Labels: C-bug, A-optimization, P1, A-COMPUTE

#15476 Use index when `a=<literal>` gets an implicit cast
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/string.rs
  src/expr/src/scalar/mod.rs
  src/transform/src/canonicalize_mfp.rs
  test/sqllogictest/literal_constraints.slt
  test/sqllogictest/transform/aggregation_nullability.slt
Labels: A-sql, A-optimization, A-COMPUTE

#15609 [sinks] Allow non-default partition count for already-existing topic
  src/kafka-util/src/admin.rs
  test/testdrive/sinks.td
Labels: A-sink, A-STORAGE

#15640 [sinks] Add sink status history collection
  src/adapter/src/catalog/builtin.rs
  src/storage/src/controller.rs
  test/sqllogictest/cluster_log_drop.slt
  test/testdrive/catalog.td
  test/testdrive/status-history.td
Labels: A-sink, A-STORAGE

#15647 Add TPC-H output correctness test
  src/testdrive/src/action/sql.rs
  test/sqllogictest/tpch.slt
  test/testdrive/tpch.td
Labels: T-testing

#15671 compute: don't report empty frontiers during reconciliation
  src/compute/src/compute_state.rs
  src/compute/src/server.rs
Labels: M-release-blocker

#15586 [sinks] Create healthchecker and surface indefinite errors
  src/adapter/src/coord.rs
  src/adapter/src/coord/ddl.rs
  src/storage/src/controller.rs
  src/storage/src/protocol/client.rs
  src/storage/src/render/mod.rs
  src/storage/src/render/sinks.rs
  src/storage/src/sink/healthcheck.rs
  src/storage/src/sink/kafka.rs
  src/storage/src/sink/mod.rs
  src/storage/src/storage_state.rs
  src/storage/src/types/sinks.proto
  src/storage/src/types/sinks.rs
Labels: A-sink, A-STORAGE

#15703 Protect `Subscribe` against computed-based OOMs
  Cargo.lock
  src/adapter/src/subscribe.rs
  src/compute-client/Cargo.toml
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/response.proto
  src/compute-client/src/response.rs
  src/compute-client/src/service.rs
  src/compute/src/compute_state.rs
  src/compute/src/sink/subscribe.rs
  src/testdrive/src/action/sql.rs
  test/testdrive/oom.td
Labels: T-proto

#15743 [sinks] [kafka] Remove explicit Init/Running state machine
  src/storage/src/sink/kafka.rs
Labels: A-sink, A-STORAGE

#15679 Update index usage docs
  doc/user/content/ops/optimization.md
  doc/user/content/overview/arrangements.md
  doc/user/content/sql/create-index.md
Labels: A-docs

#15758 Handle replica-targeting in the compute controller
  src/compute-client/src/command.proto
  src/compute-client/src/command.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/controller/replica.rs
  src/compute/src/compute_state.rs
  src/compute/src/server.rs
Labels: T-proto
