Repository MaterializeInc/materialize, pull requests merged in 2022-11, with the labels that each got.

#15849 Always install introspection indexes
  src/compute-client/src/command.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/controller/replica.rs
  src/compute-client/src/logging.proto
  src/compute-client/src/logging.rs
  src/compute/src/compute_state.rs
  src/compute/src/logging/compute.rs
  src/compute/src/logging/differential.rs
  src/compute/src/logging/reachability.rs
  src/compute/src/logging/timely.rs
  src/compute/src/server.rs
  test/cluster/mzcompose.py
Labels: T-proto

#15888 optbench: add `--db-pass` and `--db-require-ssl` CLI options
  misc/python/materialize/cli/optbench.py
  misc/python/materialize/optbench/sql.py
  misc/python/stubs/pg8000/__init__.pyi
Labels: A-COMPUTE

#15894 docs: bootstrap reference docs folder
  doc/developer/reference/README.md
  doc/developer/reference/adapter/README.md
  doc/developer/reference/assets/platform-architecture-adapter.png
  doc/developer/reference/assets/platform-architecture-compute.png
  doc/developer/reference/assets/platform-architecture-storage.png
  doc/developer/reference/assets/platform-architecture.png
  doc/developer/reference/compute/README.md
  doc/developer/reference/storage/README.md
Labels: A-COMPUTE

#15871 Rewrite cluster startup flow to fix crash loops on restart
  misc/python/materialize/cloudtest/application.py
  misc/python/materialize/cloudtest/k8s/environmentd.py
  src/compute-client/src/command.proto
  src/compute-client/src/command.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/controller/replica.rs
  src/compute-client/src/service.rs
  src/compute/Cargo.toml
  src/compute/src/communication.rs
  src/compute/src/compute_state.rs
  src/compute/src/server.rs
  src/controller/src/lib.rs
  src/environmentd/src/lib.rs
  test/cloudtest/conftest.py
  test/cloudtest/test_computed_shared_fate.py
Labels: T-proto

#15744 [sinks] [status] Put sink status collection behind unsafe
  src/adapter/src/coord/ddl.rs
  test/testdrive/status-history.td
Labels: A-sink, A-STORAGE

#15517 Unify IndexedFilter printing between fast path and dataflow
  src/adapter/src/coord/peek.rs
  src/adapter/src/explain_new/mir/text.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/literal_constraints.slt
  test/sqllogictest/relation-cse.slt
  test/sqllogictest/system-cluster.slt
  test/sqllogictest/transform/dataflow.slt
  test/sqllogictest/transform/join_fusion.slt
  test/sqllogictest/transform/join_index.slt
  test/testdrive/subexpression-replacement.td
Labels: A-optimization, A-COMPUTE

#15953 docs: add `CONTRIBUTING.md` for reference developer docs
  doc/developer/reference/CONTRIBUTING.md
  doc/developer/reference/README.md
  doc/developer/reference/adapter/README.md
  doc/developer/reference/assets/environment-high-level-architecture-adapter.png
  doc/developer/reference/assets/environment-high-level-architecture-compute.png
  doc/developer/reference/assets/environment-high-level-architecture-storage.png
  doc/developer/reference/assets/environment-high-level-architecture.png
  doc/developer/reference/compute/README.md
  doc/developer/reference/storage/README.md
Labels: A-docs

#15966 Minor doc update for index lookups
  doc/user/content/ops/optimization.md
Labels: A-docs

#15927 storage: punctuation response for strict id checks
  src/storage-client/src/client.proto
  src/storage-client/src/client.rs
  src/storage-client/src/controller.rs
  src/storage-client/src/controller/rehydration.rs
  src/storage/src/server.rs
  src/storage/src/storage_state.rs
  src/storage/tests/setup.rs
Labels: T-proto

#16014 [sinks] Unify parameters of StorageSinkDesc
  src/storage-client/src/client.rs
  src/storage-client/src/controller.rs
  src/storage-client/src/types/sinks.rs
  src/storage/src/render/mod.rs
  src/storage/src/render/sinks.rs
  src/storage/src/sink/kafka.rs
  src/storage/src/storage_state.rs
Labels: A-sink, A-STORAGE

#15969 adapter: add `window_functions` feature flag
  src/adapter/src/catalog.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/session/vars.rs
  src/sql/src/catalog.rs
  src/sql/src/plan/optimize.rs
  src/sql/src/query_model/test/catalog.rs
  test/testdrive/session.td
Labels: A-optimization, A-ADAPTER

#16046 environmentd: make --bootstrap-system-var consistent
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/config.rs
  src/adapter/src/coord.rs
  src/environmentd/src/bin/environmentd/main.rs
  src/environmentd/src/lib.rs
  src/environmentd/tests/util.rs
  src/sqllogictest/src/runner.rs
  src/stash-debug/src/main.rs
  test/cluster/mzcompose.py
Labels: M-release-blocker

#16073 kafka-util: add info! log when rewriting a broker address
  src/kafka-util/src/client.rs
Labels: M-release-blocker

#15841 sql: fix database scoping in pg_catalog and information_schema
  Cargo.lock
  src/adapter/src/catalog/builtin.rs
  src/sqllogictest/Cargo.toml
  src/sqllogictest/src/runner.rs
  test/sqllogictest/information_schema_columns.slt
  test/sqllogictest/information_schema_tables.slt
  test/sqllogictest/pg_catalog_class.slt
  test/sqllogictest/pg_catalog_matviews.slt
  test/sqllogictest/pg_catalog_namespace.slt
  test/sqllogictest/pg_catalog_views.slt
  test/testdrive/catalog.td
Labels: M-release-blocker

#16147 Fix double localizing in `consequence_for_input`
  src/expr/src/relation/join_input_mapper.rs
  test/sqllogictest/transform/predicate_pushdown.slt
Labels: M-release-blocker, A-optimization, A-COMPUTE

#16295 Add a regression test for #16128
  test/sqllogictest/transform/predicate_pushdown.slt
Labels: T-testing, A-optimization, A-COMPUTE

#16292 Remove GROUP BY from `optimization.md`
  doc/user/content/ops/optimization.md
Labels: A-docs

#16350 adapter: don't panic in EXPLAIN if the expected stage is mising
  src/adapter/src/coord/sequencer.rs
Labels: A-optimization, A-ADAPTER

#16341 storage: correctly calculate the times to reclock to
  src/storage/src/source/reclock.rs
Labels: release-blocker

#16291 Fuse `InlineLet` and `UpdateLet` into `RelationCSE`
  src/transform/src/cse/relation_cse.rs
  src/transform/src/inline_let.rs
  src/transform/src/lib.rs
  src/transform/src/update_let.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
Labels: C-refactoring, A-optimization, A-COMPUTE

#16297 Add Differential join's start_keys to EXPLAIN
  src/adapter/src/explain_new/mir/text.rs
  test/sqllogictest/autogenerated/all_parts_essential.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/column_knowledge.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/funcs.slt
  test/sqllogictest/github-14116.slt
  test/sqllogictest/github-9147.slt
  test/sqllogictest/github-9782.slt
  test/sqllogictest/joins.slt
  test/sqllogictest/literal_constraints.slt
  test/sqllogictest/relation-cse.slt
  test/sqllogictest/scalar_subqueries_select_list.slt
  test/sqllogictest/subquery.slt
  test/sqllogictest/table_func.slt
  test/sqllogictest/tpch.slt
  test/sqllogictest/transform/aggregation_nullability.slt
  test/sqllogictest/transform/filter_index.slt
  test/sqllogictest/transform/is_null_propagation.slt
  test/sqllogictest/transform/join_fusion.slt
  test/sqllogictest/transform/join_index.slt
  test/sqllogictest/transform/lifting.slt
  test/sqllogictest/transform/predicate_pushdown.slt
  test/sqllogictest/transform/union.slt
  test/sqllogictest/window_funcs.slt
  test/testdrive/render-delta-join.td
Labels: A-optimization, A-COMPUTE
