Repository MaterializeInc/materialize, pull requests merged in 2022-08, with the labels that each got.

#13962 doc/user: document secrets
  doc/user/content/sql/alter-rename.md
  doc/user/content/sql/alter-secret.md
  doc/user/content/sql/create-connection.md
  doc/user/content/sql/create-secret.md
  doc/user/content/sql/drop-connection.md
  doc/user/content/sql/drop-secret.md
  doc/user/content/sql/show-secrets.md
  doc/user/layouts/partials/sql-grammar/alter-rename.svg
  doc/user/layouts/partials/sql-grammar/alter-secret.svg
  doc/user/layouts/partials/sql-grammar/create-secret.svg
  doc/user/layouts/partials/sql-grammar/drop-secret.svg
  doc/user/layouts/partials/sql-grammar/show-databases.svg
  doc/user/layouts/partials/sql-grammar/show-secrets.svg
  doc/user/sql-grammar/sql-grammar.bnf
Labels: A-docs

#14021 persist: assign gc work preferentially to writers
  src/persist-client/src/impl/encoding.rs
  src/persist-client/src/impl/gc.rs
  src/persist-client/src/impl/machine.rs
  src/persist-client/src/impl/maintenance.rs
  src/persist-client/src/impl/metrics.rs
  src/persist-client/src/impl/state.proto
  src/persist-client/src/impl/state.rs
  src/persist-client/src/impl/trace.rs
Labels: T-proto

#14031 New introspection source and view to show frontiers for storage source instantiations at the dataflow layer
  doc/user/content/sql/system-catalog.md
  src/adapter/src/catalog/builtin.rs
  src/compute-client/src/logging.proto
  src/compute-client/src/logging.rs
  src/compute/src/logging/compute.rs
  src/compute/src/render/mod.rs
  test/sqllogictest/cluster.slt
  test/testdrive/catalog.td
  test/testdrive/github-13790.td
  test/testdrive/introspection-sources.td
  test/testdrive/logging.td
Labels: T-proto

#14085 Remove some Threshold operators that have no effect
  src/transform/src/lib.rs
  src/transform/src/threshold_elision.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
  src/transform/tests/testdata/threshold_elision
  test/sqllogictest/transform/threshold_elision.slt
Labels: C-feature, A-optimization, A-COMPUTE

#14128 catalog: Allow for more builtin roles
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/builtin.rs
  src/adapter/src/catalog/builtin_table_updates.rs
  src/adapter/src/catalog/storage.rs
  src/sql/src/catalog.rs
  src/sql/src/names.rs
  test/cluster/mzcompose.py
  test/sqllogictest/id_reuse.slt
  test/sqllogictest/pg_catalog_roles.slt
  test/testdrive/roles.td
Labels: T-proto

#14208 Update command-and-response-binary-encoding.md
  doc/developer/command-and-response-binary-encoding.md
Labels: A-docs, T-proto

#14173 Sql: add single-param trunc
  doc/user/data/sql_funcs.yml
  src/expr/src/scalar.proto
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/float32.rs
  src/expr/src/scalar/func/impls/float64.rs
  src/expr/src/scalar/func/impls/numeric.rs
  src/pgrepr/src/oid.rs
  src/sql/src/func.rs
  test/sqllogictest/arithmetic.slt
  test/sqllogictest/numeric.slt
Labels: T-proto

#14187 transform: handle more cases in `ThresholdElision`
  src/expr/src/visit.rs
  src/transform/src/attribute/mod.rs
  src/transform/src/attribute/non_negative.rs
  src/transform/src/attribute/subtree_size.rs
  src/transform/src/column_knowledge.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/threshold_elision.rs
  src/transform/tests/testdata/threshold_elision
  test/sqllogictest/transform/threshold_elision.slt
Labels: A-optimization, A-COMPUTE

#14209 Retractable upsert errors
  src/storage/src/decode/avro.rs
  src/storage/src/decode/csv.rs
  src/storage/src/decode/mod.rs
  src/storage/src/decode/protobuf.rs
  src/storage/src/render/debezium.rs
  src/storage/src/render/sources.rs
  src/storage/src/render/upsert.rs
  src/storage/src/source/persist_source.rs
  src/storage/src/types/errors.proto
  src/storage/src/types/errors.rs
  test/cluster/mzcompose.py
  test/cluster/upsert/01-create-sources.td
  test/cluster/upsert/02-after-storaged-restart.td
  test/testdrive/kafka-envelope-none.td
Labels: M-release-blocker

#14252 doc/user: unstable docs more apparent, less threatening
  doc/user/assets/sass/_layout.scss
  doc/user/layouts/partials/header.html
Labels: A-docs

#14247 Revert the removal of the literal constraints detection code in lowering
  src/compute-client/src/plan/mod.rs
Labels: C-refactoring, A-optimization, A-COMPUTE

#14258 Decompose record in `Literal(record(c1, c2)) = record_create(e1, e2)`
  src/expr/src/scalar/mod.rs
  test/sqllogictest/record.slt
Labels: C-feature, A-optimization, A-COMPUTE

#14033 adapter: implement `EXPLAIN ... AS TEXT` for `Mir` plans
  src/adapter/src/coord/peek.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/explain_new/common.rs
  src/adapter/src/explain_new/hir/mod.rs
  src/adapter/src/explain_new/hir/text.rs
  src/adapter/src/explain_new/mir/mod.rs
  src/adapter/src/explain_new/mir/text.rs
  src/adapter/src/explain_new/mod.rs
  src/expr/src/lib.rs
  src/expr/src/relation/mod.rs
  src/ore/src/str.rs
  src/repr/src/explain_new.rs
  test/sqllogictest/explain/decorrelated_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
Labels: C-feature, A-optimization, A-ADAPTER

#14286 adapter: align fast and slow path output for `EXPLAIN ... AS TEXT`
  src/adapter/src/coord/peek.rs
  src/adapter/src/explain_new/mod.rs
  src/ore/src/str.rs
  src/repr/src/explain_new.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
Labels: C-refactoring, A-optimization, A-COMPUTE

#14404 Update command-and-response-binary-encoding.md
  doc/developer/command-and-response-binary-encoding.md
Labels: A-docs, T-proto

#14402 compute: remove remnants of Kafka sinks
  Cargo.lock
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/coord/sequencer.rs
  src/compute-client/src/controller.rs
  src/compute/Cargo.toml
  src/compute/src/bin/computed.rs
  src/compute/src/compute_state.rs
  src/compute/src/render/sinks.rs
  src/compute/src/server.rs
  src/compute/src/sink/persist_sink.rs
  src/compute/src/sink/tail.rs
  src/storage/src/types/sinks.proto
  src/storage/src/types/sinks.rs
Labels: T-proto

#14403 Literal constraints -- support multiple lookups on fast path
  src/adapter/src/coord/peek.rs
  src/compute-client/src/command.proto
  src/compute-client/src/command.rs
  src/compute-client/src/controller.rs
  src/compute/src/compute_state.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/literal_constraints.slt
Labels: A-optimization, A-COMPUTE, T-proto

#14464 Don't generate empty literal_constraints in Arbitrary Peek
  src/compute-client/src/command.rs
Labels: A-COMPUTE

#14465 Decompose `record_create(...) = record_create(...)`
  src/expr/src/scalar/mod.rs
  test/sqllogictest/literal_constraints.slt
Labels: A-optimization, A-COMPUTE

#14466 Fix NonNegative attribute on constant collections
  src/transform/src/attribute/non_negative.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
Labels: A-optimization, A-COMPUTE

#14378 Non-differential FrontierUppers
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/timestamp_selection.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/replicated.rs
  src/compute-client/src/response.rs
  src/compute-client/src/service.rs
  src/compute/src/compute_state.rs
  src/storage/src/controller.rs
  src/storage/src/controller/rehydration.rs
  src/storage/src/protocol/client.proto
  src/storage/src/protocol/client.rs
  src/storage/src/storage_state.rs
  src/timely-util/src/progress.rs
Labels: M-release-blocker, T-proto

#14408 compute-client: remove DataflowDescription::id
  src/compute-client/src/command.proto
  src/compute-client/src/command.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/replicated.rs
  src/compute-client/src/plan/mod.rs
  src/compute-client/src/service.rs
Labels: T-proto

#14534 Remove duplicates from indexes_to_undistribute
  src/expr/src/scalar/mod.rs
  test/sqllogictest/literal_constraints.slt
Labels: A-optimization, A-COMPUTE, M-green-builds

#14441 Avoid crash during the handling of a RecursionLimitError
  src/expr/src/relation/mod.rs
  src/ore/src/stack.rs
  src/transform/src/lib.rs
Labels: A-optimization, A-COMPUTE
