Repository MaterializeInc/materialize, pull requests merged in 2022-02, with the labels that each got.

#10377 Update `doc/developer/platform/README.md`
  doc/developer/platform/README.md
Labels: A-docs

#10371 qgm: add `NonNullRequirements` derived attribute
  src/sql/src/query_model/attribute/mod.rs
  src/sql/src/query_model/attribute/non_null_requirements.rs
  src/sql/src/query_model/rewrite/mod.rs
  src/sql/src/query_model/test/catalog.rs
  src/sql/src/query_model/test/mod.rs
  src/sql/src/query_model/test/util.rs
  src/sql/src/query_model/validator/quantifier.rs
Labels: C-feature, A-optimization

#10493 doc/user: Update dbt guide
  doc/user/content/guides/dbt.md
  misc/dbt-materialize/README.md
Labels: A-docs

#10435 qgm: add `RejectedNulls` derived attribute
  src/sql/src/query_model/attribute/mod.rs
  src/sql/src/query_model/attribute/propagated_nulls.rs
  src/sql/src/query_model/attribute/rejected_nulls.rs
  src/sql/src/query_model/test/util.rs
Labels: C-feature, A-optimization

#10529 doc/user: Change default in `topic_metadata_refresh_interval_ms` to 300 seconds
  doc/user/layouts/partials/create-source/connector/kafka/with-options.html
Labels: A-docs

#10532 Support additional date/time units for interval parsing
  doc/user/content/release-notes.md
  doc/user/layouts/partials/sql-grammar/time-unit.svg
  doc/user/sql-grammar/sql-grammar.bnf
  src/repr/src/adt/datetime.rs
  src/repr/src/adt/interval.rs
  src/sql-parser/src/ast/defs/value.rs
  src/sql/src/plan/query.rs
  test/sqllogictest/interval.slt
Labels: C-feature, A-sql

#10528 doc/user: Update Postgres source documentation page and guides
  doc/user/content/guides/cdc-postgres.md
  doc/user/content/guides/postgres-cloud.md
  doc/user/content/release-notes.md
  doc/user/content/sql/create-source/postgres.md
  doc/user/content/third-party/debezium.md
Labels: A-docs

#10690 doc/user: Update CDC guides
  doc/user/content/guides/cdc-mysql.md
  doc/user/content/guides/cdc-postgres.md
  doc/user/content/sql/create-source/postgres.md
Labels: A-docs

#10517 Add issue template for a proposal for a new optimization.
  .github/ISSUE_TEMPLATE/07-optimization.yml
Labels: A-optimization

#10710 materialized: add missing "MZ_" prefix to new frontegg environment variables
  src/materialized/src/bin/materialized/main.rs
Labels: M-release-blocker

#10752 Decorrelation: Do not attempt outer join if the join kind is inner.
  src/sql/src/plan/lowering.rs
  test/sqllogictest/cte_lowering.slt
Labels: C-bug, A-optimization

#10753 Prevent paninc on Interval negation
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/interval.rs
  src/repr/src/adt/interval.rs
  test/sqllogictest/dates-times.slt
  test/sqllogictest/interval.slt
Labels: C-bug, A-sql, P2

#10678 doc/user: Merge all Kafka documentation pages into one + restructure the content
  doc/user/content/connect/materialize-cdc.md
  doc/user/content/guides/cdc-mysql.md
  doc/user/content/guides/cdc-postgres.md
  doc/user/content/ops/memory.md
  doc/user/content/overview/api-components.md
  doc/user/content/release-notes.md
  doc/user/content/sql/create-sink.md
  doc/user/content/sql/create-source/avro-kafka.md
  doc/user/content/sql/create-source/csv-kafka.md
  doc/user/content/sql/create-source/json-kafka.md
  doc/user/content/sql/create-source/kafka.md
  doc/user/content/sql/create-source/protobuf-kafka.md
  doc/user/content/sql/create-source/text-kafka.md
  doc/user/content/third-party/debezium.md
  doc/user/layouts/partials/create-source/connector/kafka/syntax.html
  doc/user/layouts/partials/create-source/envelope/debezium/syntax.html
  doc/user/layouts/partials/create-source/envelope/upsert/syntax.html
  doc/user/layouts/partials/create-source/key-constraint/details.html
  doc/user/layouts/partials/create-source/key-constraint/syntax.html
  doc/user/layouts/partials/sql-grammar/create-source-kafka.svg
  doc/user/layouts/partials/sql-grammar/format-spec.svg
  doc/user/layouts/shortcodes/create-source/syntax-connector-details.html
  doc/user/sql-grammar/sql-grammar.bnf
Labels: A-docs

#10679 QGM: Lower outer join boxes
  src/sql/src/plan/lowering.rs
  src/sql/src/query_model/mir.rs
  src/sql/src/query_model/model/graph.rs
  src/sql/tests/querymodel/lowering
Labels: C-feature, A-optimization

#10851 qgm: Handle QGM ⇒ MIR lowering of global aggregates
  src/sql/src/query_model/mir.rs
  src/sql/tests/querymodel/lowering
Labels: C-bug, T-correctness, A-optimization

#10885 Implement justify interval methods
  doc/user/content/sql/functions/justify-days.md
  doc/user/content/sql/functions/justify-hours.md
  doc/user/content/sql/functions/justify-interval.md
  doc/user/content/sql/types/interval.md
  doc/user/data/sql_funcs.yml
  doc/user/layouts/partials/sql-grammar/func-justify-days.svg
  doc/user/layouts/partials/sql-grammar/func-justify-hours.svg
  doc/user/layouts/partials/sql-grammar/func-justify-interval.svg
  doc/user/sql-grammar/sql-grammar.bnf
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/interval.rs
  src/repr/src/adt/interval.rs
  src/sql/src/func.rs
  test/sqllogictest/interval.slt
Labels: C-feature, A-sql

#10949 doc/user: Move metabase to "beta", remove forked driver reference
  doc/user/content/third-party/supported-tools.md
Labels: A-docs
