Repository MaterializeInc/materialize, pull requests merged in 2022-03, with the labels that each got.

#10860 Expr/relation: Minor interface changes
  src/expr/src/relation/join_input_mapper.rs
  src/expr/src/relation/mod.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/query_model/mir.rs
  src/transform/src/reduction_pushdown.rs
Labels: C-refactoring, A-optimization

#10964 expr: fix (modulo) division type inference
  src/expr/src/scalar/func.rs
Labels: A-sql, C-refactoring

#10494 doc/user: Add systemd instructions
  doc/user/content/install.md
Labels: A-docs

#10980 Support \d <object> meta command
  doc/user/content/sql/system-catalog.md
  doc/user/data/sql_funcs.yml
  src/coord/src/catalog/builtin.rs
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/oid.rs
  src/sql-parser/src/keywords.txt
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
  src/sql/src/func.rs
  src/sql/src/plan/query.rs
  test/sqllogictest/pg_catalog_attribute.slt
  test/sqllogictest/pg_catalog_class.slt
  test/sqllogictest/pg_get_constraintdef.slt
  test/sqllogictest/pg_get_indexdef.slt
  test/testdrive/catalog.td
  test/testdrive/pg-catalog.td
Labels: C-feature, A-sql

#10897 QGM: Add support for QGM error in QGM -> MIR lowering
  src/coord/src/coord.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/optimize.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/query_model/error.rs
  src/sql/src/query_model/hir.rs
  src/sql/src/query_model/mir.rs
  src/sql/src/query_model/model/graph.rs
  src/sql/src/query_model/test/mod.rs
  src/sql/tests/querymodel/lowering
Labels: C-feature, A-optimization

#10901 qgm: add type inference support
  ci/test/slt-fast.sh
  src/coord/src/coord.rs
  src/sql/src/query_model/attribute/core.rs
  src/sql/src/query_model/attribute/mod.rs
  src/sql/src/query_model/attribute/relation_type.rs
  src/sql/src/query_model/dot.rs
  src/sql/src/query_model/error.rs
  src/sql/src/query_model/hir.rs
  src/sql/src/query_model/model/graph.rs
  src/sql/src/query_model/model/scalar.rs
  src/sql/src/query_model/test/mod.rs
  src/sql/src/query_model/test/util.rs
  test/sqllogictest/qgm/qgm-type-inference.slt
Labels: C-feature, A-sql, A-optimization

#11101 qgm: introduce `RequiredAttributes` type
  src/sql/src/query_model/attribute/core.rs
  src/sql/src/query_model/dot.rs
  src/sql/src/query_model/model/graph.rs
  src/sql/src/query_model/rewrite/mod.rs
Labels: C-refactoring, A-optimization

#11184 doc/user: Make function names searchable in docs
  doc/user/layouts/shortcodes/fnlist.html
Labels: A-docs

#11220 qgm: reorganize hir module structure
  src/sql/src/query_model/attribute/propagated_nulls.rs
  src/sql/src/query_model/attribute/rejected_nulls.rs
  src/sql/src/query_model/attribute/relation_type.rs
  src/sql/src/query_model/hir/hir_from_qgm.rs
  src/sql/src/query_model/hir/mod.rs
  src/sql/src/query_model/hir/qgm_from_hir.rs
  src/sql/src/query_model/model/graph.rs
  src/sql/src/query_model/rewrite/mod.rs
  src/sql/src/query_model/validator/quantifier.rs
Labels: C-refactoring, A-optimization

#11228 qgm: add `Union` support to `FromHir`
  src/sql/src/query_model/hir/qgm_from_hir.rs
  src/sql/src/query_model/model/graph.rs
  src/sql/tests/querymodel/basic
Labels: C-feature, A-optimization

#11267 Change cloud sign up link
  doc/user/content/cloud/_index.md
  doc/user/layouts/partials/header.html
Labels: A-docs

#11253 expr: add unique key information to `TableFunc::output_type()`
  src/expr/src/relation/func.rs
Labels: C-feature, A-sql

#11252 qgm: add `CallTable` support to `FromHir`
  src/sql/src/query_model/dot.rs
  src/sql/src/query_model/hir/qgm_from_hir.rs
  src/sql/src/query_model/model/graph.rs
  src/sql/src/query_model/validator/quantifier.rs
  src/sql/tests/querymodel/basic
Labels: C-feature, A-optimization

#11299 doc/user: Improve icons on supported tools page
  doc/user/assets/sass/_content.scss
  doc/user/assets/sass/main.scss
  doc/user/content/third-party/supported-tools.md
  doc/user/layouts/_default/baseof.html
  doc/user/layouts/partials/inline-svgs.html
  doc/user/layouts/shortcodes/supportLevel.html
Labels: A-docs

#11305 doc/user: Add "click to copy" on docs codeblocks
  doc/user/assets/sass/_content.scss
  doc/user/layouts/_default/baseof.html
Labels: A-docs

#11316 doc/user: Add header tags to enable rich snippets for docs links
  doc/user/layouts/_default/baseof.html
  doc/user/layouts/partials/head.html
  doc/user/static/images/materialize-horizontal.png
  doc/user/static/images/materialize-symbol.png
  doc/user/static/images/materialize_favicon_32.png
  doc/user/static/images/materialize_logo.svg
  doc/user/static/images/materialize_logo_180.png
Labels: A-docs

#11174 doc/user: add golang guide
  doc/user/content/guides/golang.md
Labels: A-docs

#11243 QGM => HIR
  src/sql/src/query_model/error.rs
  src/sql/src/query_model/hir/hir_from_qgm.rs
  src/sql/src/query_model/mir.rs
  src/sql/src/query_model/model/graph.rs
  src/sql/src/query_model/test/mod.rs
  src/sql/tests/querymodel/hirroundtrip
Labels: C-feature, A-optimization
