Repository MaterializeInc/materialize, pull requests merged in 2022-07, with the labels that each got.

#13370 repr: introduce new API for explaining plans
  ci/slt/slt.sh
  ci/test/slt-fast.sh
  src/adapter/src/coord.rs
  src/adapter/src/error.rs
  src/adapter/src/explain_new/common.rs
  src/adapter/src/explain_new/hir/mod.rs
  src/adapter/src/explain_new/hir/text.rs
  src/adapter/src/explain_new/lir/json.rs
  src/adapter/src/explain_new/lir/mod.rs
  src/adapter/src/explain_new/mir/mod.rs
  src/adapter/src/explain_new/mir/text.rs
  src/adapter/src/explain_new/mod.rs
  src/adapter/src/explain_new/qgm/dot.rs
  src/adapter/src/explain_new/qgm/mod.rs
  src/adapter/src/lib.rs
  src/pgwire/src/message.rs
  src/repr/src/explain_new.rs
  src/repr/src/lib.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/keywords.txt
  src/sql-parser/src/parser.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
  test/sqllogictest/explain/bad_explain_statements.slt
  test/sqllogictest/explain/decorrelated_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/optimized_query_graph_as_dot.slt
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/query_graph_as_dot.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
Labels: C-feature, A-optimization, A-COMPUTE

#13475 doc/developer: Fix broken links in the "Query Compilation 101" guide
  doc/developer/101-query-compilation.md
Labels: A-docs, A-optimization

#13581 Add common explanation structures
  src/adapter/src/catalog.rs
  src/adapter/src/coord.rs
  src/adapter/src/explain_new/common.rs
  src/adapter/src/explain_new/hir/text.rs
  src/adapter/src/explain_new/lir/json.rs
  src/adapter/src/explain_new/mir/text.rs
  src/adapter/src/explain_new/mod.rs
  src/adapter/src/explain_new/qgm/dot.rs
  src/compute-client/src/explain.rs
  src/expr-test-util/src/lib.rs
  src/expr/src/explain.rs
  src/expr/src/lib.rs
  src/expr/src/relation/mod.rs
  src/ore/src/str.rs
  src/repr/src/explain_new.rs
  src/sql/src/catalog.rs
  src/sql/src/plan/explain.rs
  src/sql/src/plan/expr.rs
  src/sql/src/query_model/dot.rs
  src/sql/src/query_model/test/catalog.rs
Labels: C-feature, A-optimization, A-COMPUTE

#13625 doc/developer: update `command-and-response-binary-encoding.md`
  doc/developer/command-and-response-binary-encoding.md
Labels: A-docs

#13646 sql: do not require CERTIFICATE AUTHORITY in CONNECTION
  src/sql/src/plan/statement/ddl.rs
  src/storage/src/types/connections.rs
  test/kafka-sasl-plain/smoketest.td
  test/kafka-ssl/smoketest.td
Labels: T-proto

#13656 persist: finish wiring up seqno-capability based blob gc
  src/persist-client/benches/porcelain.rs
  src/persist-client/examples/maelstrom/txn.rs
  src/persist-client/examples/source_example.rs
  src/persist-client/src/impl/encoding.rs
  src/persist-client/src/impl/gc.rs
  src/persist-client/src/impl/machine.rs
  src/persist-client/src/impl/metrics.rs
  src/persist-client/src/impl/state.proto
  src/persist-client/src/impl/state.rs
  src/persist-client/src/lib.rs
  src/persist-client/src/read.rs
  src/storage/src/source/persist_source.rs
  src/storage/src/source/reclock.rs
Labels: T-proto

#13707 adapter: Add `EXPLAIN ... AS TEXT` support for single-output `HIR` stages
  src/adapter/src/coord.rs
  src/adapter/src/explain_new/hir/mod.rs
  src/adapter/src/explain_new/hir/text.rs
  src/adapter/src/explain_new/mod.rs
  src/expr/src/relation/mod.rs
  src/ore/src/str.rs
  src/repr/src/explain_new.rs
  test/sqllogictest/explain/raw_plan_as_text.slt
Labels: C-feature, A-optimization, A-COMPUTE

#13757 expr: introduce `Visit*` framework for `HIR` types
  src/expr/src/relation/mod.rs
  src/expr/src/scalar/mod.rs
  src/expr/src/visit.rs
  src/sql/src/plan.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/transform_expr.rs
  src/sql/src/query_model/hir/qgm_from_hir.rs
  src/transform/src/cse/relation_cse.rs
  src/transform/src/update_let.rs
Labels: A-optimization, A-COMPUTE

#13731 Make AND/OR variadic.
  src/adapter/src/explain_new/hir/text.rs
  src/expr/src/linear.rs
  src/expr/src/relation/canonicalize.rs
  src/expr/src/scalar.proto
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/mod.rs
  src/expr/tests/testdata/reduce
  src/sql/src/plan/explain.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/transform_ast.rs
  src/sql/src/plan/transform_expr.rs
  src/sql/src/query_model/attribute/rejected_nulls.rs
  src/sql/src/query_model/hir/hir_from_qgm.rs
  src/sql/src/query_model/model/scalar.rs
  src/sql/src/query_model/test/util.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/tests/testdata/canonicalize_mfp
  src/transform/tests/testdata/join-implementation
  src/transform/tests/testdata/predicate-pushdown
  src/transform/tests/testdata/steps
  test/sqllogictest/autogenerated/all_parts_essential.slt
  test/sqllogictest/boolean.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/column_knowledge.slt
  test/sqllogictest/github-9027.slt
  test/sqllogictest/in_list.slt
  test/sqllogictest/qgm/qgm-type-inference.slt
  test/sqllogictest/tpch.slt
  test/testdrive/subexpression-replacement.td
  test/testdrive/temporal.td
Labels: T-proto

#13917 storage: don't keep status_shard for non-sources
  src/storage/src/controller.proto
  src/storage/src/controller.rs
  src/storage/src/source/reclock.rs
Labels: T-proto

#13904 Introspection materialization lag 13489
  doc/user/content/sql/system-catalog.md
  src/adapter/src/catalog/builtin.rs
  src/compute-client/src/logging.proto
  src/compute-client/src/logging.rs
  src/compute/src/logging/compute.rs
  src/compute/src/render/mod.rs
  test/sqllogictest/cluster.slt
  test/testdrive/catalog.td
  test/testdrive/introspection-sources.td
  test/testdrive/logging.td
Labels: T-proto
