Repository MaterializeInc/materialize, pull requests merged in 2022-05, with the labels that each got.

#12271 expr,dataflow-types: enable `peek_protobuf_roundtrip` test
  src/dataflow-types/src/client.rs
  src/expr/src/linear.rs
Labels: C-feature, C-refactoring, A-COMPUTE

#12238 dbt-materialize: continous testing using --store-failures
  misc/dbt-materialize/CHANGELOG.md
  misc/dbt-materialize/README.md
  misc/dbt-materialize/dbt/adapters/materialize/__version__.py
  misc/dbt-materialize/dbt/include/materialize/macros/materializations/test.sql
  misc/dbt-materialize/setup.py
  misc/dbt-materialize/test/materialize.dbtspec
Labels: T-dbt

#12281 dataflow-types: enable `join_plan_protobuf_roundtrip` test
  src/dataflow-types/src/client.rs
  src/dataflow-types/src/plan/join/delta_join.rs
  src/dataflow-types/src/plan/join/linear_join.rs
  src/dataflow-types/src/plan/join/mod.rs
  src/expr/src/scalar/mod.rs
Labels: C-feature, C-refactoring, A-COMPUTE

#12328 dataflow-types,expr: use fewer cases for some `protobuf_roundtrip` tests
  src/dataflow-types/src/client.rs
  src/dataflow-types/src/plan/join/mod.rs
  src/expr/src/linear.rs
Labels: C-refactoring, A-COMPUTE

#12241 dataflow-types: Protobuf support for DataflowDescription.
  src/dataflow-types/build.rs
  src/dataflow-types/src/client.rs
  src/dataflow-types/src/client/controller/storage.proto
  src/dataflow-types/src/client/controller/storage.rs
  src/dataflow-types/src/types.proto
  src/dataflow-types/src/types.rs
  src/repr/src/adt/regex.rs
  src/repr/src/lib.rs
  src/repr/src/proto.rs
  src/repr/src/relation.rs
  src/repr/src/relation_and_scalar.proto
Labels: C-feature, A-COMPUTE

#12343 repr: refactor the `Arbitrary` implementation for `Row`
  src/dataflow-types/src/plan/mod.rs
  src/expr/src/scalar/mod.rs
  src/repr/src/lib.rs
  src/repr/src/row.rs
  src/repr/src/scalar.rs
  src/repr/tests/rows.rs
Labels: C-feature, C-refactoring, A-COMPUTE

#12357 repr: use `ProtoNaiveDate` instead of `ProtoDate` in `row.proto`
  src/repr/build.rs
  src/repr/src/adt/interval.proto
  src/repr/src/adt/interval.rs
  src/repr/src/chrono.proto
  src/repr/src/chrono.rs
  src/repr/src/row.proto
  src/repr/src/row/encoding.rs
Labels: C-refactoring, A-COMPUTE

#12395 doc/developer: add "Command and Response Binary Encoding" design doc
  doc/developer/design/20220511_command_and_response_binary_encoding.md
Labels: A-docs, A-COMPUTE

#12428 dbt-materialize audit adapter macros
  misc/dbt-materialize/dbt/adapters/materialize/__init__.py
  misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql
Labels: T-dbt

#12433 dataflow-types: Protobuf support for ComputeCommand (w/ proptest).
  src/dataflow-types/src/client.proto
  src/dataflow-types/src/client.rs
Labels: C-feature, A-COMPUTE

#12453 dataflow-types: Protobuf support for ComputeResponse.
  src/dataflow-types/src/client.proto
  src/dataflow-types/src/client.rs
  src/dataflow-types/src/types.proto
  src/dataflow-types/src/types.rs
  src/repr/src/proto.rs
Labels: C-feature, A-COMPUTE

#12419 doc/developer: add "Command and Response Binary Encoding" developer guide
  doc/developer/command_and_response_binary_encoding.md
  src/repr/src/chrono.rs
Labels: A-docs, A-STORAGE, A-COMPUTE

#12589 repr: introduce new `Proto$T`-conversion API
  src/repr/src/proto.rs
Labels: C-refactoring

#12594 repr: migrate code to the new `Proto$T`-conversion API
  src/coord/src/catalog/storage.rs
  src/dataflow-types/src/client.rs
  src/dataflow-types/src/errors.rs
  src/dataflow-types/src/logging.rs
  src/dataflow-types/src/plan/mod.rs
  src/dataflow-types/src/types.rs
  src/expr/src/id.rs
  src/expr/src/relation/func.rs
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/like_pattern.rs
  src/expr/src/scalar/mod.rs
  src/repr/src/adt/array.rs
  src/repr/src/adt/char.rs
  src/repr/src/adt/datetime.rs
  src/repr/src/adt/interval.rs
  src/repr/src/adt/numeric.rs
  src/repr/src/adt/regex.rs
  src/repr/src/adt/varchar.rs
  src/repr/src/chrono.rs
  src/repr/src/global_id.rs
  src/repr/src/relation.rs
  src/repr/src/row/encoding.rs
  src/repr/src/scalar.rs
  src/repr/src/strconv.rs
Labels: C-refactoring

#12632 expr,dataflow-types: migrate code to the new `Proto$T`-conversion API
  src/coord/src/catalog/storage.rs
  src/dataflow-types/src/client.rs
  src/dataflow-types/src/client/controller/storage.rs
  src/dataflow-types/src/errors.rs
  src/dataflow-types/src/logging.rs
  src/dataflow-types/src/plan/join/delta_join.rs
  src/dataflow-types/src/plan/join/linear_join.rs
  src/dataflow-types/src/plan/join/mod.rs
  src/dataflow-types/src/plan/mod.rs
  src/dataflow-types/src/plan/reduce.rs
  src/dataflow-types/src/plan/threshold.rs
  src/dataflow-types/src/plan/top_k.rs
  src/dataflow-types/src/types.rs
  src/expr/src/id.rs
  src/expr/src/linear.rs
  src/expr/src/relation/func.rs
  src/expr/src/relation/mod.rs
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/like_pattern.rs
  src/expr/src/scalar/mod.rs
  src/kafka-util/src/addr.rs
  src/repr/src/adt/array.rs
  src/repr/src/adt/char.rs
  src/repr/src/adt/datetime.rs
  src/repr/src/adt/interval.rs
  src/repr/src/adt/numeric.rs
  src/repr/src/adt/regex.rs
  src/repr/src/adt/varchar.rs
  src/repr/src/chrono.rs
  src/repr/src/global_id.rs
  src/repr/src/proto.rs
  src/repr/src/relation.rs
  src/repr/src/row/encoding.rs
  src/repr/src/scalar.rs
  src/repr/src/strconv.rs
Labels: C-refactoring

#12671 repr: implement `RustType` for `prost` scalar types and update developer guide
  doc/developer/command_and_response_binary_encoding.md
  src/repr/src/proto.rs
Labels: C-feature, A-docs
