Repository MaterializeInc/materialize, pull requests merged in 2022-04, with the labels that each got.

#11595 repr: add `ProtoRepr` trait
  src/repr/src/proto/adt/array.rs
  src/repr/src/proto/mod.rs
Labels: C-refactoring

#11536 sql: Dynamically allocate system global IDs
  src/coord/src/catalog.rs
  src/coord/src/catalog/builtin.rs
  src/coord/src/catalog/builtin_table_updates.rs
  src/coord/src/catalog/storage.rs
  src/coord/src/coord.rs
  src/coord/src/coord/prometheus.rs
  src/coord/tests/testdata/t
  src/sql/src/catalog.rs
  src/sql/src/plan.rs
  test/testdrive/logging.td
  test/upgrade/check-from-current_source-view-on-builtin.td
  test/upgrade/create-in-any_version-view-on-builtin.td
Labels: A-sql, A-platform

#11607 repr: add `strconv.proto`
  src/repr/build.rs
  src/repr/src/proto/adt/array.rs
  src/repr/src/proto/mod.rs
  src/repr/src/proto/row.proto
  src/repr/src/proto/strconv.proto
  src/repr/src/proto/strconv.rs
  src/repr/src/strconv.rs
Labels: A-optimization

#11647 repr: add `TryIntoIfSome` trait
  src/repr/src/proto/mod.rs
Labels: C-refactoring, A-COMPUTE

#11642 coord,sql: Support `pg_get_viewdef` SQL functions
  doc/user/content/sql/system-catalog.md
  doc/user/data/sql_funcs.yml
  src/coord/src/catalog/builtin.rs
  src/coord/src/catalog/builtin_table_updates.rs
  src/sql/src/func.rs
  test/sqllogictest/pg_catalog_views.slt
  test/sqllogictest/pg_get_viewdef.slt
  test/testdrive/timelines.td
Labels: C-feature, A-sql

#11717 expr,repr: cross-crate test dependencies
  Cargo.lock
  src/expr/Cargo.toml
  src/expr/src/id.rs
  src/expr/src/scalar/mod.rs
  src/repr/Cargo.toml
  src/repr/src/adt/array.rs
  src/repr/src/adt/char.rs
  src/repr/src/adt/numeric.rs
  src/repr/src/adt/varchar.rs
  src/repr/src/strconv.rs
Labels: C-refactoring, A-COMPUTE

#11761 expr: add protobuf support for `UnmaterializableFunc`
  src/expr/build.rs
  src/expr/src/proto/id.rs
  src/expr/src/proto/scalar/func.proto
  src/expr/src/proto/scalar/func.rs
  src/expr/src/proto/scalar/mod.rs
  src/expr/src/scalar/func.rs
  src/repr/src/proto/adt/array.rs
  src/repr/src/proto/adt/char.rs
  src/repr/src/proto/adt/numeric.rs
  src/repr/src/proto/adt/varchar.rs
Labels: C-feature, A-COMPUTE

#11801 expr: Add protobuf for chrono types
  src/repr/build.rs
  src/repr/src/adt/datetime.rs
  src/repr/src/chrono.rs
  src/repr/src/lib.rs
  src/repr/src/proto/adt/datetime.proto
  src/repr/src/proto/adt/datetime.rs
  src/repr/src/proto/adt/mod.rs
  src/repr/src/proto/chrono.proto
  src/repr/src/proto/chrono.rs
  src/repr/src/proto/mod.rs
Labels: C-feature, A-COMPUTE

#11803 expr: stub protobuf support for `BinaryFunc`
  src/expr/src/scalar/func.proto
  src/expr/src/scalar/func.rs
Labels: C-feature, A-COMPUTE

#11823 expr: stub protobuf support for `VariadicFunc`
  src/expr/src/scalar/func.proto
  src/expr/src/scalar/func.rs
Labels: C-feature, A-COMPUTE

#11902 expr: add protobuf support for `VariadicFunc` (complete)
  src/expr/build.rs
  src/expr/src/scalar/func.proto
  src/expr/src/scalar/func.rs
  src/repr/src/chrono.rs
  src/repr/src/lib.rs
Labels: C-feature, A-COMPUTE

#11887 expr: common visitor implementation for `Mir*Expr` types
  src/coord/src/coord/dataflow_builder.rs
  src/expr/src/lib.rs
  src/expr/src/linear.rs
  src/expr/src/relation/canonicalize.rs
  src/expr/src/relation/join_input_mapper.rs
  src/expr/src/relation/mod.rs
  src/expr/src/scalar/mod.rs
  src/expr/src/visit.rs
  src/transform/src/canonicalize_mfp.rs
  src/transform/src/column_knowledge.rs
  src/transform/src/cse/relation_cse.rs
  src/transform/src/dataflow.rs
  src/transform/src/fusion/filter.rs
  src/transform/src/fusion/flatmap_to_map.rs
  src/transform/src/fusion/join.rs
  src/transform/src/fusion/map.rs
  src/transform/src/fusion/negate.rs
  src/transform/src/fusion/project.rs
  src/transform/src/fusion/reduce.rs
  src/transform/src/fusion/top_k.rs
  src/transform/src/fusion/union.rs
  src/transform/src/inline_let.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/map_lifting.rs
  src/transform/src/monotonic.rs
  src/transform/src/nonnullable.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/projection_extraction.rs
  src/transform/src/projection_pushdown.rs
  src/transform/src/reduce_elision.rs
  src/transform/src/reduction.rs
  src/transform/src/reduction_pushdown.rs
  src/transform/src/redundant_join.rs
  src/transform/src/topk_elision.rs
  src/transform/src/union_cancel.rs
  src/transform/src/update_let.rs
Labels: C-refactoring, A-optimization

#11763 Guide to connect AWS MSK to Materialize
  doc/user/content/integrations/aws-msk.md
Labels: A-docs

#11925 expr: add protobuf support for `BinaryFunc` (complete)
  src/expr/build.rs
  src/expr/src/scalar/func.proto
  src/expr/src/scalar/func.rs
Labels: C-feature, A-COMPUTE

#11940 expr: add protobuf support for `UnaryFunc` (almost complete)
  src/expr/build.rs
  src/expr/src/scalar/func.proto
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/array.rs
  src/expr/src/scalar/func/impls/char.rs
  src/expr/src/scalar/func/impls/date.rs
  src/expr/src/scalar/func/impls/int2vector.rs
  src/expr/src/scalar/func/impls/jsonb.rs
  src/expr/src/scalar/func/impls/list.rs
  src/expr/src/scalar/func/impls/map.rs
  src/expr/src/scalar/func/impls/numeric.rs
  src/expr/src/scalar/func/impls/record.rs
  src/expr/src/scalar/func/impls/string.rs
  src/expr/src/scalar/func/impls/time.rs
  src/expr/src/scalar/func/impls/timestamp.rs
  src/expr/src/scalar/mod.rs
  src/repr/src/strconv.rs
Labels: C-feature, A-COMPUTE

#11975 doc/user: dev/stage/prod segment tag
  doc/user/layouts/partials/head.html
Labels: A-docs

#11976 doc/user: Add unstable warning to header.
  doc/user/layouts/partials/header.html
Labels: A-docs

#12018 doc/user: update "Tools and Integrations"
  doc/user/assets/sass/_content.scss
  doc/user/content/integrations/_index.md
  doc/user/layouts/partials/inline-svgs.html
Labels: A-docs

#11922 expr: deprecate `_nolimit` visitor methods
  src/coord/src/coord/dataflow_builder.rs
  src/expr/src/linear.rs
  src/expr/src/relation/canonicalize.rs
  src/expr/src/relation/join_input_mapper.rs
  src/expr/src/relation/mod.rs
  src/expr/src/scalar/mod.rs
  src/expr/src/visit.rs
  src/transform/src/column_knowledge.rs
  src/transform/src/dataflow.rs
  src/transform/src/fusion/join.rs
  src/transform/src/fusion/reduce.rs
  src/transform/src/join_implementation.rs
  src/transform/src/map_lifting.rs
  src/transform/src/nonnullable.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/projection_pushdown.rs
  src/transform/src/reduction_pushdown.rs
  src/transform/src/redundant_join.rs
Labels: C-refactoring, A-optimization

#12048 doc/user: temporarily rename SQL Spellbook section
  doc/user/config.toml
  doc/user/content/_index.md
  doc/user/content/cloud/get-started-with-cloud.md
  doc/user/content/get-started.md
  doc/user/content/known-limitations.md
  doc/user/content/sql/create-source/kafka.md
  doc/user/content/sql/functions/now_and_mz_logical_timestamp.md
  doc/user/content/sql/join.md
  doc/user/content/sql/patterns/manual-materialization.md
  doc/user/content/sql/patterns/temporal-filters.md
  doc/user/content/sql/patterns/top-k.md
  doc/user/content/sql/patterns/window-functions.md
  doc/user/data/sql_funcs.yml
Labels: A-docs

#12067 dbt-materialize: release `v1.0.5`
  misc/dbt-materialize/CHANGELOG.md
  misc/dbt-materialize/dbt/adapters/materialize/__version__.py
  misc/dbt-materialize/setup.py
Labels: T-dbt

#12110 doc/user: Fix connection params typo
  doc/user/content/sql/create-source/postgres.md
Labels: A-docs

#12119 doc/user: alias CREATE SOURCE into SQL Commands
  doc/user/config.toml
Labels: A-docs

#12136 doc/user: remove stale dbt installation instructions from guide
  doc/user/content/integrations/dbt.md
Labels: A-docs

#12137 doc/user: remove stale dbt installation instructions from guide (#12136)
  doc/user/content/integrations/dbt.md
Labels: A-docs
