Repository MaterializeInc/materialize, pull requests merged in 2023-04, with the labels that each got.

#18510 sql: improve WMR error message on type mismatch
  src/sql/src/plan/error.rs
  src/sql/src/plan/query.rs
  test/sqllogictest/with_mutually_recursive.slt
Labels: A-ADAPTER

#18585 ci: Run cargo check on merge with target branch
  ci/test/check-merge-with-target.sh
  ci/test/pipeline.template.yml
Labels: T-testing

#18582 Fix a cast inversion bug in `LiteralConstraints`
  src/expr/src/scalar/mod.rs
  test/sqllogictest/literal_constraints.slt
Labels: A-optimization, A-COMPUTE

#18604 ci: Avoid starting agent for merge check when not in PR
  ci/test/check-merge-with-target.sh
  ci/test/pipeline.template.yml
Labels: T-testing

#18605 docs: Fix cloudtest setup for Mac users
  doc/developer/cloudtest.md
Labels: T-docs-update

#18633 ci: Run "Merge skew cargo check" with target dependencies
  ci/test/check-merge-with-target.sh
  ci/test/pipeline.template.yml
Labels: T-testing

#18532 Rework `projection_~` transforms to make them `recursion_safe`
  src/transform/src/dataflow.rs
  src/transform/src/lib.rs
  src/transform/src/literal_constraints.rs
  src/transform/src/movement/mod.rs
  src/transform/src/movement/projection_lifting.rs
  src/transform/src/movement/projection_pushdown.rs
  src/transform/tests/test_runner.rs
  test/sqllogictest/transform/projection_lifting.slt
Labels: A-optimization, A-COMPUTE

#18554 Mark ReductionPushdown and ReduceElision WMR-safe
  src/transform/src/reduce_elision.rs
  src/transform/src/reduction_pushdown.rs
  src/transform/tests/testdata/partial-reduction-pushdown
  test/sqllogictest/transform/reduce_elision.slt
  test/sqllogictest/transform/reduction_pushdown.slt
Labels: A-optimization, A-COMPUTE

#18618 docs: add note about cluster AZ assignment
  doc/developer/design/20220214_create_cluster.md
  doc/user/content/sql/create-cluster-replica.md
  doc/user/content/sql/create-cluster.md
Labels: A-docs, T-docs-education

#18606 #18121 use EXPECTED GROUP SIZE hint in basic top-K rendering
  doc/user/content/sql/select.md
  src/compute-client/src/plan/mod.rs
  src/compute-client/src/plan/reduce.rs
  src/compute-client/src/plan/top_k.proto
  src/compute-client/src/plan/top_k.rs
  src/compute/src/render/top_k.rs
  src/expr/src/explain/text.rs
  src/expr/src/relation/mod.rs
  src/sql/src/plan/explain/text.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/query.rs
  src/transform/src/canonicalization/topk_elision.rs
  src/transform/src/fusion/top_k.rs
  src/transform/src/literal_lifting.rs
  src/transform/src/movement/projection_lifting.rs
  src/transform/src/predicate_pushdown.rs
  test/sqllogictest/explain/decorrelated_plan_as_json.slt
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/raw_plan_as_json.slt
  test/sqllogictest/topk.slt
Labels: T-proto

#18728 docs: Update scratch lifetime
  doc/developer/scratch.md
Labels: T-docs-update

#18713 transform: refine `DatumKnowledge::meet_assign` type handing
  src/transform/src/column_knowledge.rs
  test/sqllogictest/github-18708.slt
Labels: A-optimization, A-COMPUTE

#18731 Rework `redundant_join` so it is `recursion_safe`
  src/transform/src/redundant_join.rs
  test/sqllogictest/transform/redundant_join.slt
Labels: A-optimization, A-COMPUTE

#18831 ci: Add further range tests
  test/sqllogictest/range.slt
Labels: T-testing

#18812 ci: Test output consistency between constant-folding vs. rendered query evaluations
  test/sqllogictest/transform/fold_vs_dataflow/1_numbers_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/1_numbers_folding.slt
  test/sqllogictest/transform/fold_vs_dataflow/2_number_fns_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/2_number_fns_folding.slt
  test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_folding.slt
  test/sqllogictest/transform/fold_vs_dataflow/4_text_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/4_text_folding.slt
  test/sqllogictest/transform/fold_vs_dataflow/5_repeat_row_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/5_repeat_row_folding.slt
  test/sqllogictest/transform/fold_vs_dataflow/6_bytea_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/6_bytea_folding.slt
Labels: T-testing

#18853 [sinks] Fail open when we can't fetch Kafka config
  src/storage-client/src/sink.rs
  test/kafka-sasl-plain/mzcompose.py
  test/kafka-sasl-plain/no-describe-configs.properties
  test/kafka-sasl-plain/no-describe-configs.td
  test/kafka-sasl-plain/sasl.jaas.config
  test/test-certs/create-certs.sh
Labels: release-blocker

#18846 adapter: Add resource limit for compute credits
  doc/user/content/sql/show.md
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/builtin.rs
  src/adapter/src/catalog/builtin_table_updates.rs
  src/adapter/src/catalog/config.rs
  src/adapter/src/coord/ddl.rs
  src/adapter/src/error.rs
  src/controller/src/clusters.rs
  src/sql/src/session/vars.rs
  test/cloudtest/test_privatelink_connection.py
  test/cluster/resources/resource-limits.td
  test/sqllogictest/cluster.slt
  test/sqllogictest/system-cluster.slt
  test/sqllogictest/vars.slt
  test/testdrive/connection-create-drop.td
  test/testdrive/session.td
Labels: release-blocker

#18866 testdrive: fix error message
  src/testdrive/src/action/kafka/add_partitions.rs
Labels: T-testing

#18875 ci: add multiple_partitions platform check
  misc/python/materialize/checks/all_checks.py
  misc/python/materialize/checks/multiple_partitions.py
  src/testdrive/src/action/kafka/add_partitions.rs
Labels: T-testing

#18893 `NormalizeLets` -- inlining at inner nesting levels
  src/transform/src/normalize_lets.rs
  test/sqllogictest/transform/normalize_lets.slt
Labels: A-optimization, A-COMPUTE

#18952 Fix `LetRec` lowering when inserting an `ArrangeBy`
  src/compute-client/src/plan/mod.rs
  test/sqllogictest/with_mutually_recursive.slt
Labels: A-optimization, A-COMPUTE

#19015 storage: dont use http proxies for csr-over-ssh
  src/ccsr/src/client.rs
  src/ccsr/src/config.rs
  src/storage-client/src/types/connections.rs
  test/ssh-connection/mzcompose.py
Labels: release-blocker
