Repository MaterializeInc/materialize, pull requests merged in 2023-01, with the labels that each got.

#16903 UpdateConfiguration compute command
  src/compute-client/src/command.proto
  src/compute-client/src/command.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/controller/replica.rs
  src/compute/src/compute_state.rs
  src/compute/src/server.rs
Labels: T-proto

#16953 Fix a lint issue for links in doc comments
  src/expr/src/scalar/mod.rs
Labels: A-optimization, A-COMPUTE

#16959 dbt-materialize: release v1.3.3
  misc/dbt-materialize/CHANGELOG.md
  misc/dbt-materialize/README.md
  misc/dbt-materialize/dbt/adapters/materialize/__version__.py
  misc/dbt-materialize/setup.py
Labels: T-dbt

#16908 IDLE ARRANGEMENT MERGE EFFORT option
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/storage.rs
  src/adapter/src/coord/sequencer.rs
  src/compute-client/src/command.proto
  src/compute-client/src/command.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/controller/orchestrator.rs
  src/compute-client/src/controller/replica.rs
  src/compute-client/src/service.rs
  src/compute/src/communication.rs
  src/compute/src/server.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/keywords.txt
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
  src/sql/src/plan.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/with_options.rs
  test/testdrive/idle_arrangement_merge_effort.td
Labels: T-proto

#17050 stash: add logging for unexpected lower
  src/stash/src/postgres.rs
Labels: release-blocker

#17070 adapter: use `environment` context for LaunchDarkly sync
  src/adapter/src/config/frontend.rs
  test/launchdarkly/mzcompose.py
Labels: A-ADAPTER

#17062 adapter: drop linked cluster if sink fails to create
  src/adapter/src/coord/message_handler.rs
  test/testdrive/kafka-sink-errors.td
Labels: release-blocker

#17093 ore: add a tracing layer for LaunchDarkly monitoring
  Cargo.lock
  src/adapter/src/config/frontend.rs
  src/environmentd/src/lib.rs
Labels: A-ADAPTER

#17006 Support using AZ-specific services when consuming a privatelink connection in kafka
  src/cloud-resources/src/lib.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql/src/plan/statement.rs
  src/sql/src/plan/statement/ddl.rs
  src/storage-client/src/types/connections.proto
  src/storage-client/src/types/connections.rs
  test/cloudtest/test_privatelink_connection.py
Labels: T-proto

#17121 Split literal constraints detection from `CanonicalizeMfp`.
  src/transform/src/canonicalize_mfp.rs
  src/transform/src/lib.rs
  src/transform/src/literal_constraints.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
  test/sqllogictest/literal_constraints.slt
  test/sqllogictest/not-null-propagation.slt
Labels: A-optimization, A-COMPUTE

#17119 adapter: remove `window_functions` feature flag
  src/adapter/src/catalog.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/session/vars.rs
  src/sql/src/catalog.rs
  src/sql/src/plan/optimize.rs
  src/sql/src/query_model/test/catalog.rs
  test/testdrive/session.td
Labels: A-optimization, A-COMPUTE

#17188 sql: remove unused `typemap_rev` dependency
  Cargo.lock
  src/sql/Cargo.toml
Labels: A-ADAPTER

#17231 Docs: SSH tunnel guide -- restrict firewall to mz ips
  doc/user/content/ops/network-security/ssh-tunnel.md
Labels: A-docs

#17269 Migration to remove legacy orchestrator services
  src/environmentd/src/lib.rs
Labels: release-blocker

#17285 adapter: disallow queries on storage clusters
  src/adapter/src/catalog.rs
  test/testdrive/linked-clusters.td
  test/testdrive/storage-clusters.td
Labels: release-blocker

#17286 controller: set storage workers appropriately
  src/controller/src/clusters.rs
Labels: release-blocker

#17305 storage-client: fix emission of "dropped" source/sink status
  src/storage-client/src/controller.rs
  test/testdrive/status-history.td
Labels: release-blocker

#17316 adapter: align `EXPLAIN AS TEXT` for `With` clauses in HIR/MIR/LIR
  src/adapter/src/explain_new/hir/text.rs
  src/adapter/src/explain_new/lir/text.rs
  test/sqllogictest/cte_lowering.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
  test/sqllogictest/github-9027.slt
  test/sqllogictest/literal_constraints.slt
  test/sqllogictest/scalar_subqueries_select_list.slt
  test/sqllogictest/tpch.slt
  test/sqllogictest/window_funcs.slt
Labels: A-COMPUTE

#17235 doc/user: add documentation for mz_internal.mz_postgres_sources
  doc/user/content/integrations/cdc-postgres.md
  doc/user/content/sql/create-source/postgres.md
  doc/user/content/sql/system-catalog/mz_internal.md
Labels: A-docs

#17277 test: add `allowed_cluster_replica_sizes` nightly test
  test/launchdarkly/mzcompose.py
  test/restart/mzcompose.py
Labels: T-testing, A-ADAPTER

#17371 Remove some leftover QGM tests
  src/sql/tests/querymodel/basic
  src/sql/tests/querymodel/dotformat
  src/sql/tests/querymodel/hirroundtrip
  src/sql/tests/querymodel/lowering
  src/sql/tests/querymodel/rewrite/simplify_outer_joins
Labels: A-optimization, A-COMPUTE

#17348 explain: replace column runs with ranges in `~ScalarExpr` sequences
  src/adapter/src/coord/peek.rs
  src/adapter/src/explain_new/hir/mod.rs
  src/adapter/src/explain_new/hir/text.rs
  src/adapter/src/explain_new/lir/text.rs
  src/adapter/src/explain_new/mir/mod.rs
  src/adapter/src/explain_new/mir/text.rs
  src/adapter/src/explain_new/mod.rs
  test/sqllogictest/attributes/mir_arity.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/explain/decorrelated_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
  test/sqllogictest/tpch.slt
  test/sqllogictest/transform/reduce_fusion.slt
  test/sqllogictest/transform/threshold_elision.slt
Labels: A-optimization

#17374 explain: deprecate and remove the old `explain` code
  src/adapter/src/coord/peek.rs
  src/adapter/src/explain_new/hir/text.rs
  src/adapter/src/explain_new/lir/text.rs
  src/adapter/src/explain_new/mir/text.rs
  src/adapter/src/explain_new/mod.rs
  src/compute-client/src/explain.rs
  src/compute-client/src/lib.rs
  src/expr-test-util/src/lib.rs
  src/expr/src/explain.rs
  src/expr/src/relation/mod.rs
  src/repr/src/explain_new/mod.rs
  src/sql/src/plan.rs
  src/sql/src/plan/explain.rs
  src/sql/src/plan/expr.rs
Labels: A-optimization, A-COMPUTE

#17372 Clarify JSON Parsing
  doc/user/content/sql/create-source/_index.md
  doc/user/content/sql/create-source/kafka.md
  doc/user/content/sql/patterns/single-parsing.md
Labels: A-docs
