Repository MaterializeInc/materialize, pull requests merged in 2023-03, with the labels that each got.

#16475 Remove `skip(1)` from `differential::plan`
  src/compute-client/src/plan/mod.rs
  src/expr/src/explain/text.rs
  src/expr/src/relation/mod.rs
  src/transform/src/join_implementation.rs
  src/transform/tests/testdata/join-implementation
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/reduction-pushdown
  src/transform/tests/testdata/steps
  test/sqllogictest/autogenerated/all_parts_essential.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/column_knowledge.slt
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/funcs.slt
  test/sqllogictest/github-14116.slt
  test/sqllogictest/github-16036.slt
  test/sqllogictest/github-9027.slt
  test/sqllogictest/github-9147.slt
  test/sqllogictest/github-9782.slt
  test/sqllogictest/joins.slt
  test/sqllogictest/literal_constraints.slt
  test/sqllogictest/not-null-propagation.slt
  test/sqllogictest/relation-cse.slt
  test/sqllogictest/scalar_subqueries_select_list.slt
  test/sqllogictest/subquery.slt
  test/sqllogictest/table_func.slt
  test/sqllogictest/tpch.slt
  test/sqllogictest/transform/aggregation_nullability.slt
  test/sqllogictest/transform/filter_index.slt
  test/sqllogictest/transform/is_null_propagation.slt
  test/sqllogictest/transform/join_fusion.slt
  test/sqllogictest/transform/join_index.slt
  test/sqllogictest/transform/lifting.slt
  test/sqllogictest/transform/predicate_pushdown.slt
  test/sqllogictest/transform/union.slt
  test/sqllogictest/window_funcs.slt
  test/testdrive/render-delta-join.td
Labels: A-optimization, A-COMPUTE

#17905 Put `JoinImplementation` in the same fixpoint loop with `LiteralLifting`
  src/transform/src/lib.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
  test/sqllogictest/joins.slt
Labels: C-bug, A-optimization, A-COMPUTE

#17907 explain: correctly trace `optimize/local` entry + small timing fixes
  misc/python/materialize/cli/optbench.py
  misc/python/materialize/optbench/README.md
  misc/python/materialize/optbench/sql.py
  misc/python/materialize/optbench/util.py
  src/adapter/src/coord/sequencer.rs
  src/repr/src/explain/tracing.rs
  src/transform/src/dataflow.rs
Labels: A-optimization, A-COMPUTE

#18003 storage: bring reclock optimization back
  src/storage/src/source/source_reader_pipeline.rs
Labels: release-blocker

#18054 Fix join plan invalidations by later transforms
  src/expr/src/relation/canonicalize.rs
  src/transform/src/canonicalize_mfp.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
  test/sqllogictest/attributes/mir_arity.slt
  test/sqllogictest/autogenerated/all_parts_essential.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/github-16036.slt
  test/sqllogictest/literal_constraints.slt
  test/sqllogictest/relation-cse.slt
  test/sqllogictest/tpch.slt
  test/sqllogictest/transform/join_index.slt
Labels: C-bug, A-optimization, A-COMPUTE

#18314 Make `PredicatePushdown` WMR-safe
  src/expr/src/relation/mod.rs
  src/transform/src/predicate_pushdown.rs
  test/sqllogictest/transform/predicate_pushdown.slt
Labels: A-optimization, A-COMPUTE

#18331 Mark `UnionBranchCancellation` WMR-safe
  src/transform/src/union_cancel.rs
  test/sqllogictest/transform/union_cancel.slt
  test/sqllogictest/with_mutually_recursive.slt
Labels: A-optimization, A-COMPUTE

#18371 storage: increase reliability of ssh connections
  Cargo.lock
  src/postgres-util/Cargo.toml
  src/ssh-util/Cargo.toml
  src/ssh-util/src/tunnel.rs
  src/storage-client/src/types/connections.rs
Labels: release-blocker

#18382 Rework `fold_constants` so it is `recursion_safe`
  src/transform/src/fold_constants.rs
  src/transform/src/fusion/mod.rs
  src/transform/src/lib.rs
  src/transform/src/normalize_lets.rs
  src/transform/src/normalize_ops.rs
  test/sqllogictest/transform/fold_constants.slt
  test/sqllogictest/transform/union_cancel.slt
  test/sqllogictest/with_mutually_recursive.slt
Labels: A-optimization, A-COMPUTE
