Repository MaterializeInc/materialize, pull requests merged in 2023-05, with the labels that each got.

#19010 Rework `non_null_requirements` so it is `recursion_safe`
  doc/developer/design/20230223_stabilize_with_mutually_recursive.md
  src/transform/src/lib.rs
  src/transform/src/non_null_requirements.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/testdata/non_null_requirements
  test/sqllogictest/transform/non_null_requirements.slt
Labels: A-optimization, A-COMPUTE

#19199 Explicit error msg for WMR with `linear_chains`
  src/expr/src/explain/mod.rs
  src/expr/src/explain/text.rs
  src/repr/src/explain/mod.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
Labels: A-optimization, A-COMPUTE

#19191 ci: protobuf linting (1/2): add buf config
  src/buf.yaml
Labels: T-testing

#19195 adapter: check peek validity instead of replanning
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
Labels: A-ADAPTER

#19157 ci: protobuf linting (2/2): ci step to detect breaking changes
  ci/builder/Dockerfile
  ci/test/check-merge-with-target.sh
  ci/test/lint-fast.sh
  misc/buildkite/git.bash
Labels: T-testing

#18538 WMR limits design doc
  doc/developer/design/20230330_recursion_limit.md
Labels: A-COMPUTE

#19224 Fix join visitation
  src/expr/src/relation/mod.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
Labels: A-optimization, A-COMPUTE

#19201 adapter: export `last_sse_time` from LD as a Prometheus metric
  Cargo.lock
  src/adapter/src/config/frontend.rs
  src/environmentd/src/lib.rs
Labels: release-blocker, A-ADAPTER

#19257 Correcting the logic for diff_record
  src/storage/src/render/upsert.rs
Labels: release-blocker

#19280 docs: Fix atan function entry
  doc/user/data/sql_funcs.yml
Labels: T-docs-update

#19285 Fix locality of join key references in the typechecker
  src/transform/src/typecheck.rs
  test/sqllogictest/github-19273.slt
Labels: A-optimization, A-COMPUTE

#19288 Don't push literal errors past Negate
  src/transform/src/predicate_pushdown.rs
  src/transform/src/typecheck.rs
  test/sqllogictest/transform/predicate_pushdown.slt
Labels: A-optimization, A-COMPUTE

#19312 ci: protobuf linting: rework excludes, add comment
  ci/test/lint-fast.sh
  misc/buildkite/git.bash
  src/buf.yaml
Labels: T-testing

#19013 Test generator for output consistency checks (V1)
  bin/lint
  bin/output-consistency-test
  ci/nightly/pipeline.yml
  misc/python/materialize/mzcompose/__init__.py
  misc/python/materialize/output_consistency/common/configuration.py
  misc/python/materialize/output_consistency/data_type/data_type.py
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/data_type/data_type_with_values.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/execution/evaluation_strategy.py
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/execution/sql_executor.py
  misc/python/materialize/output_consistency/execution/test_summary.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/boolean_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/trigonometric_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/any_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/boolean_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/number_operation_param.py
  misc/python/materialize/output_consistency/input_data/test_input_data.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/boolean_type_provider.py
  misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
  misc/python/materialize/output_consistency/input_data/validators/generic_args_validator.py
  misc/python/materialize/output_consistency/input_data/validators/number_args_validator.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/boolean_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/number_values_provider.py
  misc/python/materialize/output_consistency/known_inconsistencies/known_deviation_filter.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/operation/operation_args_validator.py
  misc/python/materialize/output_consistency/operation/operation_param.py
  misc/python/materialize/output_consistency/output/format_constants.py
  misc/python/materialize/output_consistency/output/output_printer.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/overview.png
  misc/python/materialize/output_consistency/overview.uxf
  misc/python/materialize/output_consistency/query/query_format.py
  misc/python/materialize/output_consistency/query/query_result.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/selection/randomized_picker.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_message.py
  misc/python/materialize/output_consistency/validation/validation_outcome.py
  test/output-consistency/README.md
  test/output-consistency/mzcompose
  test/output-consistency/mzcompose.py
Labels: T-testing

#19186 compute: better-fueled linear join
  src/adapter/src/catalog.rs
  src/compute-client/src/protocol/command.proto
  src/compute-client/src/protocol/command.rs
  src/compute/src/compute_state.rs
  src/compute/src/render/context.rs
  src/compute/src/render/join/linear_join.rs
  src/compute/src/render/join/mod.rs
  src/compute/src/render/join/mz_join_core.rs
  src/compute/src/render/mod.rs
  src/compute/src/server.rs
  src/sql/src/session/vars.rs
  test/sqllogictest/joins.slt
  test/testdrive/linear-join-fuel.td
Labels: T-proto

#19461 Collapse `from_mir` and `from_mir_inner`
  src/compute-client/src/plan/mod.rs
Labels: A-COMPUTE

#19481 ci: Change Protobuf linting config from FILE to WIRE
  src/buf.yaml
Labels: T-testing

#19488 Update CTE docs on known limitations
  doc/user/content/sql/select.md
Labels: A-docs, T-docs-update

#19494 Deduplicate keys in `keys_with_input_keys`
  src/expr/src/relation/mod.rs
  src/transform/tests/testdata/lifting
Labels: A-optimization, A-COMPUTE

#19502 adapter: remove obsolete `last_known_time_seconds` metric
  src/adapter/src/config/frontend.rs
Labels: A-ADAPTER

#19441 transform: rework `MonotonicFlag` inference to make it `recursion_safe`
  doc/developer/design/20230223_stabilize_with_mutually_recursive.md
  doc/user/content/sql/explain.md
  src/compute-client/src/explain/text.rs
  src/expr-test-util/tests/testdata/rel
  src/expr/src/explain/text.rs
  src/transform/src/monotonic.rs
  src/transform/tests/testdata/predicate-pushdown
  src/transform/tests/testdata/projection-pushdown
  src/transform/tests/testdata/topk_fusion
  test/sqllogictest/attributes/mir_arity.slt
  test/sqllogictest/attributes/mir_column_types.slt
  test/sqllogictest/attributes/mir_unique_keys.slt
  test/sqllogictest/distinct_on.slt
  test/sqllogictest/explain/decorrelated_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/list.slt
  test/sqllogictest/topk.slt
  test/sqllogictest/transform/column_knowledge.slt
  test/sqllogictest/transform/fold_constants.slt
  test/sqllogictest/transform/monotonic.slt
  test/sqllogictest/transform/non_null_requirements.slt
  test/sqllogictest/transform/normalize_lets.slt
  test/sqllogictest/transform/predicate_pushdown.slt
  test/sqllogictest/transform/relation_cse.slt
  test/sqllogictest/transform/threshold_elision.slt
  test/sqllogictest/transform/topk.slt
  test/testdrive/char-varchar-orderby.td
  test/testdrive/monotonic.td
  test/testdrive/primary-key-optimizations.td
  test/testdrive/source-linear-operators.td
Labels: A-optimization, A-COMPUTE

#19443 Test generator for output consistency checks (V2): aggregates
  misc/python/materialize/output_consistency/common/configuration.py
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/data_type/data_type_with_values.py
  misc/python/materialize/output_consistency/data_value/data_column.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/execution/evaluation_strategy.py
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/execution/value_storage_layout.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/expression/leaf_expression.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/test_input_data.py
  misc/python/materialize/output_consistency/input_data/validators/number_args_validator.py
  misc/python/materialize/output_consistency/input_data/values/boolean_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/number_values_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/operation/operation_args_validator.py
  misc/python/materialize/output_consistency/operation/operation_param.py
  misc/python/materialize/output_consistency/output/base_output_printer.py
  misc/python/materialize/output_consistency/output/format_constants.py
  misc/python/materialize/output_consistency/output/output_printer.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/overview.png
  misc/python/materialize/output_consistency/overview.uxf
  misc/python/materialize/output_consistency/query/query_result.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/selection/randomized_picker.py
  misc/python/materialize/output_consistency/selection/selection.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_message.py
  test/output-consistency/README.md
Labels: T-testing

#19585 Add erroring limit for WMR and change limit syntax
  doc/developer/design/20230223_stabilize_with_mutually_recursive.md
  doc/developer/design/20230330_recursion_limit.md
  doc/user/content/sql/select.md
  src/compute-client/src/explain/text.rs
  src/compute-client/src/plan.proto
  src/compute-client/src/plan/mod.rs
  src/compute/src/render/mod.rs
  src/expr/src/explain/text.rs
  src/expr/src/lib.rs
  src/expr/src/relation/mod.rs
  src/expr/src/scalar.proto
  src/expr/src/scalar/mod.rs
  src/sql-parser/src/ast/defs/query.rs
  src/sql-parser/src/keywords.txt
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/select
  src/sql/src/plan/error.rs
  src/sql/src/plan/explain/text.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/query.rs
  src/transform/src/column_knowledge.rs
  src/transform/src/cse/anf.rs
  src/transform/src/demand.rs
  src/transform/src/literal_lifting.rs
  src/transform/src/monotonic.rs
  src/transform/src/movement/projection_lifting.rs
  src/transform/src/movement/projection_pushdown.rs
  src/transform/src/non_null_requirements.rs
  src/transform/src/normalize_lets.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/redundant_join.rs
  src/transform/src/semijoin_idempotence.rs
  src/transform/src/typecheck.rs
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
  test/sqllogictest/transform/column_knowledge.slt
  test/sqllogictest/transform/literal_constraints.slt
  test/sqllogictest/transform/normalize_lets.slt
  test/sqllogictest/with_mutually_recursive.slt
Labels: A-optimization, A-COMPUTE

#19600 Output consistency tests V2: error messages from non-aggregate functions on multiple rows may differ
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/expression/leaf_expression.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing
