Repository MaterializeInc/materialize, pull requests merged in 2023-08, with the labels that each got.

#20918 secrets: pass through aws secrets reader configuration to clusterd
  Cargo.lock
  src/aws-secrets-controller/Cargo.toml
  src/aws-secrets-controller/src/lib.rs
  src/clusterd/ci/entrypoint.sh
  src/controller/Cargo.toml
  src/controller/src/clusters.rs
  src/controller/src/lib.rs
  src/environmentd/src/bin/environmentd/main.rs
  src/environmentd/tests/util.rs
  src/orchestrator-kubernetes/src/lib.rs
  src/orchestrator-process/src/lib.rs
  src/service/Cargo.toml
  src/service/src/secrets.rs
  src/sqllogictest/Cargo.toml
  src/sqllogictest/src/runner.rs
Labels: release-blocker

#20940 tests: note about cloudtest performance hint on macOS
  doc/developer/cloudtest.md
Labels: T-testing

#20920 Deprecate some old join code with a `soft_panic_or_log`
  src/adapter/src/coord/peek.rs
  src/compute-client/src/plan/mod.rs
  src/expr/src/explain/text.rs
  src/transform/src/literal_constraints.rs
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/transform/join_fusion.slt
  test/sqllogictest/transform/literal_constraints.slt
Labels: A-optimization, A-COMPUTE

#20882 LEFT JOIN consolidation design doc
  doc/developer/design/00000000_template_compute.md
  doc/developer/design/20230728_left_join_stack_consolidation.md
Labels: A-optimization, A-COMPUTE

#20994 adapter: fix `auto_run_on_introspection` for `EXPLAIN` plans
  src/adapter/src/coord/introspection.rs
  src/environmentd/tests/testdata/http/post
  src/expr/src/relation/mod.rs
  src/sql/src/plan/expr.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/transform/predicate_pushdown.slt
  test/testdrive/linked-clusters.td
Labels: A-ADAPTER

#20924 clusters: populate `disk_usage` from kubernetes
  src/adapter/src/catalog/builtin_table_updates.rs
  src/compute-client/src/controller.rs
  src/orchestrator-kubernetes/src/lib.rs
  src/orchestrator-process/src/lib.rs
  src/orchestrator/src/lib.rs
Labels: release-blocker

#20995 Consolidate after a Union that has a Negated input
  doc/developer/design/20230728_left_join_stack_consolidation.md
  src/adapter/src/coord/dataflows.rs
  src/compute-client/src/explain/text.rs
  src/compute-client/src/plan.proto
  src/compute-client/src/plan/interpret/api.rs
  src/compute-client/src/plan/interpret/physically_monotonic.rs
  src/compute-client/src/plan/mod.rs
  src/compute/src/render/mod.rs
  src/sql/src/session/vars.rs
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/outer_join.slt
  test/sqllogictest/transform/literal_constraints.slt
  test/sqllogictest/transform/relax_must_consolidate.slt
  test/testdrive/session.td
Labels: A-COMPUTE

#20991 Window functions vs. `CASE WHEN`
  src/sql/src/plan/query.rs
  test/sqllogictest/order_by.slt
  test/sqllogictest/window_funcs.slt
Labels: A-ADAPTER

#21010 cloudtests: allow configuring testdrive
  misc/python/materialize/cloudtest/k8s/testdrive.py
Labels: T-testing

#21040 cloudtests: allow specifying the namespace for testdrive
  misc/python/materialize/cloudtest/k8s/__init__.py
  misc/python/materialize/cloudtest/k8s/testdrive.py
Labels: T-testing

#21062 cloudtests: restructure k8s code
  doc/developer/cloudtest.md
  misc/python/materialize/cloudtest/__init__.py
  misc/python/materialize/cloudtest/app/application.py
  misc/python/materialize/cloudtest/app/materialize_application.py
  misc/python/materialize/cloudtest/k8s/__init__.py
  misc/python/materialize/cloudtest/k8s/api/k8s_cluster_role.py
  misc/python/materialize/cloudtest/k8s/api/k8s_config_map.py
  misc/python/materialize/cloudtest/k8s/api/k8s_deployment.py
  misc/python/materialize/cloudtest/k8s/api/k8s_pod.py
  misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
  misc/python/materialize/cloudtest/k8s/api/k8s_role_binding.py
  misc/python/materialize/cloudtest/k8s/api/k8s_secret.py
  misc/python/materialize/cloudtest/k8s/api/k8s_service.py
  misc/python/materialize/cloudtest/k8s/api/k8s_stateful_set.py
  misc/python/materialize/cloudtest/k8s/cockroach.py
  misc/python/materialize/cloudtest/k8s/debezium.py
  misc/python/materialize/cloudtest/k8s/environmentd.py
  misc/python/materialize/cloudtest/k8s/minio.py
  misc/python/materialize/cloudtest/k8s/persist_pubsub.py
  misc/python/materialize/cloudtest/k8s/postgres.py
  misc/python/materialize/cloudtest/k8s/redpanda.py
  misc/python/materialize/cloudtest/k8s/role_binding.py
  misc/python/materialize/cloudtest/k8s/ssh.py
  misc/python/materialize/cloudtest/k8s/testdrive.py
  misc/python/materialize/cloudtest/k8s/vpc_endpoints_cluster_role.py
  misc/python/materialize/cloudtest/util/cluster.py
  misc/python/materialize/cloudtest/util/exists.py
  misc/python/materialize/cloudtest/util/wait.py
  misc/python/materialize/setup.py
  test/cloudtest/test_antiaffinity.py
  test/cloudtest/test_compute.py
  test/cloudtest/test_compute_shared_fate.py
  test/cloudtest/test_crash.py
  test/cloudtest/test_disk.py
  test/cloudtest/test_managed_cluster.py
  test/cloudtest/test_privatelink_connection.py
  test/cloudtest/test_secrets.py
  test/cloudtest/test_smoke.py
  test/cloudtest/test_ssh_tunnels.py
  test/cloudtest/test_storage.py
  test/cloudtest/test_storage_shared_fate.py
  test/cloudtest/test_upgrade.py
Labels: T-testing

#21075 ci: increase cluster test timeout to 30 minutes
  ci/test/pipeline.template.yml
Labels: T-testing

#21068 slt: do not reformat in sorted cockroach mode
  src/sqllogictest/src/runner.rs
Labels: T-testing

#21083 testdrive: log when connecting to mz
  src/testdrive/src/action.rs
Labels: T-testing

#21064 cloudtests: further namespace refactorings
  misc/python/materialize/cloudtest/app/application.py
  misc/python/materialize/cloudtest/k8s/api/k8s_cluster_role.py
  misc/python/materialize/cloudtest/k8s/api/k8s_config_map.py
  misc/python/materialize/cloudtest/k8s/api/k8s_deployment.py
  misc/python/materialize/cloudtest/k8s/api/k8s_pod.py
  misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
  misc/python/materialize/cloudtest/k8s/api/k8s_role_binding.py
  misc/python/materialize/cloudtest/k8s/api/k8s_secret.py
  misc/python/materialize/cloudtest/k8s/api/k8s_service.py
  misc/python/materialize/cloudtest/k8s/api/k8s_stateful_set.py
  misc/python/materialize/cloudtest/k8s/cockroach.py
  misc/python/materialize/cloudtest/k8s/debezium.py
  misc/python/materialize/cloudtest/k8s/environmentd.py
  misc/python/materialize/cloudtest/k8s/minio.py
  misc/python/materialize/cloudtest/k8s/persist_pubsub.py
  misc/python/materialize/cloudtest/k8s/postgres.py
  misc/python/materialize/cloudtest/k8s/redpanda.py
  misc/python/materialize/cloudtest/k8s/role_binding.py
  misc/python/materialize/cloudtest/k8s/ssh.py
  misc/python/materialize/cloudtest/k8s/testdrive.py
  misc/python/materialize/cloudtest/k8s/vpc_endpoints_cluster_role.py
Labels: T-testing

#21000 Unbatch compute commands
  src/adapter/src/coord.rs
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/coord/ddl.rs
  src/adapter/src/coord/peek.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/metrics.rs
  src/compute-client/src/protocol.rs
  src/compute-client/src/protocol/command.proto
  src/compute-client/src/protocol/command.rs
  src/compute-client/src/protocol/history.rs
  src/compute-client/src/protocol/response.proto
  src/compute-client/src/protocol/response.rs
  src/compute-client/src/service.rs
  src/compute/src/compute_state.rs
  src/compute/src/server.rs
  test/cluster/mzcompose.py
Labels: T-proto

#21098 persist: fix "force keep" stats trimming bug
  ci/test/pipeline.template.yml
  misc/python/materialize/mzcompose/__init__.py
  src/persist-client/src/batch.rs
  src/persist-types/src/stats.rs
  test/persistence/mzcompose.py
Labels: release-blocker

#21136 tests: install utilities in testdrive image
  src/testdrive/ci/Dockerfile
Labels: T-testing

#21133 cloudtests: testdrive: allow configuring default URLs
  misc/python/materialize/cloudtest/k8s/testdrive.py
Labels: T-testing

#21005 [optimizer] Avoid cardinality estimation panic in debug builds
  src/transform/src/attribute/cardinality.rs
  test/sqllogictest/cardinality.slt
Labels: C-bug, A-optimization, A-COMPUTE

#21119 Explain index usage
  misc/python/materialize/checks/pg_cdc.py
  src/adapter/src/coord/peek.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/compute-client/build.rs
  src/compute-client/src/plan/mod.rs
  src/compute-client/src/types/dataflows.proto
  src/compute-client/src/types/dataflows.rs
  src/compute/src/render/mod.rs
  src/repr/build.rs
  src/repr/src/explain.proto
  src/repr/src/explain/mod.rs
  src/repr/src/explain/text.rs
  src/repr/src/lib.rs
  src/transform/src/dataflow.rs
  src/transform/src/normalize_lets.rs
  test/pg-cdc/constraints.td
  test/sqllogictest/attributes/mir_arity.slt
  test/sqllogictest/attributes/mir_unique_keys.slt
  test/sqllogictest/autogenerated/all_parts_essential.slt
  test/sqllogictest/cardinality.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/github-16036.slt
  test/sqllogictest/list.slt
  test/sqllogictest/system-cluster.slt
  test/sqllogictest/tpch.slt
  test/sqllogictest/transform/dataflow.slt
  test/sqllogictest/transform/join_fusion.slt
  test/sqllogictest/transform/join_index.slt
  test/sqllogictest/transform/literal_constraints.slt
  test/sqllogictest/transform/predicate_pushdown.slt
  test/sqllogictest/transform/redundant_join.slt
  test/sqllogictest/transform/relation_cse.slt
  test/sqllogictest/transform/relax_must_consolidate.slt
  test/sqllogictest/uniqueness_propagation_filter.slt
  test/testdrive/kafka-include-key-sources.td
  test/testdrive/materializations.td
  test/testdrive/monotonic.td
  test/testdrive/primary-key-optimizations.td
  test/testdrive/render-delta-join.td
  test/testdrive/subexpression-replacement.td
Labels: A-optimization, A-COMPUTE, T-proto

#21164 cloudtests: provide more flexibility with respect to namespaces
  misc/python/materialize/cloudtest/app/materialize_application.py
  misc/python/materialize/cloudtest/k8s/api/k8s_config_map.py
  misc/python/materialize/cloudtest/k8s/api/k8s_deployment.py
  misc/python/materialize/cloudtest/k8s/api/k8s_service.py
  misc/python/materialize/cloudtest/k8s/cockroach.py
  misc/python/materialize/cloudtest/k8s/debezium.py
  misc/python/materialize/cloudtest/k8s/environmentd.py
  misc/python/materialize/cloudtest/k8s/minio.py
  misc/python/materialize/cloudtest/k8s/persist_pubsub.py
  misc/python/materialize/cloudtest/k8s/postgres.py
  misc/python/materialize/cloudtest/k8s/redpanda.py
  misc/python/materialize/cloudtest/k8s/role_binding.py
  misc/python/materialize/cloudtest/k8s/ssh.py
  misc/python/materialize/cloudtest/k8s/testdrive.py
  misc/python/materialize/cloudtest/k8s/vpc_endpoints_cluster_role.py
Labels: T-testing

#21174 `NormalizeLets` before `CollectIndexRequests`
  src/transform/src/dataflow.rs
  src/transform/src/lib.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
  test/sqllogictest/transform/normalize_lets.slt
Labels: A-optimization, A-COMPUTE

#21190 tests: fix "running platform checks fails because of docker compose version string"
  misc/python/materialize/cli/mzcompose.py
Labels: T-testing

#21157 storage: shutdown upsert sources correctly
  src/storage/src/render/sources.rs
  src/storage/src/render/upsert.rs
Labels: release-blocker

#21153 cloudtests: add util files from cloud repo
  ci/builder/requirements.txt
  misc/python/materialize/cloudtest/config/environment_config.py
  misc/python/materialize/cloudtest/util/authentication.py
  misc/python/materialize/cloudtest/util/common.py
  misc/python/materialize/cloudtest/util/controller.py
  misc/python/materialize/cloudtest/util/docker_env.py
  misc/python/materialize/cloudtest/util/environment.py
  misc/python/materialize/cloudtest/util/jwt_key.py
  misc/python/materialize/cloudtest/util/kubectl.py
  misc/python/materialize/cloudtest/util/sql.py
  misc/python/materialize/cloudtest/util/web_request.py
  test/lang/python/smoketest.py
Labels: T-testing

#21211 cloudtests: bring further changes to util files
  misc/python/materialize/cloudtest/util/authentication.py
  misc/python/materialize/cloudtest/util/environment.py
Labels: T-testing

#21167 cloudtests: refactor kubectl usage
  misc/python/materialize/cloudtest/util/environment.py
  misc/python/materialize/cloudtest/util/kubectl.py
Labels: T-testing

#21216 cloudtests: environmentd.py: extract methods
  misc/python/materialize/cloudtest/k8s/environmentd.py
Labels: T-testing

#21223 cloudtests: sync changes from cloud repo
  misc/python/materialize/cloudtest/util/environment.py
  misc/python/materialize/cloudtest/util/sql.py
Labels: T-testing

#21228 cloudtests: kubectl: make tests_dir mandatory
  misc/python/materialize/cloudtest/util/kubectl.py
Labels: T-testing

#21177 Fix a minor bug in MFP CSE
  src/expr/src/linear.rs
  src/expr/src/scalar/mod.rs
  test/sqllogictest/list.slt
  test/sqllogictest/transform/scalar_cse.slt
  test/testdrive/subexpression-replacement.td
Labels: A-optimization, A-COMPUTE

#20954 persist: add multi-shard txn abstraction
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  ci/nightly/pipeline.yml
  src/persist-client/Cargo.toml
  src/persist-client/examples/maelstrom.rs
  src/persist-client/examples/maelstrom/node.rs
  src/persist-client/examples/maelstrom/txn_list_append_multi.rs
  src/persist-client/examples/maelstrom/txn_list_append_single.rs
  src/persist-client/examples/persistcli.rs
  src/persist-client/src/batch.rs
  src/persist-client/src/cache.rs
  src/persist-client/src/cfg.rs
  src/persist-client/src/internal/compact.rs
  src/persist-client/src/internal/metrics.rs
  src/persist-client/src/lib.rs
  src/persist-client/src/operators/shard_source.rs
  src/persist-client/src/read.rs
  src/persist-client/src/write.rs
  src/persist-txn/Cargo.toml
  src/persist-txn/src/error.rs
  src/persist-txn/src/lib.rs
  src/persist-txn/src/txn_read.rs
  src/persist-txn/src/txn_write.rs
  src/persist-txn/src/txns.rs
  test/persist/mzcompose.py
Labels: T-platform-v2

#21233 tests: rename ROOT constant to MZ_ROOT
  ci/deploy/deploy_util.py
  ci/deploy/npm.py
  ci/test/cargo-test/mzcompose.py
  misc/monitoring/mzcompose.py
  misc/python/materialize/__init__.py
  misc/python/materialize/benches/avro_ingest.py
  misc/python/materialize/ci_util/trim_pipeline.py
  misc/python/materialize/cli/ci_coverage_pr_report.py
  misc/python/materialize/cli/cloudbench.py
  misc/python/materialize/cli/crate_diagram.py
  misc/python/materialize/cli/lint-cargo.py
  misc/python/materialize/cli/mzcompose.py
  misc/python/materialize/cli/mzimage.py
  misc/python/materialize/cli/run.py
  misc/python/materialize/cli/scratch/create.py
  misc/python/materialize/cloudtest/app/materialize_application.py
  misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
  misc/python/materialize/cloudtest/k8s/cockroach.py
  misc/python/materialize/mzcompose/services.py
  misc/python/materialize/scratch.py
  misc/python/materialize/util.py
  misc/python/materialize/version_list.py
  misc/python/materialize/xcompile.py
  test/sqllogictest/mzcompose.py
Labels: T-testing

#21256 cloudtests: psycopg: update type
  misc/python/materialize/cloudtest/util/sql.py
Labels: T-testing

#21246 cloudtests: extract CloudtestApplicationBase
  misc/python/materialize/cloudtest/app/application.py
  misc/python/materialize/cloudtest/app/cloudtest_application_base.py
  misc/python/materialize/cloudtest/app/materialize_application.py
Labels: T-testing

#20565 benchmark: Run LDBC-BI benchmark
  bin/lint
  doc/developer/design/20230512_mir_cost_model.md
  test/ldbc-bi/.gitignore
  test/ldbc-bi/LICENSE
  test/ldbc-bi/README.md
  test/ldbc-bi/ddl.sql
  test/ldbc-bi/generate-copy.sh
  test/ldbc-bi/init.sql
  test/ldbc-bi/q01.sql
  test/ldbc-bi/q02.sql
  test/ldbc-bi/q03.sql
  test/ldbc-bi/q04.sql
  test/ldbc-bi/q05.sql
  test/ldbc-bi/q06.sql
  test/ldbc-bi/q07.sql
  test/ldbc-bi/q08.sql
  test/ldbc-bi/q09.sql
  test/ldbc-bi/q10.sql
  test/ldbc-bi/q11.sql
  test/ldbc-bi/q12.sql
  test/ldbc-bi/q13.sql
  test/ldbc-bi/q14.sql
  test/ldbc-bi/q15.sql
  test/ldbc-bi/q16.sql
  test/ldbc-bi/q17.sql
  test/ldbc-bi/q18.sql
  test/ldbc-bi/q19.sql
  test/ldbc-bi/q20.sql
  test/ldbc-bi/views.sql
  test/sqllogictest/cardinality.slt
  test/sqllogictest/ldbc_bi.slt
Labels: T-performance, T-testing, A-optimization, A-COMPUTE

#21288 tests: fix psycopg3 build
  test/lang/python/requirements.txt
  test/lang/python/smoketest.py
Labels: T-testing

#21290 Change `visit_bfs` to `visit_pre`
  src/expr/src/linear.rs
  src/expr/src/scalar/mod.rs
Labels: A-optimization, A-COMPUTE

#21229 Index usage docs
  doc/user/content/sql/explain.md
  doc/user/content/sql/functions/now_and_mz_now.md
  doc/user/content/sql/select.md
  doc/user/content/transform-data/optimization.md
Labels: A-docs

#21303 Introduce new IndexUsageType for fast path with LIMIT
  src/adapter/src/coord/peek.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/repr/src/explain.proto
  src/repr/src/explain/mod.rs
  src/transform/src/dataflow.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/transform/literal_constraints.slt
Labels: A-optimization, A-COMPUTE

#20941 Design doc: Faithful `EXPLAIN <catalog item>` output
  doc/developer/design/20230802_explain_running_dataflows.md
Labels: A-ADAPTER

#21308 cloudtests: unify wait
  misc/python/materialize/cloudtest/util/environment.py
  misc/python/materialize/cloudtest/util/kubectl.py
Labels: T-testing

#21350 cloudtests: fix type in sql_execute_ddl
  misc/python/materialize/cloudtest/util/sql.py
Labels: T-testing

#21261 Align `EXPLAIN MATERIALIZED VIEW` output with the runtime state
  misc/python/materialize/checks/all_checks.py
  misc/python/materialize/checks/explain_catalog_item.py
  src/adapter/src/catalog.rs
  src/adapter/src/coord.rs
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/explain/mir/mod.rs
  src/compute-client/src/explain/mod.rs
  src/repr/src/explain/mod.rs
  src/repr/src/explain/text.rs
  src/sql/src/plan/statement/dml.rs
  test/sqllogictest/explain/materialized_view.slt
Labels: A-COMPUTE, A-ADAPTER

#21369 explain: support `PHYSICAL VIEW FOR MATERIALIZED VIEW`
  src/adapter/src/catalog.rs
  src/adapter/src/coord.rs
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/coord/sequencer/inner.rs
  test/sqllogictest/explain/materialized_view.slt
Labels: A-COMPUTE, A-ADAPTER

#21349 cloudtests: repatriate EnvironmentConfig (mz repo)
  misc/python/materialize/cloudtest/config/environment_config.py
  misc/python/materialize/cloudtest/util/authentication.py
  misc/python/materialize/cloudtest/util/controller.py
  misc/python/materialize/cloudtest/util/docker_env.py
  misc/python/materialize/cloudtest/util/environment.py
  misc/python/materialize/cloudtest/util/sql.py
  misc/python/materialize/cloudtest/util/web_request.py
  misc/python/materialize/setup.py
Labels: T-testing

#21447 expr: guard against reducing to_jsonb(bool): jsonb to _: boolean
  src/expr/src/explain/text.rs
  src/expr/src/relation/canonicalize.rs
  src/expr/src/relation/mod.rs
  src/expr/src/scalar/mod.rs
  src/transform/src/attribute/mod.rs
  src/transform/src/attribute/relation_type.rs
  src/transform/tests/testdata/canonicalize_mfp
  src/transform/tests/testdata/let-get
  test/sqllogictest/github-21244.slt
Labels: A-optimization, A-COMPUTE

#21467 Revert "Add CLOCK generator source (#21373)"
  doc/user/content/sql/create-source/load-generator.md
  doc/user/sql-grammar/sql-grammar.bnf
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/ddl.rs
  src/sql-parser/src/parser.rs
  src/sql/src/plan/statement/ddl.rs
  src/storage-client/src/types/sources.proto
  src/storage-client/src/types/sources.rs
  src/storage/src/source/generator.rs
  src/storage/src/source/generator/clock.rs
Labels: release-blocker
