Repository MaterializeInc/materialize, pull requests merged in 2023-12, with the labels that each got.

#23583 ci: parallelize platform checks
  ci/test/pipeline.template.yml
  test/platform-checks/mzcompose.py
Labels: T-testing

#23609 ci: tests: disable "Checks + backup + rollback to previous"
  ci/nightly/pipeline.template.yml
Labels: T-testing

#23618 ci: Checks + backup + rollback to previous: update referenced issue in exclude
  ci/nightly/pipeline.template.yml
Labels: T-testing

#23614 ci: platform checks: disable alter connection tests again
  misc/python/materialize/checks/all_checks/alter_connection.py
Labels: T-testing

#23678 tests: re-enable PgCdcNoWait
  misc/python/materialize/checks/all_checks/pg_cdc.py
Labels: T-testing

#23610 ci: fetch tags only from mz main repo
  misc/python/materialize/git.py
Labels: T-testing

#23680 output consistency: miscellaneous adjustments
  misc/python/materialize/cli/ci_closed_issues_detect.py
  misc/python/materialize/output_consistency/data_type/data_type.py
  misc/python/materialize/output_consistency/data_value/data_column.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/input_data/operations/boolean_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/boolean_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/date_time_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/number_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/text_operation_param.py
  misc/python/materialize/output_consistency/input_data/test_input_data.py
  misc/python/materialize/output_consistency/input_data/types/date_time_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
  misc/python/materialize/output_consistency/input_data/validators/number_args_validator.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#23681 output consistency: add JSONB type
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/params/jsonb_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/jsonb_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/jsonb_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/jsonb_values_provider.py
  misc/python/materialize/output_consistency/operation/operation_param.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#23682 output consistency: add BYTEA type
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/bytea_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/crypto_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/bytea_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/return_specs/bytea_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/bytea_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/bytea_values_provider.py
  misc/python/materialize/output_consistency/validation/error_message_normalizer.py
Labels: T-testing

#23685 ci: include SLT tests in test/sqllogictest/transform/fold_vs_dataflow
  ci/slt/slt.sh
  test/sqllogictest/transform/fold_vs_dataflow/1_numbers_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/2_number_fns_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_folding.slt
  test/sqllogictest/transform/fold_vs_dataflow/4_text_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/4_text_folding.slt
  test/sqllogictest/transform/fold_vs_dataflow/5_repeat_row_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/6_bytea_dataflow.slt
Labels: T-testing

#23713 postgres consistency: remove ignore on timezone function
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22543 Docs: Fix line wrapping in functions list
  doc/user/layouts/shortcodes/fnlist.html
Labels: A-docs

#23745 Fix assert when a scalar window func is given args
  src/sql/src/plan/query.rs
  test/sqllogictest/window_funcs.slt
Labels: A-ADAPTER

#23617 tests: fix and make alter-connection tests more robust
  misc/python/materialize/checks/all_checks/alter_connection.py
Labels: T-testing

#23762 postgres consistency: enrich encode characteristics to let ignore match on regexp_split_to_array
  misc/python/materialize/output_consistency/input_data/operations/bytea_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
Labels: T-testing

#23774 tests: disable alter-connection test in cloudtest upgrade
  test/cloudtest/test_upgrade.py
Labels: T-testing

#23798 postgres consistency: extend ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#23855 postgres consistency: update issue reference
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#23785 Make `text_to_mz_timestamp` try harder
  doc/user/content/sql/types/mz_timestamp.md
  src/repr/src/scalar.rs
  src/repr/src/timestamp.rs
  test/sqllogictest/mztimestamp.slt
Labels: A-ADAPTER

#23837 postgres consistency: extend ignores regarding JSONB whitespaces
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#23831 postgres consistency: extend ignores regarding regex groups
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/ignore_filter/param_matchers.py
  misc/python/materialize/output_consistency/input_data/operations/bytea_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#23829 tests: add scenario "accumulate reductions" to bounded memory and feature benchmark
  test/bounded-memory/mzcompose.py
  test/feature-benchmark/scenarios.py
Labels: T-testing

#23865 postgres consistency: fix broken ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#23866 output consistency: improve and extend ignores
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#23884 output consistency: fix return type specs
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
Labels: T-testing

#23861 Add `EXPLAIN WITH (redacted)` support for MIR plans
  misc/python/materialize/cli/ci_closed_issues_detect.py
  src/adapter/src/catalog/state.rs
  src/adapter/src/coord/peek.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/optimize/subscribe.rs
  src/compute-types/src/explain/text.rs
  src/expr/src/explain/mod.rs
  src/expr/src/explain/text.rs
  src/expr/src/relation/mod.rs
  src/repr/src/explain/mod.rs
  src/repr/src/explain/text.rs
  src/sql/src/plan/explain/text.rs
  src/transform/src/optimizer_notices.rs
  test/sqllogictest/attributes/mir_unique_keys.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/outer_join_lowering.slt
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/sqllogictest/tpch_select.slt
  test/sqllogictest/transform/literal_constraints.slt
  test/testdrive/primary-key-optimizations.td
  test/testdrive/subexpression-replacement.td
Labels: A-COMPUTE

#23891 tests: accumulate reductions: follow-up
  test/bounded-memory/mzcompose.py
  test/feature-benchmark/scenarios.py
Labels: T-testing

#23901 adapter: add `enable_mz_notices` feature flag
  misc/python/materialize/checks/all_checks/optimizer_notices.py
  src/adapter/src/catalog.rs
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/sql/src/session/vars.rs
  test/sqllogictest/transform/notice/index_key_empty.slt
  test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#23929 tests: bounded memory: add 0.5Gb materialized_memory to accumulate-reductions
  test/bounded-memory/mzcompose.py
Labels: T-testing

#23940 tests: version resolution: refactoring to reduce code duplication
  misc/python/materialize/version_list.py
Labels: T-testing

#23920 tests: allow running individual testdrive test in cloudtest
  test/cloudtest/test_full_testdrive.py
Labels: T-testing

#23941 tests: version resolution: allow use-case specific commit overrides
  misc/python/materialize/version_list.py
  test/feature-benchmark/mzcompose.py
  test/scalability/mzcompose.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#23926 adapter: move `dataflows` from `coord` to `optimize`
  .github/CODEOWNERS
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/state.rs
  src/adapter/src/client.rs
  src/adapter/src/coord.rs
  src/adapter/src/coord/indexes.rs
  src/adapter/src/coord/peek.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/timestamp_selection.rs
  src/adapter/src/error.rs
  src/adapter/src/optimize/dataflows.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/adapter/src/optimize/view.rs
  src/adapter/src/webhook.rs
  src/transform/src/dataflow.rs
  src/transform/src/lib.rs
  src/transform/tests/test_runner.rs
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#23971 output consistency: add hex value to text type
  misc/python/materialize/output_consistency/input_data/values/text_values_provider.py
Labels: T-testing

#23982 tests: fix return code handling
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/postgres_consistency/postgres_consistency_test.py
  misc/python/materialize/version_consistency/version_consistency_test.py
Labels: T-testing

#23597 platform-checks: Disable KafkaChecks for backup+restore
  misc/python/materialize/checks/all_checks/error.py
  misc/python/materialize/checks/all_checks/json_source.py
  misc/python/materialize/checks/all_checks/kafka_formats.py
  misc/python/materialize/checks/all_checks/upsert_wide.py
Labels: C-bug

#23830 ci: re-introduce VersionsFromDocs, move legacy-upgrade to tests
  ci/nightly/pipeline.template.yml
  ci/test/pipeline.template.yml
  misc/python/materialize/version_list.py
  test/legacy-upgrade/mzcompose.py
Labels: T-testing

#24021 ci: add git-based legacy-upgrade test to nightly
  ci/nightly/pipeline.template.yml
  ci/test/pipeline.template.yml
  test/legacy-upgrade/mzcompose.py
Labels: T-testing

#23984 tests: handle accepted regressions in release builds
  misc/python/materialize/docker.py
  misc/python/materialize/scalability/comparison_outcome.py
  misc/python/materialize/scalability/endpoint.py
  misc/python/materialize/scalability/endpoints.py
  misc/python/materialize/scalability/regression_assessment.py
  misc/python/materialize/scalability/result_analyzers.py
  misc/python/materialize/version_list.py
  test/feature-benchmark/mzcompose.py
  test/scalability/mzcompose.py
Labels: T-testing

#24039 Revert "sql: teach subsources about RETAIN HISTORY"
  src/environmentd/tests/sql.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/pure.rs
Labels: release-blocker

#24049 adapter: implement off-thread optimization for `CREATE MATERIALIZED VIEW`
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/optimize/materialized_view.rs
  src/sql/src/session/vars.rs
Labels: A-ADAPTER

#24068 Move `CREATE VIEW` optimization off the coordinator thread
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/create_view.rs
Labels: A-ADAPTER

#24072 Move `CREATE INDEX` optimization off the coordinator thread
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/create_view.rs
  src/adapter/src/optimize/index.rs
Labels: A-ADAPTER

#24092 Move `SUBSCRIBE` optimization off the coordinator thread
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/subscribe.rs
  src/adapter/src/optimize/subscribe.rs
  src/sql/src/plan.rs
Labels: A-ADAPTER

#23888 Refresh types while in letrec major
  src/transform/src/normalize_lets.rs
Labels: advent-of-code

#24163 pgwire: fix perf regression with portal paging (#24093)
  src/pgwire/src/protocol.rs
Labels: release-blocker
