Repository MaterializeInc/materialize, pull requests merged in 2023-11, with the labels that each got.

#22847 scalability framework: ensure commit infos available
  misc/python/materialize/buildkite.py
  misc/python/materialize/git.py
  test/scalability/mzcompose.py
Labels: T-testing

#22846 scalability framework: rework plots, introduce boxplot
  misc/python/materialize/scalability/plot/plot.py
  misc/python/materialize/scalability/workload_executor.py
  misc/python/materialize/scalability/workload_result.py
  test/scalability/lib.py
Labels: T-testing

#22853 scalability framework: generate and upload plots in CI
  .gitignore
  ci/mkpipeline.py
  ci/test/cargo-test/mzcompose.py
  misc/python/materialize/buildkite.py
  misc/python/materialize/ci_util/trim_pipeline.py
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/benchmark_result.py
  misc/python/materialize/scalability/io/paths.py
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/lib.py
  test/scalability/mzcompose.py
  test/scalability/results/.gitignore
  test/scalability/scalability.ipynb
Labels: T-testing

#22877 scalability framework: improve plots
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/lib.py
  test/scalability/mzcompose.py
Labels: T-testing

#22915 scalability framework: extend docs regarding common-ancestor
  misc/python/materialize/benchmark_utils.py
  test/scalability/README.md
Labels: T-testing

#22916 scalability framework: include zero in y-axis
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/lib.py
  test/scalability/mzcompose.py
  test/scalability/scalability.ipynb
Labels: T-testing

#22913 scalability framework: add diagram explanations
  test/scalability/README.md
Labels: T-testing

#22912 scalability framework: allow configuring regression threshold
  test/scalability/README.md
  test/scalability/mzcompose.py
Labels: T-testing

#22919 scalability framework: highlight regression target
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/lib.py
  test/scalability/mzcompose.py
Labels: T-testing

#22922 output-consistency: add ignores
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#22917 scalability framework: include workload name in exported plots
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/lib.py
  test/scalability/mzcompose.py
Labels: T-testing

#22928 scalability framework: rename latency to duration
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/README.md
  test/scalability/lib.py
  test/scalability/mzcompose.py
Labels: T-testing

#22955 output consistency: add invalid value in enum constants
  misc/python/materialize/output_consistency/enum/enum_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/values/date_time_values_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22946 output consistency: remove ignore on timezone function after issue has been resolved
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22967 output consistency: update issue references
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22929 scalability framework: introduce duration boxplot allowing comparison by concurrent connections
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/lib.py
  test/scalability/mzcompose.py
Labels: T-testing

#22986 output consistency: add ignores
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22959 explain: change `humanized_exprs` output format
  src/expr/src/explain/text.rs
  src/repr/src/explain/mod.rs
  src/transform/src/attribute/mod.rs
  src/transform/tests/test_transforms/humanized_exprs.spec
  test/sqllogictest/attributes/mir_unique_keys.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/filter-pushdown.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/outer_join_lowering.slt
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/sqllogictest/tpch_select.slt
  test/sqllogictest/transform/literal_constraints.slt
  test/testdrive/primary-key-optimizations.td
  test/testdrive/subexpression-replacement.td
Labels: A-optimization, A-COMPUTE

#22858 adapter: use the new `Optimize` API in `sequence_peek`
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/peek.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/old_optimizer_api.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/adapter/src/optimize/view.rs
  src/compute-types/src/plan/mod.rs
  src/repr/src/explain/tracing.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
  src/transform/src/canonicalization/flatmap_to_map.rs
  src/transform/src/canonicalization/projection_extraction.rs
  src/transform/src/canonicalization/topk_elision.rs
  src/transform/src/canonicalize_mfp.rs
  src/transform/src/column_knowledge.rs
  src/transform/src/compound/union.rs
  src/transform/src/cse/anf.rs
  src/transform/src/cse/relation_cse.rs
  src/transform/src/dataflow.rs
  src/transform/src/demand.rs
  src/transform/src/fold_constants.rs
  src/transform/src/fusion/filter.rs
  src/transform/src/fusion/join.rs
  src/transform/src/fusion/map.rs
  src/transform/src/fusion/mod.rs
  src/transform/src/fusion/negate.rs
  src/transform/src/fusion/project.rs
  src/transform/src/fusion/reduce.rs
  src/transform/src/fusion/top_k.rs
  src/transform/src/fusion/union.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/literal_constraints.rs
  src/transform/src/literal_lifting.rs
  src/transform/src/movement/projection_lifting.rs
  src/transform/src/movement/projection_pushdown.rs
  src/transform/src/non_null_requirements.rs
  src/transform/src/nonnullable.rs
  src/transform/src/normalize_lets.rs
  src/transform/src/normalize_ops.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/reduce_elision.rs
  src/transform/src/reduction_pushdown.rs
  src/transform/src/redundant_join.rs
  src/transform/src/semijoin_idempotence.rs
  src/transform/src/threshold_elision.rs
  src/transform/src/union_cancel.rs
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#23020 output consistency: add new ignores
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#23021 output consistency: cleanup: remove unnecessary links
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
Labels: T-testing

#22971 adapter: move timestamp resolution after optimization
  src/adapter/src/catalog/state.rs
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/adapter/src/optimize/view.rs
  src/compute-types/src/dataflows.rs
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#23031 output consistency: add further ignores (2)
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/util.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#22944 sql,pgtz: improve support for timezone abbreviations
  Cargo.lock
  bin/lint
  doc/user/content/sql/system-catalog/pg_catalog.md
  doc/user/data/sql_funcs.yml
  misc/python/materialize/cli/lint-cargo.py
  src/adapter/src/session.rs
  src/catalog/src/builtin.rs
  src/cluster-client/build.rs
  src/compute-client/build.rs
  src/compute-types/build.rs
  src/environmentd/tests/testdata/timezones/abbrevs-2023-06-15.csv
  src/environmentd/tests/testdata/timezones/abbrevs-2023-12-15.csv
  src/environmentd/tests/testdata/timezones/names-2023-06-15.csv
  src/environmentd/tests/testdata/timezones/names-2023-12-15.csv
  src/environmentd/tests/timezones.rs
  src/expr/Cargo.toml
  src/expr/build.rs
  src/expr/src/scalar.proto
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/time.rs
  src/expr/src/scalar/func/impls/timestamp.rs
  src/expr/src/scalar/mod.rs
  src/pgrepr-consts/src/oid.rs
  src/pgtz/Cargo.toml
  src/pgtz/build.rs
  src/pgtz/src/abbrev.rs
  src/pgtz/src/lib.rs
  src/pgtz/src/timezone.proto
  src/pgtz/src/timezone.rs
  src/proto/Cargo.toml
  src/proto/build.rs
  src/proto/src/chrono.proto
  src/proto/src/chrono.rs
  src/proto/src/lib.rs
  src/repr/Cargo.toml
  src/repr/build.rs
  src/repr/src/adt/datetime.proto
  src/repr/src/adt/datetime.rs
  src/repr/src/adt/timestamp.rs
  src/repr/src/lib.rs
  src/repr/src/row.proto
  src/repr/src/row/encoding.rs
  src/repr/src/strconv.rs
  src/sql/src/func.rs
  src/sql/src/session/vars.rs
  src/storage-client/build.rs
  src/storage-types/build.rs
  src/storage-types/src/errors.rs
  src/storage-types/src/sources.proto
  test/sqllogictest/information_schema_tables.slt
  test/sqllogictest/pg_catalog_timezone_abbrevs.slt
  test/sqllogictest/pg_catalog_timezone_names.slt
  test/sqllogictest/timezone.slt
  test/testdrive/session.td
Labels: release-blocker

#23058 output consistency: fixes and further ignores
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#23022 adapter: never remove timeline state
  src/adapter/src/catalog.rs
  src/adapter/src/coord/ddl.rs
  src/adapter/src/coord/timeline.rs
  src/catalog/src/durable/transaction.rs
Labels: T-platform-v2

#23065 version consistency: catch all date-time operations
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#23051 adapter: improve GlobalMirPlan until resolution
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/optimize/peek.rs
Labels: release-blocker

#23060 scalability framework: introduce data-frame abstraction layer
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/benchmark_result.py
  misc/python/materialize/scalability/df/df_details.py
  misc/python/materialize/scalability/df/df_totals.py
  misc/python/materialize/scalability/df/df_totals_ext_cols.py
  misc/python/materialize/scalability/df/df_wrapper_base.py
  misc/python/materialize/scalability/plot/plot.py
  misc/python/materialize/scalability/regression.py
  misc/python/materialize/scalability/regression_outcome.py
  misc/python/materialize/scalability/result_analyzer.py
  misc/python/materialize/scalability/result_analyzers.py
  misc/python/materialize/scalability/workload_result.py
  test/scalability/lib.py
  test/scalability/mzcompose.py
Labels: T-testing

#23097 scalability framework: remove scatterplot variant for duration
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/lib.py
Labels: T-testing

#23091 scalability framework: boxplot: do not mix different types of SQL commands
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/df/df_details.py
  misc/python/materialize/scalability/df/df_details_cols.py
Labels: T-testing

#23098 scalability framework: introduce violin plots
  misc/python/materialize/scalability/df/df_wrapper_base.py
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/README.md
  test/scalability/lib.py
  test/scalability/mzcompose.py
Labels: T-testing

#23139 output consistency: ignore filter: improved class hierarchy
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter_base.py
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_outcome.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/postgres_consistency_test.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
  misc/python/materialize/version_consistency/version_consistency_test.py
Labels: T-testing

#23138 version consistency: drop function id suffix from error message before comparison
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/version_consistency/validation/version_consistency_error_message_normalizer.py
  misc/python/materialize/version_consistency/version_consistency_test.py
Labels: T-testing

#23174 version consistency: add ignore for array_agg and string_agg
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#23187 version consistency: clean ignore
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#23190 tests: fix github-23037.td
  test/testdrive/github-23037.td
Labels: T-testing

#23188 tests: sqlsmith: add ignore
  misc/python/materialize/sqlsmith.py
Labels: T-testing

#23145 ci: comparison with release version (1/2)
  misc/python/materialize/benchmark_utils.py
  misc/python/materialize/buildkite.py
  misc/python/materialize/checks/mzcompose_actions.py
  misc/python/materialize/docker.py
  misc/python/materialize/git.py
  misc/python/materialize/mzcompose/composition.py
  misc/python/materialize/util.py
  test/feature-benchmark/mzcompose.py
  test/scalability/mzcompose.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#23184 ci: move MzVersion to own file
  misc/python/materialize/checks/all_checks/array_type.py
  misc/python/materialize/checks/all_checks/cluster_unification.py
  misc/python/materialize/checks/all_checks/comment.py
  misc/python/materialize/checks/all_checks/default_privileges.py
  misc/python/materialize/checks/all_checks/identifiers.py
  misc/python/materialize/checks/all_checks/json_source.py
  misc/python/materialize/checks/all_checks/kafka_protocols.py
  misc/python/materialize/checks/all_checks/managed_cluster.py
  misc/python/materialize/checks/all_checks/materialized_views.py
  misc/python/materialize/checks/all_checks/owners.py
  misc/python/materialize/checks/all_checks/pg_cdc.py
  misc/python/materialize/checks/all_checks/privileges.py
  misc/python/materialize/checks/all_checks/rename_cluster.py
  misc/python/materialize/checks/all_checks/rename_replica.py
  misc/python/materialize/checks/all_checks/rename_schema.py
  misc/python/materialize/checks/all_checks/replica.py
  misc/python/materialize/checks/all_checks/roles.py
  misc/python/materialize/checks/all_checks/sink.py
  misc/python/materialize/checks/all_checks/statement_logging.py
  misc/python/materialize/checks/all_checks/swap_cluster.py
  misc/python/materialize/checks/all_checks/swap_schema.py
  misc/python/materialize/checks/all_checks/temporal_types.py
  misc/python/materialize/checks/all_checks/uuid.py
  misc/python/materialize/checks/all_checks/webhook.py
  misc/python/materialize/checks/checks.py
  misc/python/materialize/checks/cloudtest_actions.py
  misc/python/materialize/checks/executors.py
  misc/python/materialize/checks/mzcompose_actions.py
  misc/python/materialize/checks/scenarios.py
  misc/python/materialize/checks/scenarios_upgrade.py
  misc/python/materialize/docker.py
  misc/python/materialize/git.py
  misc/python/materialize/mz_version.py
  misc/python/materialize/mzcompose/services/materialized.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/util.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
  misc/python/materialize/version_list.py
  test/cloudtest/test_upgrade.py
  test/legacy-upgrade/mzcompose.py
  test/upgrade-matrix/mzcompose.py
  test/upgrade-matrix/nodes.py
Labels: T-testing

#23024 dbt-materialize: Metadata Freshness
  misc/dbt-materialize/CHANGELOG.md
  misc/dbt-materialize/README.md
  misc/dbt-materialize/dbt/adapters/materialize/impl.py
  misc/dbt-materialize/dbt/include/materialize/macros/freshness.sql
  misc/dbt-materialize/setup.py
  misc/dbt-materialize/tests/adapter/test_list_relations_without_caching.py
  misc/dbt-materialize/tests/adapter/test_source_freshness.py
Labels: T-dbt

#23217 tests: bounded memory: more appropriate setup
  ci/nightly/pipeline.template.yml
  test/bounded-memory/mzcompose.py
Labels: T-testing

#23004 dbt-materialize: Migrate `date_spine` Tests
  misc/dbt-materialize/tests/adapter/test_utils.py
Labels: T-dbt

#23239 ci: harden resolution of ancestor image
  misc/python/materialize/docker.py
Labels: T-testing

#23235 ci: fix PR detection
  misc/python/materialize/buildkite.py
  misc/python/materialize/ui.py
Labels: T-testing

#23005 dbt-materialize: Additional Tests `dbt show` `--limit`
  misc/dbt-materialize/tests/adapter/test_show.py
Labels: T-dbt

#23003 dbt-materialize: Catalog Fetch
  misc/dbt-materialize/dbt/adapters/materialize/impl.py
  misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql
  misc/dbt-materialize/dbt/include/materialize/macros/catalog.sql
  misc/dbt-materialize/dbt/include/materialize/macros/materializations/incremental.sql
  misc/dbt-materialize/dbt/include/materialize/macros/materializations/table.sql
  misc/dbt-materialize/tests/adapter/fixtures.py
  misc/dbt-materialize/tests/adapter/test_basic.py
  misc/dbt-materialize/tests/adapter/test_clusters.py
  misc/dbt-materialize/tests/adapter/test_relation_types.py
Labels: T-dbt

#23023 [WIP] dbt-materialize: 1.7.0 Additional Tests
  misc/dbt-materialize/tests/adapter/test_dbt_clone.py
  misc/dbt-materialize/tests/adapter/test_seed.py
Labels: T-dbt

#23025 dbt-materialize: Store Failures As
  doc/user/content/manage/dbt.md
  misc/dbt-materialize/CHANGELOG.md
  misc/dbt-materialize/README.md
  misc/dbt-materialize/dbt/include/materialize/macros/materializations/test.sql
  misc/dbt-materialize/tests/adapter/test_store_test_failures.py
Labels: T-dbt

#22806 Add `INCLUDE HEADER` option to Kafka source
  src/sql-parser/src/ast/defs/ddl.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
  src/sql/src/plan/statement/ddl.rs
  src/storage-types/src/sources.proto
  src/storage-types/src/sources.rs
  src/storage/src/source/kafka.rs
  test/testdrive/kafka-headers.td
Labels: T-proto

#23266 Security: Reintroduce cargo-vet in CI
  Cargo.toml
  bin/lint
  ci/builder/Dockerfile
  ci/test/pipeline.template.yml
  doc/developer/guide.md
  misc/cargo-vet/audits.toml
  misc/cargo-vet/config.toml
  misc/cargo-vet/imports.lock
Labels: T-security

#22262 adapter: add Postgres-backed TimestampOracle
  Cargo.lock
  misc/cockroach/setup_materialize.sql
  misc/images/materialized/entrypoint.sh
  misc/python/materialize/cli/ci_logged_errors_detect.py
  misc/python/materialize/cli/run.py
  misc/python/materialize/cloudtest/k8s/environmentd.py
  misc/python/materialize/mzcompose/__init__.py
  misc/python/materialize/mzcompose/services/materialized.py
  misc/python/materialize/scalability/endpoints.py
  src/adapter/Cargo.toml
  src/adapter/src/coord.rs
  src/adapter/src/coord/timeline.rs
  src/adapter/src/coord/timestamp_oracle.rs
  src/adapter/src/coord/timestamp_oracle/catalog_oracle.rs
  src/adapter/src/coord/timestamp_oracle/metrics.rs
  src/adapter/src/coord/timestamp_oracle/postgres_oracle.rs
  src/adapter/src/coord/timestamp_oracle/retry.rs
  src/environmentd/src/bin/environmentd/main.rs
  src/environmentd/src/lib.rs
  src/environmentd/src/test_util.rs
  src/postgres-client/src/metrics.rs
  src/sql/src/session/vars.rs
  src/sqllogictest/src/runner.rs
  test/crdb-restarts/mzcompose.py
  test/feature-benchmark/mzcompose.py
  test/scalability/mzcompose.py
Labels: T-platform-v2

#23368 adapter: enforce max_sources limit with ALTER SOURCE
  src/adapter/src/coord/ddl.rs
  test/cluster/resources/resource-limits.td
Labels: release-blocker

#23411 scalability framework: replace two workloads
  misc/python/materialize/scalability/operations.py
  misc/python/materialize/scalability/schema.py
  misc/python/materialize/scalability/workloads.py
Labels: T-testing

#23107 tests: alter connection for zippy
  ci/nightly/pipeline.template.yml
  misc/python/materialize/checks/mzcompose_actions.py
  misc/python/materialize/mzcompose/services/ssh_bastion_host.py
  misc/python/materialize/zippy/framework.py
  misc/python/materialize/zippy/scenarios.py
  misc/python/materialize/zippy/source_actions.py
  misc/python/materialize/zippy/source_capabilities.py
  test/zippy/mzcompose.py
Labels: T-testing

#23424 doc/developer: update `sqllogictest.md` useful tips
  doc/developer/sqllogictest.md
Labels: A-docs

#23466 scalability framework: report scalability improvements
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/benchmark_result.py
  misc/python/materialize/scalability/comparison_outcome.py
  misc/python/materialize/scalability/df/df_totals.py
  misc/python/materialize/scalability/df/df_totals_ext_cols.py
  misc/python/materialize/scalability/io/paths.py
  misc/python/materialize/scalability/regression_outcome.py
  misc/python/materialize/scalability/result_analyzer.py
  misc/python/materialize/scalability/result_analyzers.py
  misc/python/materialize/scalability/scalability_change.py
  test/scalability/mzcompose.py
Labels: T-testing

#23480 buildkite insights: allow filtering by branch and build state
  misc/python/materialize/buildkite_insights/step_durations/analysis.py
Labels: T-testing

#23529 scalability framework: ensure stable sort ordering of workloads
  test/scalability/mzcompose.py
Labels: T-testing

#23525 ci: provide mechanism to override ancestor release
  misc/python/materialize/docker.py
  misc/python/materialize/git.py
  misc/python/materialize/spawn.py
Labels: T-testing

#23455 tests: version handling: streamline to single version provider
  ci/deploy/docker.py
  misc/python/materialize/checks/scenarios_upgrade.py
  misc/python/materialize/cloudtest/k8s/environmentd.py
  misc/python/materialize/docker.py
  misc/python/materialize/git.py
  misc/python/materialize/version_list.py
  test/cloudtest/test_upgrade.py
  test/feature-benchmark/mzcompose.py
  test/legacy-upgrade/mzcompose.py
  test/scalability/mzcompose.py
  test/upgrade-matrix/mzcompose.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#23587 postgres consistency: add ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing
