Repository MaterializeInc/materialize, pull requests merged in 2023-07, with the labels that each got.

#20309 Output consistency tests: ignore error message deviation on evaluation shortcuts
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/runner/test_runner.py
Labels: T-testing

#20318 adapter: correctly compute dependencies for materialized views
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  test/sqllogictest/materialized_views.slt
Labels: release-blocker

#19991 Output consistency tests: Add coalesce and nullif
  misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/any_operation_param.py
Labels: T-testing

#20341 ci: Adjust coverage info message
  misc/python/materialize/cli/ci_coverage_pr_report.py
Labels: T-testing

#20344 Output inconsistency test: ignore deviations caused by NULL shortcuts
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
Labels: T-testing

#20358 Add various checks to `test_smoketest_all_builtins`
  src/adapter/src/catalog/builtin.rs
  src/expr/src/scalar/func.rs
Labels: A-optimization, A-COMPUTE

#20004 Documentation updates for managed clusters
  doc/user/content/get-started/key-concepts.md
  doc/user/content/get-started/quickstart.md
  doc/user/content/sql/alter-cluster.md
  doc/user/content/sql/create-cluster.md
  doc/user/layouts/partials/sql-grammar/alter-cluster-reset.svg
  doc/user/layouts/partials/sql-grammar/alter-cluster-set.svg
  doc/user/layouts/partials/sql-grammar/create-managed-cluster.svg
  doc/user/layouts/shortcodes/cluster-options.html
  doc/user/layouts/shortcodes/postgres-direct/create-an-ingestion-cluster.html
  doc/user/layouts/shortcodes/postgres-direct/right-size-the-cluster.html
  doc/user/sql-grammar/sql-grammar.bnf
Labels: A-docs, docs-impact

#20376 Output consistency tests: extend ignores, fix outcome determination
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/execution/test_summary.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_outcome.py
Labels: T-testing

#20397 Output consistency tests: fix result determination
  misc/python/materialize/output_consistency/execution/test_summary.py
Labels: T-testing

#20379 k8s-orchestrator: set fsGroup for clusterd pods
  src/environmentd/src/bin/environmentd/main.rs
  src/orchestrator-kubernetes/src/lib.rs
Labels: release-blocker

#20400 cloudtests: fix test_upgrade
  misc/python/materialize/cli/ci_logged_errors_detect.py
  misc/python/materialize/cloudtest/k8s/environmentd.py
Labels: T-testing

#20455 tests: LaunchDarkly: adapt log filter definition
  test/launchdarkly/mzcompose.py
Labels: T-testing

#20456 ci: add logged error "unrecognized configuration parameter"
  misc/python/materialize/cli/ci_logged_errors_detect.py
Labels: T-testing

#20480 tests: Fix "Full testdrive in cloudtest" by exposing port
  misc/python/materialize/cloudtest/k8s/environmentd.py
Labels: T-testing

#19984 storage: optionally spill upsert stat to disk only if size exceeds threshold
  src/adapter/src/flags.rs
  src/rocksdb-types/src/config.rs
  src/sql/src/session/vars.rs
  src/storage-client/src/types/parameters.proto
  src/storage-client/src/types/parameters.rs
  src/storage/src/internal_control.rs
  src/storage/src/render/upsert.rs
  src/storage/src/render/upsert/types.rs
  src/storage/src/source/metrics.rs
  src/storage/src/source/types.rs
  src/storage/src/storage_state.rs
  test/upsert/autospill/bytes.td
  test/upsert/mzcompose.py
Labels: release-blocker

#20593 tests: stabilize "Checks + restart source Postgres"
  misc/python/materialize/checks/debezium.py
Labels: T-testing

#20615 output consistency tests: collect and print previous queries on network error
  misc/python/materialize/output_consistency/execution/sql_executor.py
Labels: T-testing

#20525 Output consistency tests: add try_parse_monotonic_iso8601_timestamp
  misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
Labels: T-testing

#20638 output consistency tests: fix storage layout handling
  misc/python/materialize/output_consistency/execution/evaluation_strategy.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/query/query_template.py
Labels: T-testing

#19649 [transform] Estimating cardinality of MIR relation expressions
  Cargo.lock
  doc/user/content/sql/explain.md
  src/adapter/src/coord.rs
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/expr-test-util/tests/testdata/rel
  src/expr/src/relation/mod.rs
  src/expr/src/scalar/mod.rs
  src/repr/src/explain/mod.rs
  src/sql/src/session/vars.rs
  src/transform/Cargo.toml
  src/transform/src/attribute/cardinality.rs
  src/transform/src/attribute/mod.rs
  src/transform/src/dataflow.rs
  src/transform/src/fusion/filter.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/symbolic.rs
  src/transform/tests/test_transforms.rs
  src/transform/tests/testdata/reduction-pushdown
  src/transform/tests/testdata/steps
  test/sqllogictest/cardinality.slt
  test/sqllogictest/explain/optimized_plan_as_json.slt
Labels: T-performance, A-optimization, A-COMPUTE

#20678 tests: fix webhooks.py in nightly ("IN CLUSTER" changes)
  misc/python/materialize/checks/webhook.py
Labels: T-testing

#20682 tests: stabilize Postgres restart source with Debezium
  doc/developer/testdrive.md
  misc/python/materialize/checks/debezium.py
  src/testdrive/src/action/http.rs
Labels: T-testing

#20699 SQLsmith: ignore "csv_extract number of columns too large"
  test/sqlsmith/mzcompose.py
Labels: T-testing

#20695 storage: add some basic backpressure metrics
  src/compute/src/render/mod.rs
  src/storage-client/src/lib.rs
  src/storage-client/src/metrics.rs
  src/storage-client/src/source/persist_source.rs
  src/storage/src/render/sources.rs
  src/storage/src/render/upsert.rs
  src/storage/src/source/metrics.rs
  src/storage/src/source/types.rs
Labels: release-blocker

#20688 Configure backpressure max bytes in flight based on cluster size
  src/adapter/src/coord.rs
  src/adapter/src/coord/ddl.rs
  src/adapter/src/flags.rs
  src/cluster-client/src/client.proto
  src/cluster-client/src/client.rs
  src/cluster/src/server.rs
  src/cluster/src/types.rs
  src/compute-client/src/controller/replica.rs
  src/compute/src/server.rs
  src/controller/src/clusters.rs
  src/sql/src/session/vars.rs
  src/storage-client/src/controller.rs
  src/storage-client/src/controller/rehydration.rs
  src/storage-client/src/types/parameters.proto
  src/storage-client/src/types/parameters.rs
  src/storage/src/internal_control.rs
  src/storage/src/render/sources.rs
  src/storage/src/server.rs
  src/storage/src/storage_state.rs
  src/storage/tests/setup.rs
Labels: release-blocker

#20784 Don't push `error_if_null` through a Join
  src/expr/src/scalar/mod.rs
  src/transform/src/predicate_pushdown.rs
  test/sqllogictest/transform/predicate_pushdown.slt
Labels: A-optimization, A-COMPUTE

#20866 cloudtests: update design doc
  doc/developer/design/20230613_cloudtest_improvements.md
Labels: T-testing

#20870 tests: allow configuring testdrive timeout
  misc/python/materialize/cloudtest/k8s/testdrive.py
Labels: T-testing

#20867 cloudtests: prepare further semver imports for usage in cloud repo
  misc/python/materialize/cloudtest/k8s/environmentd.py
  misc/python/materialize/util.py
Labels: T-testing

#20868 cloudtests: allow more flexibility in application context
  misc/python/materialize/cloudtest/app/application.py
  misc/python/materialize/cloudtest/app/materialize_application.py
Labels: T-testing

#20844 adapter: stop LD client when `ENABLE_LAUNCHDARKLY = off`
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/config.rs
  src/adapter/src/config/frontend.rs
  src/adapter/src/config/mod.rs
  src/adapter/src/config/params.rs
  src/adapter/src/config/sync.rs
  src/adapter/src/coord.rs
  src/environmentd/src/lib.rs
  src/stash-debug/src/main.rs
  test/launchdarkly/mzcompose.py
Labels: A-ADAPTER
