Repository MaterializeInc/materialize, pull requests merged in 2023-09, with the labels that each got.

#21532 cloudtests: extract run_process_with_error_information
  misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
  misc/python/materialize/cloudtest/util/common.py
Labels: T-testing

#21530 cloudtests: separate Testdrive logic and pod
  misc/python/materialize/cloudtest/app/materialize_application.py
  misc/python/materialize/cloudtest/k8s/testdrive.py
Labels: T-testing

#21562 catalog: Remove SerializedX items from catalog
  Cargo.lock
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/migrate.rs
  src/adapter/src/catalog/storage.rs
  src/adapter/src/catalog/storage/objects.rs
  src/adapter/src/coord/sequencer/cluster.rs
  src/adapter/src/coord/sequencer/linked_cluster.rs
  src/compute-client/Cargo.toml
  src/compute-client/src/controller.rs
Labels: T-proto

#21551 benchmark: Add missing indices to LDBC
  test/ldbc-bi/ddl.sql
  test/ldbc-bi/views.sql
  test/sqllogictest/ldbc_bi.slt
Labels: T-performance, A-COMPUTE

#21538 docs/user: Link to `ALTER ... RENAME` from `ALTER CLUSTER`.
  doc/user/content/sql/alter-cluster.md
Labels: A-docs

#21670 cloudtests: allow configuring SSL mode for pgwire
  misc/python/materialize/cloudtest/util/authentication.py
  misc/python/materialize/cloudtest/util/sql.py
Labels: T-testing

#21669 Make coalesce's nullability more precise
  src/expr/src/scalar/func.rs
  test/sqllogictest/transform/column_knowledge.slt
  test/sqllogictest/types.slt
  test/testdrive/pg-catalog.td
Labels: A-optimization, A-COMPUTE

#21728 cloudtests: allow configuring envd waiting timeouts
  misc/python/materialize/cloudtest/util/environment.py
Labels: T-testing

#21681 adapter: add SystemVar flags to control optimizer stats timeouts
  src/adapter/src/coord/sequencer/inner.rs
  src/sql/src/session/vars.rs
  test/sqllogictest/cardinality.slt
Labels: T-performance, T-debug, A-optimization, A-COMPUTE, A-ADAPTER

#21760 rbac: relax RBAC requirements for `EXPLAIN <query>`
  doc/user/content/sql/explain-plan.md
  doc/user/content/sql/explain-timestamp.md
  src/sql/src/rbac.rs
  test/sqllogictest/privilege_checks.slt
Labels: A-ADAPTER

#21780 output consistency: fix value comparison (floating point, list)
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing

#21773 Correct string/number comparison in dataflow visualization
  src/environmentd/src/http/static/js/hierarchical-memory.jsx
  src/environmentd/src/http/static/js/memory.jsx
Labels: release-blocker

#21778 rbac: allow `EXPLAIN` commands in `user_privilege_hack`
  src/adapter/src/coord/introspection.rs
  test/testdrive/mz-support-privileges.td
Labels: A-ADAPTER

#21794 adapter: add more LaunchDarkly contexts
  src/adapter/src/config/frontend.rs
  src/adapter/src/config/mod.rs
  src/environmentd/src/lib.rs
  test/launchdarkly/mzcompose.py
Labels: A-ADAPTER

#21796 transform: add `ColumnNames` attribute
  Cargo.lock
  src/expr-parser/src/catalog.rs
  src/expr-parser/src/command.rs
  src/expr-parser/src/parser.rs
  src/expr-parser/tests/test_mir_parser/simple_trees.spec
  src/expr-parser/tests/test_mir_parser/with_ctes.spec
  src/repr/src/explain/mod.rs
  src/transform/Cargo.toml
  src/transform/src/attribute/arity.rs
  src/transform/src/attribute/cardinality.rs
  src/transform/src/attribute/column_names.rs
  src/transform/src/attribute/mod.rs
  src/transform/src/attribute/non_negative.rs
  src/transform/src/attribute/relation_type.rs
  src/transform/src/attribute/subtree_size.rs
  src/transform/src/attribute/unique_keys.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/threshold_elision.rs
  src/transform/tests/test_transforms.rs
  src/transform/tests/test_transforms/anf.spec
  src/transform/tests/test_transforms/arity.spec
  src/transform/tests/test_transforms/column_knowledge.spec
  src/transform/tests/test_transforms/column_names.spec
  src/transform/tests/test_transforms/literal_lifting.spec
  src/transform/tests/test_transforms/non_null_requirements.spec
  src/transform/tests/test_transforms/normalize_lets.spec
  src/transform/tests/test_transforms/predicate_pushdown.spec
  src/transform/tests/test_transforms/projection_lifting.spec
  src/transform/tests/test_transforms/projection_pushdown.spec
  src/transform/tests/test_transforms/redundant_join.spec
  src/transform/tests/test_transforms/relation_cse.spec
  src/transform/tests/test_transforms/semijoin_idempotence.spec
  src/transform/tests/test_transforms/typecheck.spec
  src/transform/tests/test_transforms/types.spec
Labels: A-optimization, A-COMPUTE

#21706 Give a notice when dropping an in-use index
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/notice.rs
  src/adapter/src/severity.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  test/pgtest-mz/notice.pt
Labels: A-optimization, A-COMPUTE

#21818 adapter: rename RescaleNumeric and CastTimestampToTimestamp functions + More tests
  src/expr/src/scalar.proto
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/numeric.rs
  src/expr/src/scalar/func/impls/timestamp.rs
  src/repr/src/adt/timestamp.rs
  src/sql/src/plan/typeconv.rs
  test/sqllogictest/dates-times.slt
Labels: T-proto

#21579 output consistency: add support for timestamp precision
  misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/types/date_time_types_provider.py
Labels: T-testing

#21939 output consistency: add new string functions
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
Labels: T-testing

#21976 cloudtests: allow configuring default timeout for requests
  misc/python/materialize/cloudtest/util/environment.py
  misc/python/materialize/cloudtest/util/web_request.py
Labels: T-testing

#22021 explain: support `EXPLAIN CREATE INDEX`
  Cargo.lock
  ci/test/slt-fast.sh
  misc/python/materialize/cli/ci_logged_errors_detect.py
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/explain
  src/sql/Cargo.toml
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
  test/sqllogictest/explain/broken_statements.slt
  test/sqllogictest/explain/decorrelated_plan_as_text.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/testdrive/mz-support-privileges.td
Labels: A-ADAPTER
