Repository MaterializeInc/materialize, pull requests merged in 2023-10, with the labels that each got.

#22062 cloudtests: use logger also in mz repo
  misc/python/materialize/cloudtest/app/application.py
  misc/python/materialize/cloudtest/app/materialize_application.py
  misc/python/materialize/cloudtest/k8s/api/k8s_service.py
  misc/python/materialize/cloudtest/k8s/api/k8s_stateful_set.py
  misc/python/materialize/cloudtest/util/common.py
  misc/python/materialize/cloudtest/util/controller.py
  misc/python/materialize/cloudtest/util/jwt_key.py
  misc/python/materialize/cloudtest/util/sql.py
  misc/python/materialize/cloudtest/util/wait.py
  misc/python/materialize/cloudtest/util/web_request.py
  pyproject.toml
  test/cloudtest/test_compute.py
  test/cloudtest/test_compute_shared_fate.py
  test/cloudtest/test_storage.py
  test/cloudtest/test_storage_shared_fate.py
  test/cloudtest/test_upgrade.py
Labels: T-testing

#22095 CI: use builder-linux-x86_64 in all checks
  ci/test/pipeline.template.yml
Labels: T-testing

#22111 CI: ignore await keyword in coverage
  misc/python/materialize/cli/ci_coverage_pr_report.py
Labels: T-testing

#22130 adapter: minor improvements in `Coordinator::sequence_~` methods
  src/adapter/src/coord/sequencer/inner.rs
Labels: A-ADAPTER

#22091 adapter: make all DurableTimestampOracle methods async
  Cargo.lock
  src/adapter/Cargo.toml
  src/adapter/src/coord.rs
  src/adapter/src/coord/appends.rs
  src/adapter/src/coord/ddl.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/read_policy.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/timeline.rs
  src/adapter/src/coord/timestamp_selection.rs
  src/adapter/tests/timestamp_selection.rs
Labels: T-platform-v2

#21977 doc/design: add design doc for Distributed TimestampOracle
  doc/developer/design/20230921_distributed_ts_oracle.md
  doc/developer/design/static/distributed_ts_oracle/insert-benchmark.png
  doc/developer/design/static/distributed_ts_oracle/peek-benchmark.png
  doc/developer/design/static/distributed_ts_oracle/update-benchmark.png
Labels: T-platform-v2

#22112 adapter: move timestamp oracle impl to it's own module, put behind trait object
  src/adapter/src/catalog.rs
  src/adapter/src/coord.rs
  src/adapter/src/coord/timeline.rs
  src/adapter/src/coord/timestamp_oracle.rs
  src/adapter/src/coord/timestamp_oracle/catalog_oracle.rs
Labels: T-platform-v2

#22156 ci: coverage report: allow ignoring files by path, ignore maelstrom
  misc/python/materialize/cli/ci_coverage_pr_report.py
Labels: T-testing

#22057 tests: test for incident 70
  ci/nightly/pipeline.template.yml
  test/cluster/mzcompose.py
Labels: T-testing

#22195 doc: update `EXPLAIN PLAN` docs
  doc/user/content/sql/explain-plan.md
  doc/user/layouts/partials/sql-grammar/explain-plan.svg
  doc/user/sql-grammar/sql-grammar.bnf
Labels: A-docs, A-optimization, A-COMPUTE

#22204 Reverse-proxy web console on /internal-console route on envd internal http server
  Cargo.lock
  src/environmentd/Cargo.toml
  src/environmentd/src/bin/environmentd/main.rs
  src/environmentd/src/http.rs
  src/environmentd/src/http/console.rs
  src/environmentd/src/lib.rs
  src/environmentd/tests/server.rs
Labels: release-blocker

#22184 auth: De-dupe token refreshes into a single task
  Cargo.lock
  src/adapter/src/session.rs
  src/balancerd/src/lib.rs
  src/balancerd/src/service.rs
  src/environmentd/src/bin/environmentd/main.rs
  src/environmentd/src/http.rs
  src/environmentd/tests/auth.rs
  src/environmentd/tests/util.rs
  src/frontegg-auth/Cargo.toml
  src/frontegg-auth/src/auth.rs
  src/frontegg-auth/src/client.rs
  src/frontegg-auth/src/client/tokens.rs
  src/frontegg-auth/src/lib.rs
  src/frontegg-auth/src/metrics.rs
  src/pgwire/src/protocol.rs
  src/repr/src/lib.rs
  src/repr/src/user.rs
  src/sql/src/session/user.rs
  src/sql/src/session/vars.rs
Labels: release-blocker

#20569 design: A unified optimizer interface
  doc/developer/design/20230714_optimizer_interface.md
Labels: A-docs, A-optimization, A-COMPUTE, A-ADAPTER

#22258 Fix a bug in `inline_if_not_too_big`
  src/transform/src/predicate_pushdown.rs
  test/sqllogictest/transform/predicate_pushdown.slt
Labels: release-blocker, A-optimization, A-COMPUTE

#22263 Use the new `Optimize` API for `CREATE MATERIALIZED VIEW`
  .github/CODEOWNERS
  src/adapter/src/coord.rs
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/old_optimizer_api.rs
  src/adapter/src/lib.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/sql/src/session/vars.rs
  src/transform/src/lib.rs
  src/transform/src/typecheck.rs
  src/transform/tests/test_transforms.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#22406 postgres consistency: update ignore filter
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#21968 Introduce arrangement specialization
  Cargo.lock
  src/adapter/src/coord/dataflows.rs
  src/adapter/src/flags.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/compute-client/src/protocol/command.proto
  src/compute-client/src/protocol/command.rs
  src/compute-types/src/explain/text.rs
  src/compute-types/src/plan.proto
  src/compute-types/src/plan/mod.rs
  src/compute/src/arrangement/manager.rs
  src/compute/src/compute_state.rs
  src/compute/src/logging/initialize.rs
  src/compute/src/render/context.rs
  src/compute/src/render/flat_map.rs
  src/compute/src/render/join/delta_join.rs
  src/compute/src/render/join/linear_join.rs
  src/compute/src/render/join/mz_join_core.rs
  src/compute/src/render/mod.rs
  src/compute/src/render/reduce.rs
  src/compute/src/render/sinks.rs
  src/compute/src/render/threshold.rs
  src/compute/src/render/top_k.rs
  src/repr/Cargo.toml
  src/repr/src/datum_vec.rs
  src/repr/src/fixed_length.rs
  src/repr/src/lib.rs
  src/repr/src/relation.rs
  src/repr/src/row.rs
  src/sql/src/session/vars.rs
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/testdrive/specialized_arrangements.td
Labels: T-proto

#22442 scalability framework: fix dataframe handling
  test/scalability/mzcompose.py
Labels: T-testing

#22355 ci: compare benchmarks against common-ancestor
  ci/nightly/pipeline.template.yml
  misc/buildkite/git.bash
  misc/python/materialize/benchmark_utils.py
  misc/python/materialize/buildkite.py
  misc/python/materialize/cli/ci_coverage_pr_report.py
  misc/python/materialize/git.py
  misc/python/materialize/mzcompose/composition.py
  misc/python/materialize/scalability/endpoints.py
  misc/python/materialize/version_list.py
  test/feature-benchmark/mzcompose.py
  test/scalability/mzcompose.py
Labels: T-testing

#22489 postgres consistency: ignore non-existing functions and operations al…
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22499 postgres consistency: ignore pow inconsistencies
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22496 postgres consistency: less coarse-grained function-does-not-exist ignores
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22476 scalability framework: upload regressions
  misc/python/materialize/scalability/regression.py
  misc/python/materialize/scalability/result_analyzers.py
  test/scalability/mzcompose.py
Labels: T-testing

#22537 scalability framework: Jupyter fixes
  misc/python/materialize/git.py
  misc/python/materialize/scalability/endpoints.py
  test/scalability/lib.py
Labels: T-testing

#22417 ci: integrate scalability framework in CI
  ci/nightly/pipeline.template.yml
  misc/python/materialize/scalability/endpoints.py
  misc/python/materialize/scalability/workload.py
  test/scalability/mzcompose.py
Labels: T-testing

#22579 scalability framework: plot: avoid errors on missing data
  test/scalability/lib.py
Labels: T-testing

#22583 scalability framework: add aggregation columns
  test/scalability/mzcompose.py
Labels: T-testing

#22580 scalability framework: regression detection on the fly
  misc/python/materialize/scalability/regression.py
  misc/python/materialize/scalability/result_analyzer.py
  misc/python/materialize/scalability/result_analyzers.py
  test/scalability/mzcompose.py
Labels: T-testing

#22590 scalability framework: extract constants
  misc/python/materialize/scalability/df/df_details_cols.py
  misc/python/materialize/scalability/df/df_totals_cols.py
  misc/python/materialize/scalability/df/df_totals_ext_cols.py
  misc/python/materialize/scalability/df/paths.py
  misc/python/materialize/scalability/result_analyzers.py
  test/scalability/mzcompose.py
Labels: T-testing

#22588 scalability framework: fix default workload selection
  test/scalability/mzcompose.py
Labels: T-testing

#22605 platform checks: disable failing statement_logging
  misc/python/materialize/checks/all_checks.py
Labels: T-testing

#22608 ci: parallel workload with naughty identifiers: introduce assertion
  misc/python/materialize/parallel_workload/database.py
Labels: T-testing

#22609 ci: increase CRDB sync durations
  misc/python/materialize/mzcompose/__init__.py
Labels: T-testing

#22564 Fix Get annotation when it access a GlobalId but inside the same dataflow
  src/expr/src/explain/text.rs
  src/expr/src/relation/mod.rs
  src/transform/src/dataflow.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/tpch_create_index.slt
Labels: A-optimization, A-COMPUTE

#22550 Docs: Mention group size hints in TopK patterns page
  doc/user/content/sql/select.md
  doc/user/content/transform-data/patterns/top-k.md
Labels: A-docs

#22613 doc/developer: document CLA check self-service fix
  doc/developer/guide-changes.md
Labels: A-docs

#22620 tests: parallel workload: adapt error message to ignore
  misc/python/materialize/parallel_workload/action.py
Labels: T-testing

#22641 ci: sqlsmith: cleanup
  test/sqlsmith/mzcompose.py
Labels: T-testing

#22617 ci: test selection: do not list skipped steps
  ci/mkpipeline.py
Labels: T-testing

#22611 scalability framework: extract classes and methods
  misc/python/materialize/scalability/benchmark_config.py
  misc/python/materialize/scalability/df/df_totals_cols.py
  misc/python/materialize/scalability/workload_executor.py
  test/scalability/mzcompose.py
Labels: T-testing

#22642 ci: run SQLsmith as mz_system
  test/sqlsmith/mzcompose.py
Labels: T-testing

#22648 ci: upgrade-matrix: fix
  test/upgrade-matrix/mzcompose.py
Labels: T-testing

#22612 scalability framework: retry on regression
  misc/python/materialize/scalability/regression.py
  misc/python/materialize/scalability/workload_executor.py
Labels: T-testing

#22591 scalability framework: enable in CI
  ci/nightly/pipeline.template.yml
Labels: T-testing

#22654 scalability framework: improve observability
  misc/python/materialize/scalability/endpoints.py
  misc/python/materialize/scalability/workload_executor.py
  test/scalability/mzcompose.py
Labels: T-testing

#22663 ci: fix data-ingest
  misc/python/materialize/data_ingest/executor.py
Labels: T-testing

#22614 scalability framework: upload workload results
  misc/python/materialize/scalability/df/paths.py
  misc/python/materialize/scalability/workload_executor.py
  test/scalability/mzcompose.py
Labels: T-testing

#22664 adapter: rework `feature_flags` macro
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/state.rs
  src/sql/src/session/vars.rs
Labels: A-ADAPTER

#22672 scalability framework: fix name handling
  misc/python/materialize/scalability/endpoint.py
  misc/python/materialize/scalability/endpoints.py
  misc/python/materialize/scalability/result_analyzers.py
  misc/python/materialize/scalability/workload_executor.py
  test/scalability/mzcompose.py
Labels: T-testing

#22674 platform upgrade checks: fix min version in RenameSchemas
  misc/python/materialize/checks/all_checks/schemas.py
Labels: T-testing

#22691 output consistency: tidy up ignore class
  misc/python/materialize/output_consistency/ignore_filter/ignore_verdict.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter_base.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22692 Minor fix in window function docs
  doc/user/data/sql_funcs.yml
Labels: A-docs

#22682 ci: platform checks: introduce @disabled annotation, restore ignores
  doc/developer/platform-checks.md
  misc/python/materialize/checks/all_checks/peek_cancellation.py
  misc/python/materialize/checks/all_checks/pg_cdc.py
  misc/python/materialize/checks/checks.py
Labels: T-testing

#22704 output consistency: support rebuilding expressions for analysis
  misc/python/materialize/output_consistency/enum/enum_operation_param.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/runner/test_runner.py
Labels: T-testing

#22733 output consistency: error message extraction fix
  misc/python/materialize/output_consistency/execution/sql_executor.py
Labels: T-testing

#22734 postgres consistency: add ignore entry
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#22744 explain: control outer join lowering via `ExplainConfig`
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/open.rs
  src/adapter/src/catalog/state.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/old_optimizer_api.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/optimize/view.rs
  src/catalog/src/memory/objects.rs
  src/repr/src/explain/mod.rs
  src/sql/src/plan/lowering.rs
  test/sqllogictest/outer_join_lowering.slt
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#22783 scalability framework: update Python libs
  ci/builder/requirements.txt
Labels: T-testing

#22787 scalability framework: refactor and extract plotting functionality
  misc/python/materialize/scalability/plot/plot.py
  test/scalability/lib.py
Labels: T-testing

#22811 scalability framework: regression handling
  misc/python/materialize/scalability/result_analyzers.py
  misc/python/materialize/scalability/workload_executor.py
  test/scalability/mzcompose.py
Labels: T-testing

#22791 Use the new `Optimize` API for `CREATE VIEW`
  src/adapter/src/catalog/state.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/optimize/view.rs
  src/sql/src/plan.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/rbac.rs
  src/sql/src/session/vars.rs
Labels: A-optimization, A-COMPUTE, A-ADAPTER
