Repository MaterializeInc/materialize, pull requests merged in 2023-02, with the labels that each got.

#17450 Initial stab at a `Normalize` transform
  src/transform/src/canonicalize_mfp.rs
  src/transform/src/fusion/filter.rs
  src/transform/src/fusion/flatmap_to_map.rs
  src/transform/src/fusion/join.rs
  src/transform/src/fusion/map.rs
  src/transform/src/fusion/mod.rs
  src/transform/src/fusion/negate.rs
  src/transform/src/fusion/project.rs
  src/transform/src/fusion/top_k.rs
  src/transform/src/fusion/union.rs
  src/transform/src/lib.rs
  src/transform/src/normalize/mod.rs
  src/transform/src/projection_extraction.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
  test/sqllogictest/relation-cse.slt
Labels: A-optimization, A-COMPUTE

#17505 dbt-materialize: release v1.4.0
  misc/dbt-materialize/CHANGELOG.md
  misc/dbt-materialize/dbt/adapters/materialize/__version__.py
  misc/dbt-materialize/setup.py
  misc/dbt-materialize/tests/adapter/test_utils.py
Labels: T-dbt

#17518 explain: various simplifications
  src/adapter/src/coord/peek.rs
  src/adapter/src/explain/fast_path/mod.rs
  src/adapter/src/explain/hir/mod.rs
  src/adapter/src/explain/lir/mod.rs
  src/adapter/src/explain/mir/mod.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/compute-client/src/explain/mod.rs
  src/compute-client/src/explain/text.rs
  src/expr-test-util/tests/testdata/scalar
  src/expr/src/explain/mod.rs
  src/expr/src/explain/text.rs
  src/expr/src/relation/mod.rs
  src/expr/src/scalar/mod.rs
  src/expr/tests/testdata/reduce
  src/ore/src/str.rs
  src/repr/src/explain/mod.rs
  src/repr/src/explain/text.rs
  src/sql/src/plan/explain/mod.rs
  src/sql/src/plan/explain/text.rs
  src/transform/tests/test_runner.rs
  test/sqllogictest/transform/join_index.slt
Labels: A-optimization, A-COMPUTE

#17564 storage: skip committing empty offset partition lists to kafka
  src/storage/src/source/kafka.rs
Labels: release-blocker

#17644 Support non-append-only COUNTER sources
  doc/user/content/sql/create-source/load-generator.md
  doc/user/layouts/partials/sql-grammar/load-generator-option.svg
  doc/user/sql-grammar/sql-grammar.bnf
  src/sql-parser/src/ast/defs/ddl.rs
  src/sql-parser/src/keywords.txt
  src/sql-parser/src/parser.rs
  src/sql/src/plan/statement/ddl.rs
  src/storage-client/src/types/sources.proto
  src/storage-client/src/types/sources.rs
  src/storage/src/source/generator.rs
  src/storage/src/source/generator/counter.rs
  test/testdrive/load-generator.td
Labels: T-proto

#17671 Minor fix in join optimization docs
  doc/user/content/ops/optimization.md
Labels: A-docs

#17604 explain: implement `timing` option
  misc/python/materialize/cli/optbench.py
  misc/python/materialize/optbench/sql.py
  misc/python/materialize/optbench/util.py
  src/adapter/src/coord/sequencer.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/expr/src/explain/mod.rs
  src/expr/src/explain/text.rs
  src/expr/src/relation/mod.rs
  src/repr/src/explain/mod.rs
  src/repr/src/explain/tracing.rs
  src/transform/tests/test_runner.rs
Labels: A-optimization, A-COMPUTE

#17751 doc/user: restructure `CREATE CONNECTION` page
  doc/user/content/integrations/_index.md
  doc/user/content/releases/v0.40.md
  doc/user/content/sql/create-connection.md
  doc/user/content/sql/create-sink/kafka.md
  doc/user/content/sql/create-source/kafka.md
  doc/user/content/sql/create-source/postgres.md
  doc/user/layouts/partials/sql-grammar/create-connection-aws-privatelink.svg
  doc/user/layouts/partials/sql-grammar/create-connection-csr.svg
  doc/user/layouts/partials/sql-grammar/create-connection-kafka-broker-aws-privatelink.svg
  doc/user/layouts/partials/sql-grammar/create-connection-kafka-broker-ssh-tunnel.svg
  doc/user/layouts/partials/sql-grammar/create-connection-kafka-broker.svg
  doc/user/layouts/partials/sql-grammar/create-connection-kafka.svg
  doc/user/layouts/partials/sql-grammar/create-connection-postgres.svg
  doc/user/layouts/partials/sql-grammar/create-connection-ssh-tunnel.svg
  doc/user/layouts/partials/sql-grammar/create-connection.svg
  doc/user/sql-grammar/sql-grammar.bnf
Labels: A-docs
