Repository MaterializeInc/materialize, pull requests merged in 2023-06, with the labels that each got.

#19602 Test generator for output consistency checks (V2): better type information
  misc/python/materialize/output_consistency/data_value/data_column.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/expression/leaf_expression.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/any_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/boolean_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/number_operation_param.py
  misc/python/materialize/output_consistency/input_data/types/boolean_type_provider.py
  misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
  misc/python/materialize/output_consistency/input_data/validators/number_args_validator.py
  misc/python/materialize/output_consistency/input_data/values/number_values_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/operation/operation_args_validator.py
  misc/python/materialize/output_consistency/operation/operation_param.py
Labels: T-testing

#19655 docs: Fix !~ operator description
  doc/user/content/sql/functions/_index.md
Labels: T-docs-update

#19656 docs: Fix variance function names
  doc/user/data/sql_funcs.yml
Labels: T-docs-update

#19659 Output consistency tests: Fix aggregation function definitions
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
Labels: T-testing

#19423 sql: implement the age(...) function
  src/expr/src/scalar.proto
  src/expr/src/scalar/func.rs
  src/repr/src/adt/timestamp.rs
  src/repr/src/scalar.rs
  src/sql/src/func.rs
  test/sqllogictest/interval.slt
Labels: C-feature, A-sql, A-ADAPTER

#19705 Output consistency tests: ignore var_samp, var_pop, array_agg, string_agg
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing

#18714 expr: add a parser for `EXPLAIN` output of `MirRelationExpr` terms
  Cargo.lock
  Cargo.toml
  src/expr-parser/Cargo.toml
  src/expr-parser/src/catalog.rs
  src/expr-parser/src/command.rs
  src/expr-parser/src/lib.rs
  src/expr-parser/src/parser.rs
  src/expr-parser/tests/test_mir_parser.rs
  src/expr-parser/tests/test_mir_parser/arrange_by.spec
  src/expr-parser/tests/test_mir_parser/join.spec
  src/expr-parser/tests/test_mir_parser/reduce.spec
  src/expr-parser/tests/test_mir_parser/scalar_exprs.spec
  src/expr-parser/tests/test_mir_parser/simple_trees.spec
  src/expr-parser/tests/test_mir_parser/top_k.spec
  src/expr-parser/tests/test_mir_parser/with_ctes.spec
  src/expr/Cargo.toml
  src/expr/src/explain/text.rs
  src/transform/Cargo.toml
  src/transform/tests/test_transforms.rs
  src/transform/tests/test_transforms/anf.spec
  src/transform/tests/test_transforms/column_knowledge.spec
  src/transform/tests/test_transforms/literal_lifting.spec
  src/transform/tests/test_transforms/non_null_requirements.spec
  src/transform/tests/test_transforms/normalize_lets.spec
  src/transform/tests/test_transforms/predicate_pushdown.spec
  src/transform/tests/test_transforms/projection_lifting.spec
  src/transform/tests/test_transforms/projection_pushdown.spec
  src/transform/tests/test_transforms/redundant_join.spec
  src/transform/tests/test_transforms/relation_cse.spec
  src/transform/tests/test_transforms/semijoin_idempotence.spec
  src/workspace-hack/Cargo.toml
Labels: A-optimization, A-COMPUTE

#19609 Add `rank()` window function
  doc/user/data/sql_funcs.yml
  src/compute-client/src/plan/reduce.rs
  src/compute/src/render/reduce.rs
  src/expr/src/relation.proto
  src/expr/src/relation/func.rs
  src/expr/src/relation/mod.rs
  src/sql/src/func.rs
  src/sql/src/plan/expr.rs
  test/sqllogictest/window_funcs.slt
Labels: A-COMPUTE

#19260 Design doc for cost model
  doc/developer/design/20230512_mir_cost_model.md
Labels: C-feature, T-performance, A-optimization, A-COMPUTE

#19816 Output consistency tests: ignore log error message deviations
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing

#19736 adapter: improve OutOfRange errors
  src/buf.yaml
  src/expr/src/relation/func.rs
  src/expr/src/scalar.proto
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/byte.rs
  src/expr/src/scalar/func/impls/datum.rs
  src/expr/src/scalar/func/impls/float32.rs
  src/expr/src/scalar/func/impls/float64.rs
  src/expr/src/scalar/func/impls/int16.rs
  src/expr/src/scalar/func/impls/int32.rs
  src/expr/src/scalar/func/impls/int64.rs
  src/expr/src/scalar/func/impls/interval.rs
  src/expr/src/scalar/func/impls/jsonb.rs
  src/expr/src/scalar/func/impls/list.rs
  src/expr/src/scalar/func/impls/map.rs
  src/expr/src/scalar/func/impls/mz_timestamp.rs
  src/expr/src/scalar/func/impls/numeric.rs
  src/expr/src/scalar/func/impls/string.rs
  src/expr/src/scalar/func/impls/uint16.rs
  src/expr/src/scalar/func/impls/uint32.rs
  src/expr/src/scalar/func/impls/uint64.rs
  src/expr/src/scalar/mod.rs
  test/sqllogictest/arithmetic.slt
  test/sqllogictest/boolean.slt
  test/sqllogictest/dates-times.slt
  test/sqllogictest/float.slt
  test/sqllogictest/interval.slt
  test/sqllogictest/jsonb.slt
  test/sqllogictest/numeric.slt
  test/sqllogictest/oid.slt
  test/sqllogictest/postgres/float4.slt
  test/sqllogictest/postgres/float8.slt
  test/sqllogictest/type-promotion.slt
  test/sqllogictest/unsigned_int.slt
  test/testdrive/temporal.td
Labels: A-ADAPTER, T-proto

#19725 ci: introduce kail to collect cloudtest logs
  bin/ci-builder
  ci/builder/Dockerfile
  ci/builder/README.md
  ci/plugins/cloudtest/README.md
  ci/plugins/cloudtest/hooks/command
  ci/plugins/cloudtest/hooks/post-command
Labels: T-testing

#19837 Revert "persist: fix bug where apply_diff wasn't updating some State fields"
  src/persist-client/src/internal/state_diff.rs
Labels: release-blocker

#19839 Index `MZ_SOURCE_STATISTICS` and decrease its retention
  src/adapter/src/catalog/builtin.rs
  test/sqllogictest/cluster.slt
  test/testdrive/catalog.td
  test/testdrive/indexes.td
Labels: release-blocker

#19855 Output consistency tests: adapt message normalization
  misc/python/materialize/output_consistency/validation/error_message_normalizer.py
Labels: T-testing

#19819 Output consistency tests: various improvements
  misc/python/materialize/output_consistency/enum/enum_operation_param.py
  misc/python/materialize/output_consistency/execution/evaluation_strategy.py
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/execution/sql_executor.py
  misc/python/materialize/output_consistency/execution/test_summary.py
  misc/python/materialize/output_consistency/execution/value_storage_layout.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/boolean_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/trigonometric_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/any_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/boolean_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/date_time_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/number_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/number_return_spec.py
  misc/python/materialize/output_consistency/input_data/test_input_data.py
  misc/python/materialize/output_consistency/input_data/validators/generic_args_validator.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/operation/operation_param.py
  misc/python/materialize/output_consistency/output/output_printer.py
  misc/python/materialize/output_consistency/query/query_result.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/validation/validation_message.py
  misc/python/materialize/output_consistency/validation/validation_outcome.py
  test/output-consistency/README.md
Labels: T-testing

#19672 Output consistency tests: support text type
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/params/text_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/array_return_spec.py
  misc/python/materialize/output_consistency/input_data/return_specs/text_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/text_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/text_values_provider.py
Labels: T-testing

#19838 transform: Spec tests on typechecking
  src/expr-parser/tests/test_mir_parser/arrange_by.spec
  src/transform/src/typecheck.rs
  src/transform/tests/test_transforms.rs
  src/transform/tests/test_transforms/typecheck.spec
Labels: T-testing, A-COMPUTE

#18007 persist: mfp pushdown design doc
  doc/developer/design/20230306_persist_mfp_pushdown.md
Labels: A-STORAGE

#19962 test utility: print kubernetes pods
  misc/python/materialize/cloudtest/util/print_pods.py
  misc/python/materialize/cloudtest/wait.py
Labels: T-testing

#19928 docs: cloudtest improvements design doc
  doc/developer/design/20230613_cloudtest_improvements.md
Labels: T-testing

#19906 Cloudtest improvements: repo preparation
  .gitignore
  doc/developer/cloudtest.md
  misc/python/materialize/checks/executors.py
  misc/python/materialize/cloudtest/__init__.py
  misc/python/materialize/cloudtest/app/application.py
  misc/python/materialize/cloudtest/app/materialize_application.py
  misc/python/materialize/git.py
  misc/python/materialize/setup.py
  test/cloudtest/conftest.py
  test/cloudtest/test_antiaffinity.py
  test/cloudtest/test_cluster_rehydration.py
  test/cloudtest/test_compute.py
  test/cloudtest/test_compute_shared_fate.py
  test/cloudtest/test_crash.py
  test/cloudtest/test_egress_ips.py
  test/cloudtest/test_full_testdrive.py
  test/cloudtest/test_labels.py
  test/cloudtest/test_metrics.py
  test/cloudtest/test_privatelink_connection.py
  test/cloudtest/test_replica_restart.py
  test/cloudtest/test_secrets.py
  test/cloudtest/test_smoke.py
  test/cloudtest/test_ssh_tunnels.py
  test/cloudtest/test_storage.py
  test/cloudtest/test_storage_shared_fate.py
  test/cloudtest/test_upgrade.py
Labels: T-testing

#19222 docs: Adds RBAC intro & guides
  doc/user/config.toml
  doc/user/content/invite-users.md
  doc/user/content/manage/access-control/_index.md
  doc/user/content/manage/access-control/manage-privileges.md
  doc/user/content/manage/access-control/manage-roles.md
  doc/user/content/manage/access-control/rbac-tutorial.md
  doc/user/content/sql/namespaces.md
  doc/user/static/images/add-user.png
Labels: A-docs, T-docs-new-feature

#20049 storage-client: add param to disable shard finalization
  src/adapter/src/catalog.rs
  src/sql/src/session/vars.rs
  src/storage-client/src/controller.rs
  src/storage-client/src/types/parameters.proto
  src/storage-client/src/types/parameters.rs
Labels: release-blocker

#20081 Fix nullability inference for Timestamp-Interval arithmetics
  src/expr/src/scalar/func.rs
  test/sqllogictest/dates-times.slt
Labels: A-COMPUTE

#20124 Backport 0.57.9 reverts
  Cargo.lock
  clippy.toml
  doc/user/content/sql/system-catalog/mz_internal.md
  src/adapter/src/catalog/builtin.rs
  src/cluster/src/types.rs
  src/compute-client/src/logging.proto
  src/compute-client/src/logging.rs
  src/compute/Cargo.toml
  src/compute/src/compute_state.rs
  src/compute/src/extensions/arrange.rs
  src/compute/src/extensions/collection.rs
  src/compute/src/extensions/mod.rs
  src/compute/src/lib.rs
  src/compute/src/logging/compute.rs
  src/compute/src/logging/differential.rs
  src/compute/src/logging/initialize.rs
  src/compute/src/logging/mod.rs
  src/compute/src/logging/reachability.rs
  src/compute/src/logging/timely.rs
  src/compute/src/render/context.rs
  src/compute/src/render/join/linear_join.rs
  src/compute/src/render/mod.rs
  src/compute/src/render/reduce.rs
  src/compute/src/render/threshold.rs
  src/compute/src/render/top_k.rs
  src/compute/src/server.rs
  src/compute/src/typedefs.rs
  src/environmentd/src/http/static/js/hierarchical-memory.jsx
  src/environmentd/src/http/static/js/memory.jsx
  src/expr/Cargo.toml
  src/storage-client/src/types/errors.rs
  src/storage/src/render/sinks.rs
  src/timely-util/Cargo.toml
  src/timely-util/src/lib.rs
  src/timely-util/src/operator.rs
  src/timely-util/src/reduce.rs
  test/sqllogictest/cluster.slt
  test/sqllogictest/information_schema_tables.slt
  test/testdrive/catalog.td
  test/testdrive/divergent-dataflow-cancellation.td
  test/testdrive/indexes.td
  test/testdrive/introspection-sources.td
  test/testdrive/logging.td
Labels: release-blocker

#20229 tracing: ensure we don't apply the otel filter globally
  src/ore/src/tracing.rs
Labels: release-blocker

#20236 adapter: eagerly validate max replicas limit for managed clusters
  src/adapter/src/coord/sequencer/cluster.rs
  src/adapter/src/error.rs
  test/sqllogictest/managed_cluster.slt
Labels: release-blocker
