Repository MaterializeInc/materialize, pull requests merged in 2024-05, with the labels that each got.

#26853 transform: add `transforms!` macro
  src/transform/src/lib.rs
Labels: A-optimization, A-COMPUTE

#26844 output consistency: add some further values
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/input_data/values/bytea_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/text_values_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26837 tests: platform checks: support changing system vars, add scenario TogglePersistRoundtripSpine
  ci/nightly/pipeline.template.yml
  misc/python/materialize/checks/mzcompose_actions.py
  misc/python/materialize/checks/scenarios.py
  test/platform-checks/mzcompose.py
Labels: T-testing

#26858 ci: cloudtests execution
  ci/nightly/pipeline.template.yml
  test/cloudtest/test_storage_shared_fate.py
Labels: T-testing

#26877 tests: node recovery: increase timeout
  test/cloudtest/node_recovery/test_k8s_node_recovery.py
Labels: T-testing

#26876 tests: node recovery: improve output
  test/cloudtest/node_recovery/test_k8s_node_recovery.py
Labels: T-testing

#26882 ci: slow cloudtests: increase timeout
  ci/nightly/pipeline.template.yml
Labels: T-testing

#26925 tests: fix parallel-workload, data-ingest
  misc/python/materialize/data_ingest/executor.py
Labels: T-testing

#26911 tests: node recovery: fix
  test/cloudtest/node_recovery/test_k8s_node_recovery.py
Labels: T-testing

#26845 bounded memory: add scenario from #15044
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26822 storage/copy-to-s3: Parquet format support for nested types: array, list, map
  src/arrow-util/src/builder.rs
  src/pgwire/src/protocol.rs
  src/testdrive/src/action/s3.rs
  test/testdrive/copy-to-s3-minio.td
Labels: A-STORAGE

#26867 parallel workload: feature-flag flips
  misc/python/materialize/parallel_workload/action.py
  misc/python/materialize/parallel_workload/parallel_workload.py
Labels: T-testing

#26954 bounded memory: fix memory search
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26955 feature benchmark: improve regression reporting
  misc/python/materialize/feature_benchmark/benchmark.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#26424 tests: bounded memory: enable mysql-cdc-large-tx
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26958 postgres consistency: fix ignore entry
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26890 Add `mz_internal.mz_materialized_view_refreshes`
  doc/user/content/sql/system-catalog/mz_internal.md
  src/adapter/src/catalog/builtin_table_updates.rs
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/optimize/materialized_view.rs
  src/catalog/src/builtin.rs
  src/catalog/src/memory/objects.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  src/compute-types/build.rs
  src/compute-types/src/dataflows.proto
  src/compute-types/src/dataflows.rs
  src/compute-types/src/plan/lowering.rs
  src/compute-types/src/sinks.proto
  src/compute-types/src/sinks.rs
  src/compute/src/server.rs
  src/compute/src/sink/refresh.rs
  src/controller/src/lib.rs
  src/environmentd/tests/testdata/http/ws
  src/expr/build.rs
  src/expr/src/lib.rs
  src/expr/src/refresh_schedule.rs
  src/pgrepr-consts/src/oid.rs
  src/repr/build.rs
  src/repr/src/lib.rs
  src/repr/src/refresh_schedule.proto
  src/repr/src/refresh_schedule.rs
  src/repr/src/timestamp.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement/ddl.rs
  src/storage-client/src/controller.rs
  src/storage-controller/src/lib.rs
  test/cluster/mzcompose.py
  test/sqllogictest/autogenerated/mz_internal.slt
  test/sqllogictest/information_schema_tables.slt
  test/sqllogictest/materialized_views.slt
  test/sqllogictest/oid.slt
  test/testdrive/catalog.td
  test/testdrive/materialized-view-refresh-options.td
Labels: A-COMPUTE

#26987 platform checks: allow changing multiple vars in SystemVarChange
  misc/python/materialize/checks/scenarios.py
Labels: T-testing

#26997 storage/mysql: Support specifying date/datetime columns as text
  src/mysql-util/src/decoding.rs
  src/mysql-util/src/desc.proto
  src/mysql-util/src/desc.rs
  src/mysql-util/src/schemas.rs
  test/mysql-cdc/30-text-columns.td
Labels: release-blocker

#26896 bazel: Add rules for building all necessary C dependencies
  .bazelrc
  WORKSPACE
  ci/test/lint-main/checks/check-copyright.sh
  misc/bazel/BUILD.bazel
  misc/bazel/c_deps/BUILD.bazel
  misc/bazel/c_deps/BUILD.bzip2.bazel
  misc/bazel/c_deps/BUILD.jemalloc.bazel
  misc/bazel/c_deps/BUILD.lz4.bazel
  misc/bazel/c_deps/BUILD.openssl.bazel
  misc/bazel/c_deps/BUILD.zlib.bazel
  misc/bazel/c_deps/BUILD.zstd.bazel
  misc/bazel/c_deps/extra_setup.bzl
  misc/bazel/c_deps/openssl/test.cc
  misc/bazel/c_deps/repositories.bzl
  misc/bazel/c_deps/rust-sys/BUILD.librdkafka.bazel
  misc/bazel/c_deps/rust-sys/BUILD.rocksdb.bazel
  misc/bazel/c_deps/rust-sys/README.md
  misc/bazel/rules/BUILD.bazel
  misc/bazel/rules/utils.bzl
  misc/bazel/third_party/README.md
  misc/bazel/third_party/openssl/openssl_repositories.bzl
Labels: A-build

#27047 Make EXPLAIN not need a replica
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/pushdown.slt
Labels: A-ADAPTER

#27055 output consistency: add NULL as constant param
  misc/python/materialize/output_consistency/enum/enum_operation_param.py
Labels: T-testing

#27079 postgres consistency: add ignores
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27077 qa canary: error handling
  test/canary-load/mzcompose.py
Labels: T-testing

#27076 tests: use assert instead of fail
  test/cloudtest/node_recovery/test_k8s_node_recovery.py
Labels: T-testing

#27082 output consistency: improve return type info
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/input_data/return_specs/dynamic_return_spec.py
  misc/python/materialize/output_consistency/operation/return_type_spec.py
Labels: T-testing

#27062 output consistency: support for maps
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/params/map_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/map_return_spec.py
  misc/python/materialize/output_consistency/input_data/return_specs/map_value_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/map_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/map_values_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
Labels: T-testing

#27096 postgres consistency: extend ignore regarding string representation o…
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27095 output consistency: improve warnings
  misc/python/materialize/output_consistency/execution/test_summary.py
  misc/python/materialize/output_consistency/runner/test_runner.py
Labels: T-testing

#27104 version consistency: fix error msg normalization
  misc/python/materialize/version_consistency/validation/version_consistency_error_message_normalizer.py
  misc/python/materialize/version_consistency/version_consistency_test.py
Labels: T-testing

#27102 output consistency: add UUID type
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/uuid_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/params/uuid_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/uuid_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/uuid_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/uuid_values_provider.py
Labels: T-testing

#27127 output consistency: mathematical functions in lowercase
  misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/trigonometric_operations_provider.py
Labels: T-testing

#27123 tests: run upgrade checks on release docs update, fail on forgotten release bump
  ci/test/pipeline.template.yml
  test/skip-version-upgrade/mzcompose.py
Labels: T-testing

#27128 output consistency: add comment field to operations
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/equality_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/runner/test_runner.py
Labels: T-testing

#27132 postgres consistency: add ignore for UUID error with zero rows
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27135 Create historical versions of source statistics built in views
  doc/user/content/sql/system-catalog/mz_internal.md
  src/catalog/src/builtin.rs
  src/environmentd/tests/testdata/http/ws
  src/pgrepr-consts/src/oid.rs
  test/sqllogictest/autogenerated/mz_internal.slt
  test/sqllogictest/cluster.slt
  test/sqllogictest/information_schema_tables.slt
  test/sqllogictest/mz_introspection_index_accounting.slt
  test/sqllogictest/oid.slt
  test/testdrive/indexes.td
  test/testdrive/mz-arrangement-sharing.td
Labels: release-blocker

#27139 storage/copy-to-s3: Fix bugs; refactor ParquetFile / ArrowBuilder structure
  src/arrow-util/src/builder.rs
  src/storage-operators/src/s3_oneshot_sink/parquet.rs
  test/copy-to-s3/mzcompose.py
  test/copy-to-s3/nightly/tpch1gb.td
  test/testdrive/copy-to-s3-minio.td
Labels: A-STORAGE

#27130 qa canary: ignore read timeout, improve test case infos
  test/canary-load/mzcompose.py
Labels: T-testing

#27124 postgres consistency: change exclusion to ignore
  misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27129 output consistency: generalize map type structures
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/input_data/params/collection_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/map_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/collection_return_spec.py
  misc/python/materialize/output_consistency/input_data/return_specs/map_return_spec.py
  misc/python/materialize/output_consistency/input_data/return_specs/map_value_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/collection_type_provider.py
  misc/python/materialize/output_consistency/input_data/types/map_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/map_values_provider.py
Labels: T-testing

#27147 output consistency: add pg_typeof function
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/special_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27152 postgres consistency: add ignores for pg_typeof
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27125 output consistency: add list type
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/params/list_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/list_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/list_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/list_values_provider.py
Labels: T-testing

#27185 platform checks: extend MaterializedViews with validate statement
  misc/python/materialize/checks/all_checks/materialized_views.py
Labels: T-testing

#27190 parallel workload: add error to ignore
  misc/python/materialize/parallel_workload/action.py
Labels: T-testing

#27197 platform checks: fix upgrade checks
  misc/python/materialize/checks/all_checks/materialized_views.py
Labels: T-testing

#27193 output consistency: ignore entries refactoring
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#27203 platform checks: fix upgrade checks
  misc/python/materialize/checks/all_checks/materialized_views.py
Labels: T-testing

#27207 storage/pg: fix bug with capability handling
  src/storage/src/source/postgres/replication.rs
Labels: release-blocker

#27202 postgres consistency: fix
  misc/python/materialize/postgres_consistency/execution/pg_dialect_adjuster.py
Labels: T-testing

#27194 postgres consistency: add ignores
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27187 scalability framework: add CreateAndReplaceViewWorkload (incident #109)
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/operations.py
  misc/python/materialize/scalability/workloads/connection_workloads.py
  misc/python/materialize/scalability/workloads/ddl_workloads.py
  misc/python/materialize/scalability/workloads/dml_dql_workloads.py
  misc/python/materialize/scalability/workloads/self_test_workloads.py
  test/scalability/mzcompose.py
Labels: T-testing

#27195 postgres consistency: fix ignore logic of content mismatches
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26856 attribute: deprecate in favor of `analysis` framework
  .github/CODEOWNERS
  src/adapter/src/catalog.rs
  src/adapter/src/coord/peek.rs
  src/adapter/src/explain/mir.rs
  src/expr-parser/src/catalog.rs
  src/expr-test-util/src/lib.rs
  src/repr/src/explain.rs
  src/transform/src/analysis.rs
  src/transform/src/analysis/equivalences.rs
  src/transform/src/attribute.rs
  src/transform/src/attribute/arity.rs
  src/transform/src/attribute/cardinality.rs
  src/transform/src/attribute/column_names.rs
  src/transform/src/attribute/non_negative.rs
  src/transform/src/attribute/relation_type.rs
  src/transform/src/attribute/subtree_size.rs
  src/transform/src/attribute/unique_keys.rs
  src/transform/src/equivalence_propagation.rs
  src/transform/src/lib.rs
  src/transform/src/normalize_lets.rs
  src/transform/src/reduce_elision.rs
  src/transform/src/threshold_elision.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/test_transforms.rs
  src/transform/tests/test_transforms/column_names.spec
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/outer_join_simplification.slt
  test/sqllogictest/transform/threshold_elision.slt
Labels: A-optimization, A-COMPUTE

#27224 parallel workload: collect exception of all types
  misc/python/materialize/mzcompose/composition.py
  misc/python/materialize/parallel_workload/parallel_workload.py
  misc/python/materialize/parallel_workload/worker.py
  misc/python/materialize/parallel_workload/worker_exception.py
Labels: T-testing

#26573 mzexplore: compute maximum depth of ASTs in the wild
  misc/mzexplore/defs.jq
  misc/mzexplore/depth.jq
Labels: A-optimization, A-COMPUTE

#27248 output consistency: generalize text type
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/bytea_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/crypto_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/special_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/string_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/date_time_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/params/number_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/string_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/string_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/string_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/bytea_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/string_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/text_values_provider.py
  misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#27279 tests fix: index_too_wide_for_literal_constraints.slt
  test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt
Labels: T-testing

#27249 output consistency: add further string types
  misc/python/materialize/output_consistency/enum/enum_constant.py
  misc/python/materialize/output_consistency/enum/enum_operation_param.py
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/string_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/string_values_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27229 explain: minor fixes
  src/adapter/src/coord/peek.rs
  src/expr/src/explain/text.rs
  src/expr/src/relation/func.rs
  src/transform/src/analysis.rs
  src/transform/tests/test_transforms/column_names.spec
  src/transform/tests/test_transforms/humanized_exprs.spec
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text_redacted.slt
  test/sqllogictest/filter-pushdown.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/ldbc_bi_eager.slt
  test/sqllogictest/limit.slt
  test/sqllogictest/outer_join_lowering.slt
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/sqllogictest/tpch_select.slt
  test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt
Labels: A-optimization, A-COMPUTE

#27322 tests: add reworked RTR resumption tests
  test/kafka-rtr/mzcompose.py
  test/kafka-rtr/resumption/ingest-data.td
  test/kafka-rtr/resumption/mz-reset.td
  test/kafka-rtr/resumption/mz-setup.td
  test/kafka-rtr/resumption/toxiproxy-close-connection.td
  test/kafka-rtr/resumption/toxiproxy-limit-connection.td
  test/kafka-rtr/resumption/toxiproxy-restore-connection.td
  test/kafka-rtr/resumption/toxiproxy-setup.td
  test/kafka-rtr/resumption/toxiproxy-timeout-hold.td
  test/kafka-rtr/resumption/toxiproxy-timeout.td
Labels: T-testing

#27340 output consistency: print operation and function statistics
  misc/python/materialize/output_consistency/execution/test_summary.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/output/output_printer.py
  misc/python/materialize/output_consistency/runner/test_runner.py
Labels: T-testing

#27310 scalability framework: versioning
  misc/python/materialize/scalability/scalability_versioning.py
  misc/python/materialize/scalability/workload.py
  misc/python/materialize/scalability/workload_version.py
  misc/python/materialize/test_analytics/versioning/check_versioning.py
  misc/python/materialize/test_analytics/versioning/scalability/scalability_version_skew_check.py
Labels: T-testing

#27312 feature benchmark: versioning
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/scenario.py
  misc/python/materialize/feature_benchmark/scenario_version.py
  misc/python/materialize/test_analytics/versioning/benchmark/benchmark_version_skew_check.py
  misc/python/materialize/test_analytics/versioning/check_versioning.py
Labels: T-testing

#27343 tests: enable and adjust catalog.td
  test/testdrive/catalog.td
Labels: T-testing

#27375 tests: ignore proptest_packed_mz_acl_item_sorts
  src/repr/src/adt/mz_acl_item.rs
Labels: T-testing

#27300 sql: optimize regexp_replace for static regexes
  src/expr/src/scalar.proto
  src/expr/src/scalar.rs
  src/expr/src/scalar/func.rs
  test/sqllogictest/mzcompose.py
  test/sqllogictest/regex.slt
Labels: A-optimization, A-COMPUTE
