Repository MaterializeInc/materialize, pull requests merged in 2024-08, with the labels that each got.

#28688 Add metrics for outer join lowering cases
  Cargo.lock
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/explain/insights.rs
  src/adapter/src/optimize.rs
  src/adapter/src/optimize/copy_to.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/adapter/src/optimize/view.rs
  src/sql/Cargo.toml
  src/sql/src/lib.rs
  src/sql/src/optimizer_metrics.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/lowering/variadic_left.rs
  src/sql/src/plan/statement/dml.rs
Labels: A-optimization, A-CLUSTER

#28711 Remove deprecated `REHYDRATION TIME ESTIMATE`
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
Labels: A-ADAPTER

#28742 feature benchmark: unit mingling: improve observability
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/comparator.py
Labels: T-testing

#28743 feature benchmark: improve output
  misc/python/materialize/feature_benchmark/benchmark.py
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/comparator.py
Labels: T-testing

#28749 platform checks: add more SHOW CREATE SOURCE validations
  misc/python/materialize/checks/all_checks/debezium.py
  misc/python/materialize/checks/all_checks/kafka_formats.py
  misc/python/materialize/checks/all_checks/webhook.py
Labels: T-testing

#28802 postgres consistency: add ignore for floor return type
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28799 feature benchmark: fix unit mismatch
  misc/python/materialize/feature_benchmark/aggregation.py
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/comparator.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#28752 feature-flag consistency test: preparations
  misc/python/materialize/output_consistency/execution/evaluation_strategy.py
  misc/python/materialize/output_consistency/execution/multi_mz_executors.py
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/execution/sql_executor.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/status/test_summary.py
  misc/python/materialize/postgres_consistency/postgres_consistency_test.py
  misc/python/materialize/version_consistency/execution/multi_version_executors.py
  misc/python/materialize/version_consistency/version_consistency_test.py
  test/output-consistency/mzcompose.py
  test/postgres-consistency/mzcompose.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#28803 tests: fix SHOW CREATE for cloudtests
  misc/python/materialize/checks/all_checks/debezium.py
Labels: T-testing

#28746 feature benchmark: execution logic: improve readability
  misc/python/materialize/feature_benchmark/benchmark.py
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
Labels: T-testing

#28808 ci: annotate errors: disable upload if host name is unknown due to compilation errors
  bin/ci-annotate-errors
  misc/python/materialize/test_analytics/config/test_analytics_db_config.py
Labels: T-testing

#28807 output consistency: regex flag n
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28843 postgres consistency: ignore to account for different evaluation order
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28844 output consistency: enum characteristics
  misc/python/materialize/output_consistency/enum/enum_operation_param.py
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
Labels: T-testing

#28846 tests: fix github-26353.td
  test/testdrive/github-26353.td
Labels: T-testing

#28849 postgres consistency: fix entry point
  misc/python/materialize/postgres_consistency/postgres_consistency_test.py
Labels: T-testing

#28850 output consistency: improve error output
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_message.py
Labels: T-testing

#28853 postgres consistency: add pg_typeof ignore
  misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28862 tests: fix Debezium check in cloudtests
  misc/python/materialize/checks/all_checks/debezium.py
Labels: T-testing

#28385 output consistency: add table functions
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/string_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/table_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#28882 tests: fix Debezium check in cloudtests (2)
  misc/python/materialize/checks/all_checks/debezium.py
Labels: T-testing

#28934 feature flag consistency: fix flag definition
  misc/python/materialize/feature_flag_consistency/feature_flag/feature_flag.py
Labels: T-testing

#28970 output consistency: fix result comparator
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing

#28975 postgres consistency: extend ignore
  misc/python/materialize/output_consistency/input_data/operations/string_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28988 postgres consistency: add ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28948 Remove the `true and` from HIR join conditions
  src/sql/src/plan/query.rs
  test/sqllogictest/cte_lowering.slt
  test/sqllogictest/explain/view.slt
  test/sqllogictest/joins.slt
Labels: A-optimization, A-ADAPTER

#28994 postgres consistency: add ignore regarding IS NULL evaluation order
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29001 output consistency: expression matcher: limit characteristics to row selection
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29012 postgres consistency: add ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29061 feature benchmark: add unknown unit check
  misc/python/materialize/feature_benchmark/aggregation.py
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
Labels: T-testing

#29067 postgres consistency: adjust ignores
  misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#29103 version consistency: normalize table function error messages
  misc/python/materialize/version_consistency/validation/version_consistency_error_message_normalizer.py
Labels: T-testing

#29117 Fix join fusion when there are only constant singleton inputs
  src/transform/src/fusion/join.rs
  src/transform/tests/testdata/join-implementation
  test/sqllogictest/github-28174-29110.slt
Labels: A-optimization, A-CLUSTER

#29104 output consistency: refactoring: split file
  misc/python/materialize/output_consistency/data_value/data_column.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/enum/enum_constant.py
  misc/python/materialize/output_consistency/execution/evaluation_strategy.py
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/expression/constant_expression.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/query/query_result.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/selection/column_selection.py
  misc/python/materialize/output_consistency/selection/row_selection.py
  misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#29032 feature flag consistency: add flags for joins
  misc/python/materialize/feature_flag_consistency/input_data/feature_flag_configurations.py
Labels: T-testing

#29136 output consistency: query: add helper methods
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29144 postgres consistency: add ignore for unnest on array
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29156 Make `unpack_equivalences` sort each equivalence class by expression complexity
  src/transform/src/analysis/equivalences.rs
  src/transform/src/fusion/join.rs
  src/transform/tests/testdata/join-implementation
Labels: A-optimization, A-CLUSTER

#29276 Window function fusion
  src/adapter/src/optimize.rs
  src/compute-types/src/plan/reduce.rs
  src/compute/src/render/reduce.rs
  src/expr/src/relation.proto
  src/expr/src/relation.rs
  src/expr/src/relation/func.rs
  src/expr/src/scalar/func/impls/record.rs
  src/repr/src/optimize.rs
  src/repr/src/scalar.rs
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/plan/transform_expr.rs
  src/sql/src/session/vars/definitions.rs
  test/sqllogictest/window_funcs.slt
Labels: A-optimization, A-CLUSTER

#29287 Fix ignore nulls performance problem with long runs of nulls
  src/expr/src/relation/func.rs
  test/sqllogictest/window_funcs.slt
Labels: A-CLUSTER

#29298 `lag`/`lead` `IGNORE NULLS` refactoring and more tests
  src/expr/src/relation/func.rs
  test/sqllogictest/window_funcs.slt
Labels: A-CLUSTER
