Repository MaterializeInc/materialize, pull requests merged in 2024-04, with the labels that each got.

#26368 postgres consistency: remove ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26369 version consistency: add ignore
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#26372 bounded memory: allow parallelization
  misc/python/materialize/buildkite.py
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26370 bounded memory: validate lower memory configuration again
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26304 output consistency: add equality and inequality operators
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/boolean_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/equality_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26377 feature benchmark: add SwapSchema scenario
  misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#26381 bounded memory: parallelize
  ci/nightly/pipeline.template.yml
Labels: T-testing

#26391 ci: set timeout of bounded-memory to a reasonable value
  ci/nightly/pipeline.template.yml
Labels: T-testing

#26400 bounded memory: allow searching only for one memory limit
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26276 tests: bounded memory: add MySql scenarios
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26399 tests: disable fivetran dest in cloudtests
  misc/python/materialize/cloudtest/k8s/api/k8s_pod.py
  test/cloudtest/test_full_testdrive.py
Labels: T-testing

#26405 postgres consistency: extend ignore to capture <= and >= deviations
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26425 postgres consistency: fix ignore
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_message.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26428 tests: fix parallel-workload with 100 threads
  misc/python/materialize/data_ingest/executor.py
  misc/python/materialize/parallel_workload/action.py
  misc/python/materialize/parallel_workload/database.py
  misc/python/materialize/parallel_workload/executor.py
  misc/python/materialize/parallel_workload/parallel_workload.py
  misc/python/materialize/parallel_workload/worker.py
Labels: T-testing

#26451 tests: bounded memory: print used memory configuration
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26450 tests: bounded memory: stabilize pg-cdc-large-tx by increasing clusterd memory
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26421 *: remove the internal `idle_arrangement_merge_effort` option
  misc/python/materialize/mzcompose/__init__.py
  src/adapter/src/coord.rs
  src/adapter/src/coord/ddl.rs
  src/cluster-client/src/client.proto
  src/cluster-client/src/client.rs
  src/cluster/src/server.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/replica.rs
  src/controller/src/lib.rs
  src/sql/src/session/vars.rs
  src/sql/src/session/vars/definitions.rs
  src/storage-controller/src/rehydration.rs
Labels: T-proto

#26308 mzexplore: fixes and more commands
  misc/python/materialize/cli/mzexplore.py
  misc/python/materialize/mzexplore/__init__.py
  misc/python/materialize/mzexplore/analyze.py
  misc/python/materialize/mzexplore/catalog/s_items.sql
  misc/python/materialize/mzexplore/catalog/u_arrangement_sizes.sql
  misc/python/materialize/mzexplore/catalog/u_clone_dependencies.sql
  misc/python/materialize/mzexplore/catalog/u_items.sql
  misc/python/materialize/mzexplore/catalog/u_object_clusters.sql
  misc/python/materialize/mzexplore/clone.py
  misc/python/materialize/mzexplore/common.py
  misc/python/materialize/mzexplore/extract.py
  misc/python/materialize/mzexplore/sql.py
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  test/restart/mzcompose.py
Labels: A-optimization, A-ADAPTER, T-observability

#26478 frontegg-auth: avoid caching error responses
  src/environmentd/tests/auth.rs
  src/frontegg-auth/src/auth.rs
Labels: release-blocker

#26496 testdrive: apply timeout to query as well
  src/testdrive/src/action/sql.rs
Labels: T-testing

#26525 Expect matching parens around cluster options
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
Labels: C-bug, A-ADAPTER

#26519 testdrive: fix query timeout
  src/testdrive/src/action/sql.rs
Labels: T-testing

#26532 tests: increase timeout of cloudtests
  ci/test/pipeline.template.yml
Labels: T-testing

#26523 output consistency: support predefined queries
  misc/python/materialize/output_consistency/enum/enum_constant.py
  misc/python/materialize/output_consistency/execution/evaluation_strategy.py
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/input_data/test_input_data.py
  misc/python/materialize/output_consistency/input_data/test_input_operations.py
  misc/python/materialize/output_consistency/input_data/test_input_types.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/runner/test_runner.py
Labels: T-testing

#26530 feature benchmark: add scenarios ManySmallInserts and ManySmallUpdates
  misc/python/materialize/feature_benchmark/benchmark.py
  misc/python/materialize/feature_benchmark/scenario.py
  misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#26526 output consistency: text operations: support regex flags
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26500 postgres consistency: compare timezone definitions with postgres
  misc/python/materialize/output_consistency/input_data/operations/boolean_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
  misc/python/materialize/postgres_consistency/postgres_consistency_test.py
  test/sqllogictest/pg_catalog_timezone_abbrevs.slt
  test/sqllogictest/pg_catalog_timezone_names.slt
Labels: T-testing

#26559 buildkite insights: fix page offset
  misc/python/materialize/buildkite_insights/buildkite_api/generic_api.py
Labels: T-testing

#26401 REFRESH's automated cluster scheduling
  misc/python/materialize/mzcompose/__init__.py
  src/adapter/src/coord.rs
  src/adapter/src/coord/cluster_scheduling.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer/cluster.rs
  src/adapter/src/coord/timeline.rs
  src/adapter/src/metrics.rs
  src/catalog/src/memory/objects.rs
  src/sql/src/catalog.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/session/vars.rs
  src/sql/src/session/vars/definitions.rs
  src/sql/src/session/vars/value.rs
  test/cluster/mzcompose.py
  test/sqllogictest/materialized_views.slt
  test/testdrive/materialized-view-refresh-options.td
Labels: A-ADAPTER

#26558 bounded memory: update memory specs
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26588 postgres consistency: extend timezone ignores
  misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
Labels: T-testing

#26593 cloudtests: get rid of warning
  misc/python/materialize/mzcompose/test_result.py
Labels: T-testing

#26555 environmentd: detect malformed rows
  src/adapter/src/lib.rs
  src/adapter/src/util.rs
  src/environmentd/src/http/sql.rs
  src/pgwire/src/protocol.rs
Labels: release-blocker

#26599 tests: k8s node recovery: increase TD_TIMEOUT_FULL_RECOVERY
  test/cloudtest/node_recovery/test_k8s_node_recovery.py
Labels: T-testing

#26626 RBAC: Fix concurrent role drop check
  src/sql/src/rbac.rs
Labels: release-blocker

#25591 Fixed point iteration for Lattice analyses
  misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/create_view.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/explain.rs
  src/adapter/src/explain/mir.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/adapter/src/optimize.rs
  src/adapter/src/optimize/copy_to.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/expr/src/explain.rs
  src/expr/src/linear.rs
  src/repr/src/optimize.rs
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/session/vars/definitions.rs
  src/transform/src/analysis.rs
  src/transform/src/analysis/equivalences.rs
  src/transform/src/cse/relation_cse.rs
  src/transform/src/equivalence_propagation.rs
  src/transform/src/normalize_lets.rs
  src/transform/src/reduce_elision.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/test_transforms.rs
  src/transform/tests/test_transforms/threshold_elision.spec
  src/transform/tests/test_transforms/union_branch_cancellation.spec
  src/transform/tests/testdata/steps
  src/transform/tests/testdata/threshold_elision
  src/transform/tests/testdata/union_cancel
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text_redacted.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/ldbc_bi_eager.slt
  test/sqllogictest/outer_join_simplification.slt
  test/sqllogictest/transform/column_knowledge.slt
  test/sqllogictest/transform/demand.slt
  test/sqllogictest/transform/non_null_requirements.slt
  test/sqllogictest/transform/normalize_lets.slt
  test/sqllogictest/transform/reduce_elision.slt
  test/sqllogictest/transform/threshold_elision.slt
Labels: A-optimization, A-COMPUTE

#26616 REFRESH introspection: `mz_materialized_view_refresh_strategies` and `mz_cluster_schedules`
  doc/user/content/sql/system-catalog/mz_internal.md
  src/adapter/src/catalog/apply.rs
  src/adapter/src/catalog/builtin_table_updates.rs
  src/adapter/src/catalog/transact.rs
  src/catalog/src/builtin.rs
  src/environmentd/tests/testdata/http/ws
  src/expr/src/refresh_schedule.rs
  src/pgrepr-consts/src/oid.rs
  src/repr/src/adt/interval.rs
  test/sqllogictest/autogenerated/mz_internal.slt
  test/sqllogictest/information_schema_tables.slt
  test/sqllogictest/materialized_views.slt
  test/sqllogictest/oid.slt
  test/testdrive/catalog.td
Labels: A-ADAPTER

#26668 storage: fix edge-case panic in order-key upsert
  src/storage/src/render/upsert.rs
Labels: release-blocker

#26709 sql: restrict variadic left join lowering #26707
  ci/nightly/pipeline.template.yml
  src/sql/src/plan/lowering/variadic_left.rs
  test/rqg/Dockerfile
  test/rqg/datasets/star_schema.sql
  test/rqg/grammars/left_join_stacks.yy
  test/rqg/mzcompose.py
  test/sqllogictest/github-26707.slt
Labels: C-bug, T-correctness, A-optimization, A-COMPUTE

#26756 rqg: evolve `left-join-stacks` workload grammar (v3)
  test/rqg/datasets/star_schema.sql
  test/rqg/grammars/left_join_stacks.yy
Labels: T-testing, A-optimization, A-COMPUTE

#26780 Change the Controller timestamp bounds to allow only Datum conversion
  src/controller/src/lib.rs
  src/storage-controller/src/lib.rs
Labels: A-STORAGE, A-COMPUTE

#26783 Reorganize controller timestamp trait bounds
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/controller/replica.rs
  src/compute-client/src/controller/sequential_hydration.rs
  src/compute-client/src/service.rs
  src/controller/src/clusters.rs
  src/controller/src/lib.rs
Labels: A-STORAGE, A-COMPUTE

#26835 postgres consistency: add ignore for LIMIT 0
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26833 tests: parallel workload: add ignore
  misc/python/materialize/parallel_workload/action.py
Labels: T-testing

#26834 feature benchmark: restore ancestor-override for older version
  misc/python/materialize/version_ancestor_overrides.py
Labels: T-testing

#26842 output consistency: add initcap function
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
Labels: T-testing

#26847 postgres consistency: fix ignore entry
  misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
Labels: T-testing
