Repository MaterializeInc/materialize, pull requests merged in 2024-06, with the labels that each got.

#27394 tests: Temporarily disable failing Kafka RTR test
  test/kafka-rtr/simple/verify-rtr.td
Labels: T-recency

#27402 output consistency: improve cast type infos
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/return_specs/other_return_spec.py
  misc/python/materialize/output_consistency/input_data/special/data_type_enum_param.py
Labels: T-testing

#27438 feature benchmark: provide scale to ancestor overrides
  misc/python/materialize/version_ancestor_overrides.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#27461 tests: mysql: remove workflow_switch_to_lagging_replica
  test/mysql-cdc-resumption/mzcompose.py
Labels: T-testing

#26173 mzexplore: analysis of variadic outer joins
  misc/mzexplore/variadic_outer_joins.jq
Labels: A-monitoring, A-optimization, A-COMPUTE, T-observability

#27488 postgres consistency: improve ignores, add likely needed ones
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27487 New builtin indexed views for Metabase
  doc/user/content/sql/system-catalog/mz_internal.md
  src/catalog/src/builtin.rs
  src/environmentd/tests/testdata/http/ws
  src/pgrepr-consts/src/oid.rs
  test/sqllogictest/autogenerated/mz_internal.slt
  test/sqllogictest/cluster.slt
  test/sqllogictest/information_schema_tables.slt
  test/sqllogictest/mz_catalog_server_index_accounting.slt
  test/sqllogictest/oid.slt
  test/testdrive/catalog.td
  test/testdrive/indexes.td
  test/testdrive/mz-arrangement-sharing.td
Labels: A-ADAPTER

#27515 Re-enable `test-refresh-mv-restart` and `test-index-source-stuck`
  test/cluster/index-source-stuck/run.td
  test/cluster/mzcompose.py
Labels: T-testing

#27530 Add keys to many builtin tables
  src/catalog/src/builtin.rs
  src/environmentd/tests/testdata/http/ws
  test/sqllogictest/transform/predicate_pushdown.slt
  test/testdrive/mz-arrangement-sharing.td
  test/testdrive/pg-catalog.td
Labels: A-ADAPTER

#27547 Fix Delta join 1st input index usage annotation
  src/compute-types/src/plan/join/delta_join.rs
  src/repr/src/explain.rs
  src/transform/src/dataflow.rs
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/ldbc_bi_eager.slt
  test/sqllogictest/mzcompose.py
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/sqllogictest/tpch_select.slt
Labels: A-optimization, A-CLUSTER

#27635 postgres consistency: extend and adjust ignores
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27553 storage/sink/kafka: Allow configuring auto created topic for Kafka sinks
  doc/user/content/releases/v0.103.md
  doc/user/content/releases/v0.104.md
  doc/user/content/sql/create-sink/kafka.md
  misc/python/materialize/checks/all_checks/sink.py
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/ddl.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
  src/sql/src/kafka_util.rs
  src/sql/src/names.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/with_options.rs
  src/storage-client/src/sink.rs
  src/storage-types/src/sinks.proto
  src/storage-types/src/sinks.rs
  src/storage/src/sink/kafka.rs
  src/testdrive/src/action/kafka/verify_topic.rs
  src/walkabout/src/gen.rs
  test/testdrive/kafka-sink-errors.td
  test/testdrive/kafka-sink-topic-config.td
Labels: A-storage, A-CLUSTER

#27669 adapter: remove already applied loadgen source migration
  misc/python/materialize/checks/all_checks/load_generator.py
  src/adapter/src/catalog/migrate.rs
Labels: release-blocker

#27725 ci: re-enable one automatic retry for k8s node recovery tests
  ci/nightly/pipeline.template.yml
Labels: T-testing

#27726 feature benchmark: improve code readability, expose wallclock unit
  misc/python/materialize/feature_benchmark/benchmark.py
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/measurement.py
  misc/python/materialize/feature_benchmark/measurement_source.py
  misc/python/materialize/feature_benchmark/scenario.py
  misc/python/materialize/feature_benchmark/scenarios/optbench.py
Labels: T-testing

#27325 docs: Fix grammar of mat view WITH options
  doc/user/content/sql/create-materialized-view.md
  doc/user/layouts/partials/sql-grammar/create-materialized-view.svg
  doc/user/layouts/partials/sql-grammar/with-options-materialized-view.svg
  doc/user/sql-grammar/sql-grammar.bnf
Labels: A-docs

#27747 tests: disable smoketest_packed_numeric_roundtrips in miri
  src/repr/src/adt/numeric.rs
Labels: T-testing

#27472 optimizer: make cardinality estimates fully concrete
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/create_view.rs
  src/adapter/src/explain.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/expr/src/explain.rs
  src/repr/src/optimize.rs
  src/sql/src/session/vars/definitions.rs
  src/transform/src/analysis.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/symbolic.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/test_transforms.rs
  test/bounded-memory/mzcompose.py
  test/sqllogictest/cardinality.slt
  test/sqllogictest/github-25769.slt
Labels: A-optimization

#27766 Accept OFFSET and LIMIT/FETCH in any order
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/select
  test/sqllogictest/cockroach/limit.slt
  test/sqllogictest/limit_expr.slt
  test/sqllogictest/order_by.slt
Labels: A-ADAPTER

#27507 storage/mysql: Use a separate initial_gtid_set per subsource to allow alter source workflows
  src/adapter/src/coord/sequencer/inner.rs
  src/buf.yaml
  src/proto/src/lib.rs
  src/sql/src/pure.rs
  src/storage-types/src/sinks.proto
  src/storage-types/src/sources/mysql.proto
  src/storage-types/src/sources/mysql.rs
  src/storage/src/source/mysql.rs
  src/storage/src/source/mysql/replication.rs
  src/storage/src/source/mysql/snapshot.rs
  test/mysql-cdc/alter-source.td
Labels: A-storage, T-mysql, A-CLUSTER

#27769 feature benchmark: fix ignore entry
  misc/python/materialize/version_ancestor_overrides.py
Labels: T-testing

#27770 cargo tests: use higher concurrency
  ci/test/cargo-test/mzcompose.py
Labels: T-testing

#27777 tests: extend platform check with limit and offset
  misc/python/materialize/checks/all_checks/top_k.py
Labels: T-testing

#27789 tests: mysql-cdc: test add sub source after corruption
  test/mysql-cdc-resumption/alter-source-add-subsource.td
  test/mysql-cdc-resumption/mzcompose.py
  test/mysql-cdc-resumption/populate-table-t3.td
  test/mysql-cdc-resumption/verify-t3.td
Labels: T-testing

#27873 Fix null equality handling in ReductionPushdown
  src/transform/src/reduction_pushdown.rs
  src/transform/tests/test_transforms/reduction_pushdown.spec
  test/sqllogictest/transform/reduction_pushdown.slt
Labels: A-optimization, A-CLUSTER

#27793 feature benchmark: add ignore entry for PR#26807
  misc/python/materialize/version_ancestor_overrides.py
Labels: T-testing

#27727 tests: pg-cdc: resume after silent connection drop
  test/pg-cdc/mzcompose.py
  test/pg-cdc/override/silent-connection-drop-part-1.td
  test/pg-cdc/override/silent-connection-drop-part-2.td
Labels: T-testing

#24931 deps: upgrade to librdkafka v2.4.0
  Cargo.lock
  misc/cargo-vet/audits.toml
  test/cloudtest/test_secrets.py
  test/kafka-auth/test-kafka-sasl-plaintext.td
  test/kafka-auth/test-kafka-sasl-ssl.td
  test/kafka-auth/test-kafka-ssl.td
  test/testdrive/connection-alter.td
Labels: A-storage
