Repository MaterializeInc/materialize, pull requests merged in 2024-03, with the labels that each got.

#25657 storage/statistics: fix rehydration latency being multiplied by 1000
  src/storage-client/src/statistics.rs
  test/cluster/gh-25633/01-create-source.td
  test/cluster/gh-25633/02-after-environmentd-restart.td
  test/cluster/mzcompose.py
Labels: release-blocker

#25645 tests: mysql-cdc versions: run mysql-cdc with different versions
  ci/nightly/pipeline.template.yml
  misc/python/materialize/mysql_util.py
  test/mysql-cdc/mzcompose.py
  test/mysql-matrix/mzcompose
  test/mysql-matrix/mzcompose.py
Labels: T-testing

#25638 testdrive: introduce skip-end
  doc/developer/testdrive.md
  src/testdrive/src/action.rs
  src/testdrive/src/action/skip_end.rs
  src/testdrive/src/action/skip_if.rs
  src/testdrive/src/lib.rs
Labels: T-testing

#25668 tests: mysql: remove ignore
  test/mysql-cdc/alter-table-after-source.td
Labels: T-testing

#25586 explain,sql: support `EXPLAIN ... VIEW` variants
  src/adapter/src/coord/sequencer/inner.rs
  src/repr/src/explain/tracing.rs
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/explain
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/rbac.rs
  test/sqllogictest/explain/bad_explain_statements.slt
Labels: A-ADAPTER

#25680 tests: mysql-cdc: SSL tests
  test/mysql-cdc/mysql-cdc-ssl.td
Labels: T-testing

#25671 output consistency: special date values
  misc/python/materialize/output_consistency/input_data/types/date_time_types_provider.py
  misc/python/materialize/output_consistency/input_data/values/date_time_values_provider.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#25609 cloudtests: enable MySql tests in upgrade test
  ci/nightly/pipeline.template.yml
  misc/python/materialize/cloudtest/app/materialize_application.py
  misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
  misc/python/materialize/cloudtest/k8s/mysql.py
  test/cloudtest/test_upgrade.py
  test/mysql/Dockerfile
  test/mysql/mzbuild.yml
Labels: T-testing

#25688 tests: mysql-cdc-ssl: cleanup
  test/mysql-cdc/mysql-cdc-ssl.td
Labels: T-testing

#25690 tests: pg-cdc-resumption: refactor default workflow to include backup-restore
  test/pg-cdc-resumption/mzcompose.py
Labels: T-testing

#25398 doc/user update webhook quickstart
  doc/user/content/ingest-data/webhook-quickstart.md
Labels: A-docs

#25716 tests: testdrive: remove nested skip-if
  test/testdrive/catalog.td
Labels: T-testing

#25717 tests: mysql-cdc: adapt to truncate behavior
  test/mysql-cdc/alter-table-after-source.td
Labels: T-testing

#25718 tests: persist catalog migration: use versions from docs
  misc/python/materialize/version_list.py
  test/persist-catalog-migration/mzcompose.py
Labels: T-testing

#25775 tests: mysql-cdc: empty table
  test/mysql-cdc/empty-table.td
Labels: T-testing

#25782 tests: mysql-cdc: further schema changes
  test/mysql-cdc/25-schema-changes.td
Labels: T-testing

#25787 storage: correctly initialize source statistics on ALTER SOURCE ADD SUBSOURCE
  src/storage-controller/src/lib.rs
  test/pg-cdc/statistics.td
Labels: release-blocker

#25810 feature benchmark: change ancestor override to merge commit
  misc/python/materialize/version_ancestor_overrides.py
Labels: T-testing

#25799 adapter: delay subscribe read hold releases
  src/adapter/src/coord/sequencer/inner/subscribe.rs
Labels: release-blocker

#25584 compute: use a `FlatPlan` in the controller and rendering
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/protocol/command.rs
  src/compute-types/build.rs
  src/compute-types/src/dataflows.proto
  src/compute-types/src/dataflows.rs
  src/compute-types/src/plan.proto
  src/compute-types/src/plan/flat_plan.proto
  src/compute-types/src/plan/flat_plan.rs
  src/compute-types/src/plan/mod.rs
  src/compute/src/compute_state.rs
  src/compute/src/render/mod.rs
  test/sqllogictest/github-25545.slt
  test/sqllogictest/mzcompose.py
Labels: T-proto

#25751 storage: add source statistics for webhooks
  src/adapter/src/coord/command_handler.rs
  src/adapter/src/webhook.rs
  src/environmentd/src/http/webhook.rs
  src/storage-client/src/controller.rs
  src/storage-client/src/statistics.rs
  src/storage-controller/src/lib.rs
  src/storage-controller/src/statistics.rs
  test/cluster/storage/01-create-sources.td
  test/cluster/storage/02-after-environmentd-restart.td
  test/testdrive/webhook-statistics.td
Labels: release-blocker

#25842 storage: compact committed upper stream if source is slow to report it
  src/storage/src/metrics/source.rs
  src/storage/src/source/reclock.rs
  src/storage/src/source/source_reader_pipeline.rs
Labels: release-blocker

#25885 tests: mysql-cdc: handle closed issues
  test/mysql-cdc/alter-source.td
  test/mysql-cdc/mysql-cdc.td
  test/mysql-cdc/types-enum.td
Labels: T-testing

#25811 transform: `Fixpoint` improvements
  src/expr/src/relation/mod.rs
  src/transform/src/lib.rs
  src/transform/tests/testdata/keys
  src/transform/tests/testdata/steps
Labels: A-optimization, A-COMPUTE

#25812 optimize: automate `OptimizerFeatures` plumbing
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/create_view.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/coord/sequencer/inner/subscribe.rs
  src/adapter/src/optimize/copy_to.rs
  src/adapter/src/optimize/dataflows.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/compute-types/src/plan/lowering.rs
  src/compute-types/src/plan/mod.rs
  src/repr/src/explain/mod.rs
  src/repr/src/optimize.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/session/vars/definitions.rs
  src/transform/src/dataflow.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/test_transforms.rs
Labels: A-optimization, A-COMPUTE

#25628 transform: plumb through `OptimizerFeatures`
  src/adapter/src/optimize/copy_to.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/adapter/src/optimize/view.rs
  src/transform/src/dataflow.rs
  src/transform/src/fusion/filter.rs
  src/transform/src/join_implementation.rs
  src/transform/src/lib.rs
  src/transform/src/literal_constraints.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/src/typecheck.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/test_transforms.rs
Labels: A-optimization, A-COMPUTE

#25916 output consistency: reorder statements for reproduction
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
Labels: T-testing

#25922 feature benchmark: add ignore to account for equivalence propagation
  misc/python/materialize/version_ancestor_overrides.py
Labels: T-testing

#25925 feature benchmark: scenario-specific ancestor overrides
  misc/python/materialize/version_ancestor_overrides.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#25938 postgres consistency: add ignore for decode with special whitespace chars
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#25955 REFRESH tests with restarts
  test/cluster/mzcompose.py
  test/testdrive/materialized-view-refresh-options.td
Labels: A-COMPUTE

#25960 postgres consistency: add ignore for min/max on time
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#25961 tests: cluster isolation: increase sleep duration
  test/cluster-isolation/mzcompose.py
Labels: T-testing

#25958 output-consistency: validate content type explicitly
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_message.py
Labels: T-testing

#25929 compute: rename `NodeId` to `LirId`
  doc/user/content/sql/system-catalog/mz_internal.md
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/protocol/response.rs
  src/compute-types/src/dataflows.rs
  src/compute-types/src/explain/text.rs
  src/compute-types/src/plan/flat_plan.rs
  src/compute-types/src/plan/interpret/api.rs
  src/compute-types/src/plan/lowering.rs
  src/compute-types/src/plan/mod.rs
  src/compute/src/compute_state.rs
  src/compute/src/render/mod.rs
  test/sqllogictest/explain/physical_plan_as_json.slt
Labels: T-proto

#25964 tests: RQG: use Postgres 16.2, re-enable test
  ci/nightly/pipeline.template.yml
  test/rqg/mzcompose.py
Labels: T-testing

#25763 tests: mysql-cdc-resumption: purge entries from bin-log
  test/mysql-cdc-resumption/mzcompose.py
Labels: T-testing

#25973 ci: fix shellcheck version check to support 0.10.0
  ci/test/lint-main/before/can-lint.sh
Labels: C-bug, A-infra

#25978 tests: materialized-view-refresh-options.td: add sleep
  test/testdrive/materialized-view-refresh-options.td
Labels: T-testing

#25984 Revert "tests: materialized-view-refresh-options.td: add sleep (#25978)"
  test/testdrive/materialized-view-refresh-options.td
Labels: T-testing

#26013 Use less memory in `materialized-view-refresh-options.td`
  test/testdrive/materialized-view-refresh-options.td
Labels: T-testing

#26023 tests: mysql-cdc: enum reordering
  test/mysql-cdc/types-enum.td
Labels: T-testing

#26021 sql: Refactor to statement logging history
  src/adapter/src/catalog/open.rs
  src/adapter/src/client.rs
  src/adapter/src/coord/sql.rs
  src/adapter/src/coord/statement_logging.rs
  src/adapter/src/session.rs
  src/catalog/src/durable/transaction.rs
  src/environmentd/tests/server.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/ast/display.rs
  test/cluster/statement-logging/statement-logging.td
Labels: release-blocker

#26027 storage: take `as_of` into account when reclocking committed upper
  src/storage/src/source/source_reader_pipeline.rs
Labels: release-blocker

#26045 tests: mysql: args definition
  misc/python/materialize/mzcompose/services/mysql.py
  test/mysql-cdc-resumption/mzcompose.py
Labels: T-testing

#26065 feature benchmark: add ignore for store flatmap execution
  misc/python/materialize/version_ancestor_overrides.py
Labels: T-testing

#26051 tests: do not use v0.92.0 (in upgrade checks)
  misc/python/materialize/version_list.py
  test/legacy-upgrade/mzcompose.py
Labels: T-testing

#26018 tests: mysql-cdc-resumption: rollback in MySQL
  test/mysql-cdc-resumption/mzcompose.py
Labels: T-testing

#26103 tests: mysql-cdc: source changes
  test/mysql-cdc/alter-column-irrelevant.td
  test/mysql-cdc/mysql-cdc.td
Labels: T-testing

#26044 tests: mysql-cdc: some further special tables
  test/mysql-cdc/move-table.td
  test/mysql-cdc/table-in-mysql-schema.td
  test/mysql-cdc/temporary-tables.td
  test/mysql-cdc/views.td
Labels: T-testing

#26129 tests: mysql concurrent inserts: collapse log
  test/mysql-cdc/mzcompose.py
Labels: T-testing

#26112 tests: k8s node recovery: increase timeout, improve logging
  misc/python/materialize/mzcompose/test_result.py
  test/cloudtest/node_recovery/test_k8s_node_recovery.py
  test/output-consistency/mzcompose.py
  test/postgres-consistency/mzcompose.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#26055 compute: controller-controlled sequential hydration
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/metrics.rs
  src/compute-client/src/protocol.rs
  src/compute-client/src/protocol/command.proto
  src/compute-client/src/protocol/command.rs
  src/compute-client/src/protocol/history.rs
  src/compute-types/src/dyncfgs.rs
  src/compute/src/compute_state.rs
  test/testdrive/sequential-hydration.td
Labels: T-proto

#25972 mzexplore: jq queries for looking at extracted plans
  misc/mzexplore/README.md
  misc/mzexplore/defs.jq
  misc/mzexplore/filters.jq
  misc/mzexplore/leftjoins.jq
Labels: A-optimization, A-COMPUTE, T-observability

#26168 output consistency: error reporting: minor
  misc/python/materialize/output_consistency/validation/validation_outcome.py
Labels: T-testing

#26159 output consistency: LIKE / ILIKE: fix operator specification
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
Labels: T-testing

#26189 storage: fix dyncfg implementation
  src/storage-controller/src/lib.rs
  src/storage/src/storage_state.rs
Labels: release-blocker

#26183 Fix ILIKE with multiprocess clusters
  Cargo.lock
  misc/cargo-vet/config.toml
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  src/expr/Cargo.toml
  src/expr/src/scalar/like_pattern.rs
  src/repr/src/adt/regex.proto
  src/repr/src/adt/regex.rs
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/like.slt
Labels: A-COMPUTE

#26191 Fix newline handling in regexes
  src/expr/src/scalar/like_pattern.rs
  src/repr/src/adt/regex.rs
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/regex.slt
Labels: A-COMPUTE

#26194 storage: fix dyncfg updates for future clusters
  src/adapter/src/flags.rs
  src/storage-controller/src/lib.rs
  src/storage-types/src/configuration.rs
  src/storage-types/src/parameters.rs
  src/storage/src/storage_state.rs
Labels: release-blocker

#26210 version consistency: add ignores
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#26167 output consistency: fix validation
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing

#26211 version consistency: test both DFR and CTF
  ci/nightly/pipeline.template.yml
  test/version-consistency/mzcompose.py
Labels: T-testing

#26212 postgres consistency: remove ignore for regex with linebreaks
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#25998 Parsing for REFRESH's automated cluster scheduling
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
  src/sql/src/names.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/with_options.rs
  test/sqllogictest/cluster.slt
  test/sqllogictest/materialized_views.slt
Labels: A-ADAPTER

#26241 tests: mysql-cdc: transactions
  test/mysql-cdc/transactions-multi-conn.td
  test/mysql-cdc/transactions.td
Labels: T-testing

#26255 tests: pg-cdc: transactions
  test/pg-cdc/transactions-multi-conn.td
  test/pg-cdc/transactions.td
Labels: T-testing

#26261 ci: move mysql-cdc matrix to release-qualification
  ci/nightly/pipeline.template.yml
  ci/release-qualification/pipeline.template.yml
  ci/test/pipeline.template.yml
Labels: T-testing

#26269 output-consistency: support OFFSET and LIMIT
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/selection/randomized_picker.py
Labels: T-testing

#26296 postgres consistency: add ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26305 output consistency: prioritize value check over type check
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing

#26311 bounded memory: memory search
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26310 postgres consistency: optimize and add ignores
  misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#26322 bounded memory: add testdrive time limit
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26287 tests: bounded memory: add pg-cdc-large-tx
  test/bounded-memory/mzcompose.py
Labels: T-testing

#26289 sql: expand `variadic_left::decompose_equations` coverage
  .github/CODEOWNERS
  src/sql/src/plan/lowering/variadic_left.rs
Labels: A-optimization, A-COMPUTE

#26346 catalog: give default cluster disk if cc size
  src/catalog/src/durable/initialize.rs
Labels: release-blocker
