Repository MaterializeInc/materialize, pull requests merged in 2024-10, with the labels that each got.

#29752 tests: checks in parallel
  ci/nightly/pipeline.template.yml
  misc/python/materialize/checks/all_checks/optimizer_notices.py
  misc/python/materialize/checks/all_checks/owners.py
  misc/python/materialize/checks/all_checks/statement_logging.py
  misc/python/materialize/checks/mzcompose_actions.py
Labels: T-testing

#29804 tests: re-enable files
  test/debezium/postgres/24-types-money.td
  test/debezium/postgres/40-truncate-table.td
  test/persistence/kafka-sources/kafka-counters-after.td
  test/persistence/kafka-sources/kafka-counters-before.td
Labels: T-testing

#29875 feature flag consistency: add ignore regarding floating ops with enable_eager_delta_joins
  misc/python/materialize/feature_flag_consistency/ignore_filter/feature_flag_consistency_ignore_filter.py
  misc/python/materialize/output_consistency/query/query_result.py
  misc/python/materialize/output_consistency/query/query_template.py
Labels: T-testing

#29900 output consistency: add ignore regarding evaluation order
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
Labels: T-testing

#29897 postgres consistency: add ignore for IS NULL on record with NULL value
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29938 output consistency: refactor enum constant
  misc/python/materialize/output_consistency/enum/enum_constant.py
  misc/python/materialize/output_consistency/expression/constant_expression.py
  misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
Labels: T-testing

#29941 postgres consistency: more lenient number comparison
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#29942 output consistency: expressions: source may be None
  misc/python/materialize/output_consistency/data_value/data_column.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/expression/constant_expression.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
Labels: T-testing

#29936 Do the nullability tweaking in `EquivalenceClasses::minimize` only once
  src/expr/src/scalar.rs
  src/transform/src/analysis/equivalences.rs
Labels: A-optimization, A-CLUSTER

#29943 Asymptotically faster class unification in `EquivalenceClasses::minimize_once`
  src/transform/src/analysis/equivalences.rs
Labels: A-optimization, A-CLUSTER

#29955 output consistency: improve error extraction
  misc/python/materialize/output_consistency/execution/sql_executor.py
Labels: T-testing

#29974 postgres-consistency: add ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29939 output consistency: fix ambiguous row index
  misc/python/materialize/output_consistency/data_value/data_column.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/expression/constant_expression.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/row_indices_expression.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/row_indices_param.py
  misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
Labels: T-testing

#29982 output consistency: print used ignore entries
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/output/output_printer.py
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/status/test_summary.py
Labels: T-testing

#29994 output consistency: fix value ordering error
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing

#28931 tests: add advent-of-code 2023 puzzles
  test/sqllogictest/advent-of-code/2023/README.md
  test/sqllogictest/advent-of-code/2023/aoc_1201.slt
  test/sqllogictest/advent-of-code/2023/aoc_1202.slt
  test/sqllogictest/advent-of-code/2023/aoc_1203.slt
  test/sqllogictest/advent-of-code/2023/aoc_1204.slt
  test/sqllogictest/advent-of-code/2023/aoc_1205.slt
  test/sqllogictest/advent-of-code/2023/aoc_1206.slt
  test/sqllogictest/advent-of-code/2023/aoc_1207.slt
  test/sqllogictest/advent-of-code/2023/aoc_1208.slt
  test/sqllogictest/advent-of-code/2023/aoc_1209.slt
  test/sqllogictest/advent-of-code/2023/aoc_1210.slt
  test/sqllogictest/advent-of-code/2023/aoc_1211.slt
  test/sqllogictest/advent-of-code/2023/aoc_1212.slt
  test/sqllogictest/advent-of-code/2023/aoc_1213.slt
  test/sqllogictest/advent-of-code/2023/aoc_1214.slt
  test/sqllogictest/advent-of-code/2023/aoc_1215.slt
  test/sqllogictest/advent-of-code/2023/aoc_1216.slt
  test/sqllogictest/advent-of-code/2023/aoc_1217.slt
  test/sqllogictest/advent-of-code/2023/aoc_1218.slt
  test/sqllogictest/advent-of-code/2023/aoc_1219.slt
  test/sqllogictest/advent-of-code/2023/aoc_1220.slt
  test/sqllogictest/advent-of-code/2023/aoc_1221.slt
  test/sqllogictest/advent-of-code/2023/aoc_1222.slt
  test/sqllogictest/advent-of-code/2023/aoc_1223.slt
  test/sqllogictest/advent-of-code/2023/aoc_1224.slt
  test/sqllogictest/advent-of-code/2023/aoc_1225.slt
  test/sqllogictest/mzcompose.py
Labels: T-testing

#30029 postgres consistency: extend ignore regarding jsonb object generation
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#30062 postgres consistency: improve function definition regarding sort order
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
Labels: T-testing

#29817 tests: create table from kafka source: zippy
  misc/python/materialize/zippy/debezium_actions.py
  misc/python/materialize/zippy/debezium_capabilities.py
  misc/python/materialize/zippy/mysql_cdc_capabilities.py
  misc/python/materialize/zippy/pg_cdc_capabilities.py
  misc/python/materialize/zippy/sink_actions.py
  misc/python/materialize/zippy/source_actions.py
  misc/python/materialize/zippy/source_capabilities.py
  misc/python/materialize/zippy/table_capabilities.py
  misc/python/materialize/zippy/view_actions.py
  misc/python/materialize/zippy/view_capabilities.py
  misc/python/materialize/zippy/watermarked_object_capabilities.py
Labels: T-testing

#29802 tests: create table from kafka source: platform checks
  misc/python/materialize/checks/all_checks/alter_connection.py
  misc/python/materialize/checks/all_checks/alter_index.py
  misc/python/materialize/checks/all_checks/debezium.py
  misc/python/materialize/checks/all_checks/error.py
  misc/python/materialize/checks/all_checks/identifiers.py
  misc/python/materialize/checks/all_checks/json_source.py
  misc/python/materialize/checks/all_checks/kafka_formats.py
  misc/python/materialize/checks/all_checks/kafka_protocols.py
  misc/python/materialize/checks/all_checks/multiple_partitions.py
  misc/python/materialize/checks/all_checks/ranges.py
  misc/python/materialize/checks/all_checks/rename_source.py
  misc/python/materialize/checks/all_checks/retain_history.py
  misc/python/materialize/checks/all_checks/sink.py
  misc/python/materialize/checks/all_checks/ssh.py
  misc/python/materialize/checks/all_checks/top_k.py
  misc/python/materialize/checks/all_checks/upsert.py
  misc/python/materialize/checks/all_checks/upsert_enrich.py
  misc/python/materialize/checks/all_checks/upsert_many_columns.py
  misc/python/materialize/checks/all_checks/upsert_many_rows.py
  misc/python/materialize/checks/all_checks/upsert_many_updates.py
  misc/python/materialize/checks/all_checks/upsert_shrink_grow.py
  misc/python/materialize/checks/all_checks/upsert_unordered_key.py
  misc/python/materialize/checks/all_checks/upsert_wide.py
Labels: T-testing

#30051 tests: improve bounded memory search
  test/bounded-memory/mzcompose.py
Labels: T-testing

#30126 tests: disable durable_cache in Miri
  src/durable-cache/src/lib.rs
Labels: T-testing

#29803 tests: create table from kafka source: other checks
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
  misc/python/materialize/feature_benchmark/scenarios/concurrency.py
  misc/python/materialize/feature_benchmark/scenarios/subscribe.py
  misc/python/materialize/parallel_benchmark/scenarios.py
  test/0dt/mzcompose.py
  test/bounded-memory/mzcompose.py
  test/cloudtest/test_compute_shared_fate.py
  test/cloudtest/test_crash.py
  test/cloudtest/test_disk.py
  test/cloudtest/test_smoke.py
  test/cloudtest/test_storage_shared_fate.py
  test/cluster-isolation/mzcompose.py
  test/limits/mzcompose.py
  test/pubsub-disruption/mzcompose.py
  test/restart/mzcompose.py
  test/source-sink-errors/mzcompose.py
  test/storage-usage/mzcompose.py
Labels: T-testing

#30128 tests: bounded memory: fix
  test/bounded-memory/mzcompose.py
Labels: T-testing

#30130 tests: testdrive w/ old source syntax: sync tests
  test/testdrive-old-kafka-src-syntax/alter-sink.td
  test/testdrive-old-kafka-src-syntax/catalog.td
  test/testdrive-old-kafka-src-syntax/coord-read-holds.td
  test/testdrive-old-kafka-src-syntax/distinct-arrangements.td
  test/testdrive-old-kafka-src-syntax/indexes.td
  test/testdrive-old-kafka-src-syntax/kafka-debezium-sources-compound-key.td
  test/testdrive-old-kafka-src-syntax/kafka-sink-partition-by.td
  test/testdrive-old-kafka-src-syntax/load-generator.td
  test/testdrive-old-kafka-src-syntax/materialization-lag.td
  test/testdrive-old-kafka-src-syntax/replica-expiration.td
  test/testdrive-old-kafka-src-syntax/source-statistics.td
  test/testdrive-old-kafka-src-syntax/source-tables.td
Labels: T-testing

#30060 tests: create table from kafka source: other formats
  misc/python/materialize/checks/all_checks/kafka_formats.py
  test/0dt/mzcompose.py
  test/kafka-resumption/sink-networking/setup.td
  test/kafka-resumption/sink-queue-full/during.td
  test/kafka-resumption/sink-queue-full/setup.td
  test/kafka-rtr/mzcompose.py
  test/kafka-rtr/resumption/mz-setup.td
  test/kafka-rtr/simple/mz-setup.td
  test/kafka-rtr/simple/verify-rtr.td
  test/rtr-combined/rtr/mz-setup.td
  test/testdrive/audit-log.td
  test/testdrive/connection-alter.td
  test/testdrive/connection-create-drop.td
  test/testdrive/github-12005.td
  test/testdrive/kafka-data-formats.td
  test/testdrive/kafka-exactly-once-sink.td
  test/testdrive/kafka-include-key-sources.td
  test/testdrive/kafka-sinks.td
  test/testdrive/regex-sources.td
  test/testdrive/source-statistics.td
Labels: T-testing

#30152 tests: continual tasks: fix activation
  misc/python/materialize/mzcompose/__init__.py
Labels: T-testing

#30174 postgres consistency: extend ignore entry
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#30179 tests: fix pretty.slt
  test/sqllogictest/pretty.slt
Labels: T-testing

#30180 tests: create table from source: minor adjustments
  test/testdrive/mz-sources.td
  test/testdrive/primary-key-optimizations.td
Labels: T-testing

#30196 postgres consistency: add ignore for evaluation shortcut
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#30103 Window aggregation fusion
  src/adapter/src/optimize.rs
  src/compute-types/src/plan/reduce.rs
  src/compute/src/render/reduce.rs
  src/expr/src/relation.proto
  src/expr/src/relation.rs
  src/expr/src/relation/func.rs
  src/repr/src/optimize.rs
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/plan/transform_expr.rs
  src/sql/src/session/vars/definitions.rs
  test/sqllogictest/transform/fold_constants.slt
  test/sqllogictest/window_funcs.slt
Labels: A-optimization, A-ADAPTER, A-CLUSTER

#30210 bounded memory: improve search
  ci/nightly/pipeline.template.yml
  test/bounded-memory/mzcompose.py
Labels: T-testing

#30251 bounded memory: refactoring: search as separate workflow
  ci/nightly/pipeline.template.yml
  test/bounded-memory/mzcompose.py
Labels: T-testing

#30262 test analytics: introduce dummy connector and use it in bounded-memory minimization search
  misc/python/materialize/test_analytics/config/test_analytics_db_config.py
  misc/python/materialize/test_analytics/connector/test_analytics_connector.py
  misc/python/materialize/test_analytics/test_analytics_db.py
  test/bounded-memory/mzcompose.py
Labels: T-testing
