Repository MaterializeInc/materialize, pull requests merged in 2024-09, with the labels that each got.

#29336 Downgrade the `soft_panic` in `drop_plans_and_metainfos` to an error log
  src/adapter/src/catalog.rs
Labels: A-ADAPTER

#29348 output consistency: do not fail on "possibly invalid operation specification"
  misc/python/materialize/cli/ci_annotate_errors.py
Labels: T-testing

#29349 output consistency: reproduction printer: do not remove data sources that are unreferenced but needed
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
Labels: T-testing

#29351 postgres consistency: add ignores
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#29124 scalability framework: refactoring / cleanup
  misc/python/materialize/scalability/config/benchmark_config.py
  misc/python/materialize/scalability/df/df_totals.py
  misc/python/materialize/scalability/endpoint/endpoint.py
  misc/python/materialize/scalability/endpoint/endpoints.py
  misc/python/materialize/scalability/executor/benchmark_executor.py
  misc/python/materialize/scalability/operation/operation_data.py
  misc/python/materialize/scalability/operation/operations/operations.py
  misc/python/materialize/scalability/operation/operations_test.py
  misc/python/materialize/scalability/operation/scalability_operation.py
  misc/python/materialize/scalability/plot/plot.py
  misc/python/materialize/scalability/result/benchmark_result.py
  misc/python/materialize/scalability/result/comparison_outcome.py
  misc/python/materialize/scalability/result/regression_assessment.py
  misc/python/materialize/scalability/result/result_analyzer.py
  misc/python/materialize/scalability/result/result_analyzers.py
  misc/python/materialize/scalability/result/scalability_change.py
  misc/python/materialize/scalability/result/workload_result.py
  misc/python/materialize/scalability/scalability_versioning.py
  misc/python/materialize/scalability/schema/schema.py
  misc/python/materialize/scalability/workload/workload.py
  misc/python/materialize/scalability/workload/workload_markers.py
  misc/python/materialize/scalability/workload/workload_version.py
  misc/python/materialize/scalability/workload/workloads/connection_workloads.py
  misc/python/materialize/scalability/workload/workloads/ddl_workloads.py
  misc/python/materialize/scalability/workload/workloads/dml_dql_workloads.py
  misc/python/materialize/scalability/workload/workloads/self_test_workloads.py
  test/scalability/mzcompose.py
Labels: T-testing

#29377 output consistency: source handling fixes
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/query/additional_source.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/selection/row_selection.py
Labels: T-testing

#29394 output consistency: remove unnecessary output
  misc/python/materialize/output_consistency/validation/validation_outcome.py
Labels: T-testing

#29422 window functions: Fix tiebreaker in `order_aggregate_datums_with_rank`
  src/expr/src/relation/func.rs
  test/sqllogictest/array_subquery.slt
  test/sqllogictest/arrays.slt
  test/sqllogictest/cockroach/aggregate.slt
  test/sqllogictest/jsonb.slt
  test/sqllogictest/list.slt
  test/sqllogictest/list_subquery.slt
  test/sqllogictest/pg_catalog_user.slt
  test/sqllogictest/window_funcs.slt
Labels: A-CLUSTER

#29442 output consistency: add error message ignore
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/validation/validation_message.py
Labels: T-testing

#29443 version consistency: provide evaluation strategy to ignore filter
  misc/python/materialize/output_consistency/execution/evaluation_strategy.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
  misc/python/materialize/version_consistency/version_consistency_test.py
Labels: T-testing

#29446 output consistency: remove string_agg and array_agg without ordering
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29447 output consistency: fix list_agg and change it to use order
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
Labels: T-testing

#29148 Limit compute maintenance based on elapsed time
  src/compute-types/src/dyncfgs.rs
  src/compute/src/compute_state.rs
  src/compute/src/server.rs
Labels: A-CLUSTER

#29362 tests: create table from source: platform checks and testdrive
  misc/python/materialize/checks/all_checks/source_tables.py
  test/testdrive/source-tables.td
Labels: T-testing

#29464 version consistency: add ignore for unnest
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#29379 Micro-optimizations around window functions
  Cargo.lock
  src/expr/Cargo.toml
  src/expr/benches/window_functions.rs
  src/expr/src/lib.rs
  src/expr/src/relation/func.rs
  src/repr/src/row.rs
Labels: A-CLUSTER

#28748 Make `LiteralConstraints` specially handle empty `possible_vals`
  src/transform/src/literal_constraints.rs
Labels: A-optimization, A-CLUSTER

#29519 version consistency: add ignore
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#29531 version consistency: extend ignore to also apply for success mismatches
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#29533 postgres consistency: add regex ignore
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29553 version consistency: ignore version
  misc/python/materialize/version_ancestor_overrides.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#29495 tests: create table from source: cargo tests
  src/environmentd/src/test_util.rs
  src/environmentd/tests/sql.rs
Labels: T-testing

#29580 output consistency: pull up some error message normalization logic
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/validation/error_message_normalizer.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/postgres_consistency/postgres_consistency_test.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
  misc/python/materialize/version_consistency/validation/version_consistency_error_message_normalizer.py
  misc/python/materialize/version_consistency/version_consistency_test.py
Labels: T-testing

#29588 feature benchmark: fix regression reporting
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#29505 tests: platform checks: create table from source
  misc/python/materialize/checks/all_checks/load_generator.py
  misc/python/materialize/checks/all_checks/mysql_cdc.py
  misc/python/materialize/checks/all_checks/pg_cdc.py
  misc/python/materialize/checks/all_checks/source_errors.py
  misc/python/materialize/checks/all_checks/ssh.py
  misc/python/materialize/mzcompose/__init__.py
  test/pg-cdc/subsource-resolution-empty.td
  test/testdrive/tpch.td
Labels: T-testing

#29514 Adjust monotonicity of `TextConcat`
  src/expr/src/scalar/func.rs
Labels: A-optimization, A-CLUSTER

#29619 output consistency: extend ignore entry
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
Labels: T-testing

#29625 feature benchmark: fix output
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#29626 feature benchmark: comparator refactoring
  misc/python/materialize/feature_benchmark/aggregation.py
  misc/python/materialize/feature_benchmark/benchmark.py
  misc/python/materialize/feature_benchmark/benchmark_result.py
  misc/python/materialize/feature_benchmark/benchmark_result_evaluator.py
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/comparator.py
  misc/python/materialize/feature_benchmark/report.py
  misc/python/materialize/scalability/executor/benchmark_executor.py
  misc/python/materialize/scalability/result/scalability_result.py
  misc/python/materialize/scalability/scalability_versioning.py
  misc/python/materialize/test_analytics/data/feature_benchmark/feature_benchmark_result_storage.py
  test/feature-benchmark/mzcompose.py
  test/scalability/mzcompose.py
Labels: T-testing

#29622 tests: create table from source: product limits
  test/limits/mzcompose.py
Labels: T-testing

#29554 Window functions: `Reduce` - `FlatMap UnnestList` fusion
  src/buf.yaml
  src/compute-types/src/explain/text.rs
  src/compute-types/src/plan/lowering.rs
  src/compute-types/src/plan/reduce.proto
  src/compute-types/src/plan/reduce.rs
  src/compute/src/render/flat_map.rs
  src/compute/src/render/reduce.rs
  src/expr/src/linear.rs
  src/expr/src/relation/func.rs
  src/repr/src/optimize.rs
  src/repr/src/row.rs
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/session/vars/definitions.rs
  test/sqllogictest/explain/physical_plan_aggregates.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text_redacted.slt
  test/sqllogictest/window_funcs.slt
  test/testdrive/negative-multiplicities.td
Labels: A-optimization, A-CLUSTER

#29652 output consistency: adapt to psycopg and byte array changes
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#29657 version consistency: fix ignore
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#29662 output consistency: error message matching
  misc/python/materialize/output_consistency/validation/error_message_normalizer.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29665 tests: fix subsource-resolution-empty.td
  test/pg-cdc-old-syntax/subsource-resolution-empty.td
Labels: T-testing

#29637 feature benchmark: repeated scenario runs
  doc/developer/feature-benchmark.md
  misc/python/materialize/feature_benchmark/benchmark_result.py
  misc/python/materialize/feature_benchmark/benchmark_result_selection.py
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/report.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#29679 version consistency: improve version matching in ignore filter
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
  misc/python/materialize/version_consistency/version_consistency_test.py
Labels: T-testing

#29454 compute: Variable-length encoding for list length
  src/environmentd/tests/testdata/http/ws
  src/repr/src/row.rs
  test/sqllogictest/explain/decorrelated_plan_as_json.slt
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/plan_insights.slt
  test/sqllogictest/explain/raw_plan_as_json.slt
  test/sqllogictest/window_funcs.slt
Labels: A-CLUSTER

#29731 postgres consistency: add ignore
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#29730 version consistency: add ignore regarding timestamp casting
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#29735 output consistency: abort run after reaching a certain number of failures
  misc/python/materialize/output_consistency/common/configuration.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/status/test_summary.py
Labels: T-testing

#29732 tests: fix cloudtest upgrade test
  misc/python/materialize/cloudtest/k8s/environmentd.py
  test/cloudtest/test_egress_ips.py
Labels: T-testing

#29742 version consistency: add ignore for floating precision
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#29756 version consistency: extend ignore
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#29502 tests: create table from source: slt
  test/sqllogictest/audit_log.slt
  test/sqllogictest/github-19273.slt
  test/sqllogictest/github-19290.slt
  test/sqllogictest/object_ownership.slt
  test/sqllogictest/rename.slt
  test/sqllogictest/retain_history.slt
Labels: T-testing

#29781 postgres: upgrade version
  ci/release-qualification/pipeline.template.yml
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  test/postgres/Dockerfile
Labels: T-testing
