Repository MaterializeInc/materialize, pull requests merged in 2024-11, with the labels that each got.

#30332 More join visitation fix
  src/expr/src/relation.rs
Labels: A-CLUSTER

#30336 Make all `let_in`s fallible
  src/expr/src/relation.rs
  src/sql/src/plan/lowering.rs
Labels: A-CLUSTER

#30340 Remove the `enable_outer_join_null_filter` feature flag
  misc/python/materialize/feature_flag_consistency/input_data/feature_flag_configurations.py
  src/adapter/src/optimize.rs
  src/repr/src/optimize.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/session/vars/definitions.rs
Labels: A-CLUSTER

#29718 storage: continual feedback upsert operator
  ci/nightly/pipeline.template.yml
  misc/python/materialize/cloudtest/k8s/testdrive.py
  misc/python/materialize/mzcompose/__init__.py
  misc/python/materialize/version_ancestor_overrides.py
  misc/python/materialize/version_list.py
  src/storage-types/src/dyncfgs.rs
  src/storage/src/lib.rs
  src/storage/src/render/sources.rs
  src/storage/src/upsert.rs
  src/storage/src/upsert/types.rs
  src/storage/src/upsert_continual_feedback.rs
  test/kafka-rtr/simple/verify-rtr.td
  test/platform-checks/mzcompose.py
  test/testdrive-old-kafka-src-syntax/explain-timestamps.td
  test/testdrive-old-kafka-src-syntax/mzcompose.py
  test/testdrive-old-kafka-src-syntax/pr-24663-regression.td
  test/testdrive/explain-timestamps.td
  test/testdrive/mzcompose.py
  test/testdrive/pr-24663-regression.td
  test/upsert/rehydration/03-after-rehydration.td
  test/zippy/mzcompose.py
Labels: T-platform-v2

#26258 Redundant Distinct elision
  src/transform/src/analysis.rs
  src/transform/src/lib.rs
  src/transform/src/will_distinct.rs
  test/sqllogictest/advent-of-code/2023/aoc_1205.slt
  test/sqllogictest/advent-of-code/2023/aoc_1216.slt
  test/sqllogictest/advent-of-code/2023/aoc_1220.slt
  test/sqllogictest/advent-of-code/2023/aoc_1223.slt
  test/sqllogictest/cardinality.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/ldbc_bi_eager.slt
  test/sqllogictest/transform/fold_constants.slt
  test/sqllogictest/transform/literal_lifting.slt
  test/sqllogictest/transform/reduce_elision.slt
  test/sqllogictest/transform/redundant_join.slt
  test/sqllogictest/transform/threshold_elision.slt
  test/testdrive/introspection-sources.td
Labels: A-optimization

#30579 test/cluster: another attempt to fix flaky stuck frontier check
  test/cluster/mzcompose.py
Labels: T-testing, A-CLUSTER

#30622 Refactor how we run `FoldConstants`
  src/transform/src/lib.rs
  src/transform/src/normalize_lets.rs
  test/sqllogictest/not-null-propagation.slt
  test/sqllogictest/transform/fold_constants.slt
Labels: A-optimization, A-CLUSTER

#30641 Remove some old feature flags around window functions
  src/adapter/src/optimize.rs
  src/compute-types/src/plan/lowering.rs
  src/repr/src/optimize.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/plan/transform_expr.rs
  src/sql/src/session/vars/definitions.rs
  test/sqllogictest/window_funcs.slt
Labels: A-optimization, A-CLUSTER

#30651 Revert "ci: Try zstd compression for debug sections"
  .bazelrc
Labels: release-blocker
