Repository MaterializeInc/materialize, pull requests merged in 2024-02, with the labels that each got.

#20491 tests: recovery after k8s node failure
  bin/ci-builder
  ci/nightly/pipeline.template.yml
  ci/plugins/cloudtest/hooks/post-command
  ci/test/pipeline.template.yml
  misc/kind/cluster-node-recovery-test.yaml
  misc/python/materialize/cloudtest/app/materialize_application.py
  misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
  misc/python/materialize/cloudtest/k8s/cockroach.py
  misc/python/materialize/cloudtest/k8s/debezium.py
  misc/python/materialize/cloudtest/k8s/environmentd.py
  misc/python/materialize/cloudtest/k8s/minio.py
  misc/python/materialize/cloudtest/k8s/postgres.py
  misc/python/materialize/cloudtest/k8s/redpanda.py
  misc/python/materialize/cloudtest/k8s/ssh.py
  misc/python/materialize/cloudtest/k8s/testdrive.py
  test/cloudtest/conftest.py
  test/cloudtest/node_recovery/README.md
  test/cloudtest/node_recovery/test_k8s_node_recovery.py
  test/cloudtest/setup
Labels: T-testing

#24875 tests: platform checks: testdrive timeout from env var
  test/platform-checks/mzcompose.py
Labels: T-testing

#24876 tests: node recovery: improve output
  test/cloudtest/node_recovery/test_k8s_node_recovery.py
Labels: T-testing

#24857 tests: add explain timestamp statements to materialized_views.py
  misc/python/materialize/checks/all_checks/materialized_views.py
Labels: T-testing

#24887 explain: rework `FastPath` handling
  src/adapter/src/coord.rs
  src/adapter/src/coord/peek.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/optimize/peek.rs
  src/repr/src/explain/tracing.rs
  src/sql-parser/src/ast/defs/statement.rs
Labels: A-COMPUTE

#24926 storage: Assorted minor MySQL source improvements
  src/storage-types/src/sources/mysql.rs
  src/storage/src/source/mysql.rs
  src/storage/src/source/mysql/replication.rs
  src/storage/src/source/mysql/snapshot.rs
Labels: A-STORAGE

#24958 tests: disable cargo test test_retain_history due to #24957
  src/environmentd/tests/sql.rs
Labels: T-testing

#24945 sql: remove Option wrapper around PostgresColumnDesc col_num
  src/postgres-util/src/desc.proto
  src/postgres-util/src/desc.rs
  src/postgres-util/src/schemas.rs
  src/sql/src/pure/postgres.rs
Labels: T-proto

#24902 ci: improve error extraction for parallel workload
  misc/python/materialize/mzcompose/composition.py
  misc/python/materialize/parallel_workload/parallel_workload.py
  misc/python/materialize/parallel_workload/worker.py
  misc/python/materialize/parallel_workload/worker_exception.py
Labels: T-testing

#24907 tests: retain history: follow-up
  misc/python/materialize/checks/all_checks/retain_history.py
Labels: T-testing

#25018 doc/user: refine `SSH TUNNEL` setup instructions
  doc/user/content/ingest-data/postgres-amazon-aurora.md
  doc/user/content/ingest-data/postgres-amazon-rds.md
  doc/user/content/ingest-data/postgres-azure-db.md
  doc/user/content/ingest-data/postgres-self-hosted.md
  doc/user/content/sql/create-connection.md
  doc/user/layouts/shortcodes/network-security/ssh-tunnel.md
Labels: A-docs

#24860 test: add SLT test case to avoid regression of #24506
  test/sqllogictest/github-24506.slt
Labels: T-testing, A-COMPUTE

#25065 adapter: more detailed soft panic in `drop_plans_and_metainfos`
  src/adapter/src/catalog.rs
Labels: A-ADAPTER

#25026 Support `EXPLAIN REPLAN [INDEX | MATERIALIZED VIEW]`
  misc/python/materialize/mzexplore/common.py
  src/adapter/src/catalog/state.rs
  src/adapter/src/coord.rs
  src/adapter/src/coord/indexes.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/optimize/copy_to.rs
  src/adapter/src/optimize/dataflows.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/repr/src/explain/mod.rs
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/explain
  src/sql/src/plan.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/rbac.rs
  test/sqllogictest/explain/enable_eager_delta_joins.slt
  test/sqllogictest/explain/replan_catalog_items.slt
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#25104 tests: version resolution: fix
  misc/python/materialize/version_list.py
Labels: T-testing

#25109 ci: retry k8s node recovery tests
  ci/nightly/pipeline.template.yml
Labels: T-testing

#25105 feature benchmark: add ignore for persist-txn message count change
  misc/python/materialize/version_list.py
Labels: T-testing

#25106 tests: separate ignores for feature benchmark and scalability framework
  misc/python/materialize/version_list.py
Labels: T-testing

#24959 tests: fix mz E2E test
  src/kafka-util/src/client.rs
Labels: T-testing

#25163 feature benchmark: update ignore entry to account for PR#24918 being reverted in 0.87.1
  misc/python/materialize/version_list.py
Labels: T-testing

#25164 tests: specify statement timeout
  misc/python/materialize/checks/all_checks/float_types.py
Labels: T-testing

#25187 tests: extend tests for row as identifier
  src/sql-parser/tests/testdata/create
  src/sql-parser/tests/testdata/select
Labels: T-testing

#25203 feature benchmark: improve output
  misc/python/materialize/feature_benchmark/benchmark.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#25229 postgres consistency: add ignore for #25228 (date parsing)
  misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#25230 sqlsmith: OOM output
  test/sqlsmith/mzcompose.py
Labels: T-testing

#25231 Advance REFRESH `mz_now` resolution to `least_valid_read`
  src/adapter/src/coord/command_handler.rs
Labels: A-ADAPTER

#25270 version consistency: add ignore for date_trunc
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#25268 benchmark: move scenarios
  misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
  misc/python/materialize/feature_benchmark/scenarios/concurrency.py
  misc/python/materialize/feature_benchmark/scenarios/customer.py
  misc/python/materialize/feature_benchmark/scenarios/optbench.py
  misc/python/materialize/feature_benchmark/scenarios/scale.py
  misc/python/materialize/feature_benchmark/scenarios/skew.py
  misc/python/materialize/feature_benchmark/scenarios/subscribe.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#25274 version consistency: cleanup
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#25269 feature benchmark: allow skipping scenarios in certain versions
  misc/python/materialize/feature_benchmark/scenario.py
  misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#25184 Acquire precise read holds for `REFRESH AT`s
  src/adapter/src/coord.rs
  src/adapter/src/coord/command_handler.rs
  src/adapter/src/coord/id_bundle.rs
  src/adapter/src/coord/read_policy.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/coord/sql.rs
  src/adapter/src/coord/timeline.rs
  src/adapter/src/error.rs
  src/storage-controller/src/lib.rs
  test/sqllogictest/materialized_views.slt
Labels: A-ADAPTER

#25326 Fix `set_read_policy` also in the Compute controller
  src/compute-client/src/controller/instance.rs
Labels: A-COMPUTE

#25320 ci: release qualification: feature benchmark should compare against the previous release
  ci/release-qualification/pipeline.template.yml
Labels: T-testing

#25327 Fix the stepping back in `downgrade_warmup_capabilities`
  src/compute-client/src/controller/instance.rs
  test/sqllogictest/materialized_views.slt
Labels: A-COMPUTE

#25332 tests: clean upgrade checks
  ci/nightly/pipeline.template.yml
  misc/python/materialize/checks/scenarios_upgrade.py
  test/upgrade-matrix/README.md
  test/upgrade-matrix/mzcompose
  test/upgrade-matrix/mzcompose.py
  test/upgrade-matrix/nodes.py
Labels: T-testing

#25345 feature benchmark: enable MySqlStreaming
  misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
Labels: T-testing

#25346 feature benchmark: enable MySqlInitialLoad
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#25335 ci: slt: disable failing slt tests
  test/sqllogictest/dates-times.slt.gh25289
Labels: T-testing

#25351 Fix visitation in `HirRelationExpr::contains_temporal`
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/sql/src/plan/expr.rs
  test/sqllogictest/temporal.slt
Labels: A-ADAPTER

#25414 tests: pg-cdc: handle args like in mysql-cdc
  test/pg-cdc/mzcompose.py
Labels: T-testing

#25453 ci: junit.xml: fix error extraction for run_testdrive_files
  misc/python/materialize/cloudtest/k8s/testdrive.py
  misc/python/materialize/mzcompose/test_result.py
Labels: T-testing

#25454 ci: generate dummy junit.xml also for nightly
  ci/mkpipeline.py
Labels: T-testing

#25440 storage: index new source statistics
  doc/user/content/sql/system-catalog/mz_internal.md
  src/catalog/src/builtin.rs
  test/sqllogictest/autogenerated/mz_internal.slt
  test/sqllogictest/mz_introspection_index_accounting.slt
  test/testdrive/source-statistics-view.td
Labels: release-blocker

#25481 storage: make offset_known/offset_committed nullable
  src/storage-client/src/statistics.rs
Labels: release-blocker

#25553 tests: aws-real: retry once
  ci/nightly/pipeline.template.yml
Labels: T-testing

#25552 tests: zippy: no alter connection on upsert sources
  misc/python/materialize/zippy/source_actions.py
Labels: T-testing

#25565 tests: mysql-cdc: minor consistency improvement
  test/mysql-cdc/privileges.td
Labels: T-testing

#25579 tests: move version-ancestor overrides to separate file
  misc/python/materialize/scalability/regression_assessment.py
  misc/python/materialize/version_ancestor_overrides.py
  misc/python/materialize/version_list.py
  test/feature-benchmark/mzcompose.py
  test/rqg/mzcompose.py
  test/scalability/mzcompose.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#25585 Don't acquire read holds when EXPLAINing a REFRESH MV
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  test/sqllogictest/materialized_views.slt
Labels: A-ADAPTER

#25587 tests: preflight check with continue upgrade: exclude StatementLogging for 0.89.2
  misc/python/materialize/checks/scenarios.py
  misc/python/materialize/checks/scenarios_upgrade.py
Labels: T-testing

#25604 tests: sqlsmith: add ignore for NaN timestamp
  misc/python/materialize/sqlsmith.py
Labels: T-testing

#25606 tests: testdrive in cloudtests: capture output for error extraction
  misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
  misc/python/materialize/cloudtest/k8s/testdrive.py
Labels: T-testing

#25564 tests: mysql: add MySQL platform checks
  misc/python/materialize/checks/all_checks/mysql_cdc.py
  test/cloudtest/test_upgrade.py
  test/platform-checks/mzcompose.py
Labels: T-testing

#25616 tests: mysql: fix comment
  misc/python/materialize/zippy/mysql_actions.py
  misc/python/materialize/zippy/postgres_actions.py
Labels: T-testing

#25010 design: Cluster-specific `Optimize` pipelines
  doc/developer/design/20240205_cluster_specific_optimization.md
  doc/developer/design/static/20240205_cluster_specific_optimization/problem.png
Labels: A-COMPUTE

#25640 tests: source cdc: add table after creating the source
  test/mysql-cdc/alter-source.td
  test/pg-cdc/alter-source.td
Labels: T-testing

#25607 tests: mysql: add mysql version-matrix test
  ci/nightly/pipeline.template.yml
  misc/python/materialize/mysql.py
  misc/python/materialize/mzcompose/services/mysql.py
  test/mysql-cdc/alter-table-after-source.td
  test/mysql-cdc/data-utf8.td
  test/mysql-cdc/mysql-cdc.td
  test/mysql-cdc/mzcompose.py
  test/mysql-cdc/types-character.td
  test/mysql-cdc/types-temporal.td
  test/mysql-matrix/mzcompose
  test/mysql-matrix/mzcompose.py
Labels: T-testing

#25574 adapter, compute, storage: Single worker copy to s3 sink end to end
  Cargo.lock
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/optimize/copy_to.rs
  src/aws-util/src/s3_uploader.rs
  src/clusterd/src/bin/clusterd.rs
  src/compute-types/src/sinks.proto
  src/compute-types/src/sinks.rs
  src/compute/src/server.rs
  src/compute/src/sink/copy_to_s3_oneshot.rs
  src/pgcopy/Cargo.toml
  src/pgcopy/build.rs
  src/pgcopy/src/copy.proto
  src/pgcopy/src/copy.rs
  src/pgcopy/src/lib.rs
  src/pgrepr/src/value.rs
  src/pgwire/src/protocol.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/rbac.rs
  src/storage-operators/Cargo.toml
  src/storage-operators/src/lib.rs
  src/storage-operators/src/s3_oneshot_sink.rs
  src/storage-types/Cargo.toml
  src/storage-types/build.rs
  src/storage-types/src/sinks.proto
  src/storage-types/src/sinks.rs
  src/storage/src/source/postgres/snapshot.rs
  test/aws-localstack/copy-to-s3/copy-to-s3.td
  test/aws-localstack/mzcompose.py
  test/pgtest-mz/copy-to.pt
  test/sqllogictest/copy_to.slt
Labels: T-proto
