Repository MaterializeInc/materialize, pull requests merged in 2024-07, with the labels that each got.

#27979 output consistency: support range type
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/range_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/range_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/collection_entry_return_spec.py
  misc/python/materialize/output_consistency/input_data/return_specs/range_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/range_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
  misc/python/materialize/output_consistency/input_data/values/range_values_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#27959 Add contains operator for LIST and ARRAY
  src/expr/src/scalar.proto
  src/expr/src/scalar/func.rs
  src/pgrepr-consts/src/oid.rs
  src/sql/src/func.rs
  test/sqllogictest/arrays.slt
  test/sqllogictest/list.slt
Labels: T-proto

#28009 output consistency: improve operation description
  misc/python/materialize/output_consistency/operation/operation.py
Labels: T-testing

#28018 Avoid null skew in outer join lowering
  src/adapter/src/optimize.rs
  src/expr/src/scalar.rs
  src/expr/tests/testdata/reduce
  src/repr/src/optimize.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/session/vars/definitions.rs
  src/transform/tests/testdata/canonicalize_mfp
  test/sqllogictest/attributes/mir_arity.slt
  test/sqllogictest/attributes/mir_column_types.slt
  test/sqllogictest/autogenerated/all_parts_essential.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/explain/decorrelated_plan_as_json.slt
  test/sqllogictest/explain/decorrelated_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_json.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text_redacted.slt
  test/sqllogictest/explain/replan_catalog_items.slt
  test/sqllogictest/explain/view.slt
  test/sqllogictest/github-16036.slt
  test/sqllogictest/joins.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/ldbc_bi_eager.slt
  test/sqllogictest/outer_join_lowering.slt
  test/sqllogictest/outer_join_simplification.slt
  test/sqllogictest/scalar_subqueries_select_list.slt
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/sqllogictest/tpch_select.slt
  test/sqllogictest/transform/aggregation_nullability.slt
  test/sqllogictest/transform/join_index.slt
  test/sqllogictest/transform/relation_cse.slt
  test/sqllogictest/transform/union.slt
  test/testdrive/mz-arrangement-sharing.td
Labels: A-optimization, A-CLUSTER

#28010 output consistency: array type: add operations
  misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/return_specs/array_return_spec.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28038 output consistency: support record type
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/record_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/params/record_operation_param.py
  misc/python/materialize/output_consistency/input_data/return_specs/record_return_spec.py
  misc/python/materialize/output_consistency/input_data/return_specs/undetermined_return_spec.py
  misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
  misc/python/materialize/output_consistency/input_data/types/record_types_provider.py
Labels: T-testing

#28036 version consistency: add ignore for contains on list and array
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#28043 output consistency: contains operation
  misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/range_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/range_operation_param.py
Labels: T-testing

#28051 De-flake a REFRESH introspection test
  test/sqllogictest/materialized_views.slt
  test/testdrive/materialized-view-refresh-options.td
Labels: T-testing

#28017 platform checks: show create cluster, alter cluster to managed
  misc/python/materialize/checks/all_checks/cluster.py
  misc/python/materialize/checks/checks.py
Labels: T-testing

#28066 output consistency: allow disabling predefined queries
  misc/python/materialize/output_consistency/common/configuration.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/runner/test_runner.py
Labels: T-testing

#28068 output consistency: fix determine storage layout
  misc/python/materialize/output_consistency/expression/expression_with_args.py
Labels: T-testing

#28086 Wire up `enable_outer_join_null_filter` to `EXPLAIN`
  src/repr/src/explain.rs
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/statement/dml.rs
Labels: A-optimization, A-ADAPTER

#28090 Adjust window func tests
  test/sqllogictest/transform/fold_constants.slt
  test/sqllogictest/window_funcs.slt
Labels: T-testing

#28101 output consistency: improve statistics
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/execution/test_summary.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/generators/query_generator.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/output/output_printer.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/status/consistency_test_logger.py
  misc/python/materialize/output_consistency/status/test_summary.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_outcome.py
Labels: T-testing

#28105 tests: aws-real: cleanup aws roles after test
  test/aws/mzcompose.py
Labels: T-testing

#27977 Detect loops in `Fixpoint`
  src/transform/src/lib.rs
Labels: A-optimization, A-CLUSTER

#22776 Design doc for `REFRESH` MVs
  doc/developer/design/00000000_template.md
  doc/developer/design/20231027_refresh_mvs.md
Labels: A-compute

#28067 output consistency: provide reproduction code in collapsible part of annotation
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/output/base_output_printer.py
  misc/python/materialize/output_consistency/output/output_printer.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/status/test_summary.py
  misc/python/materialize/output_consistency/validation/validation_outcome.py
Labels: T-testing

#28135 output consistency: fix array type
  misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
  misc/python/materialize/output_consistency/input_data/types/array_type_provider.py
  misc/python/materialize/output_consistency/input_data/values/array_values_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28161 output consistency: map type: adjust operation specifications
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
Labels: T-testing

#28138 Change `REHYDRATION TIME ESTIMATE` to `HYDRATION TIME ESTIMATE`
  doc/developer/design/20231027_refresh_mvs.md
  doc/user/content/sql/alter-cluster.md
  doc/user/content/sql/create-cluster.md
  doc/user/content/sql/create-materialized-view.md
  doc/user/content/sql/system-catalog/mz_internal.md
  misc/dbt-materialize/dbt/include/materialize/macros/ci/create_cluster.sql
  misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
  misc/dbt-materialize/tests/adapter/test_ci.py
  misc/dbt-materialize/tests/adapter/test_deploy.py
  src/adapter/src/catalog/builtin_table_updates.rs
  src/adapter/src/coord/cluster_scheduling.rs
  src/audit-log/src/lib.rs
  src/catalog/src/builtin.rs
  src/catalog/src/durable/objects/serialization.rs
  src/catalog/tests/read-write.rs
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/ddl
  src/sql/src/plan.rs
  src/sql/src/plan/statement/ddl.rs
  test/sqllogictest/autogenerated/mz_internal.slt
  test/sqllogictest/materialized_views.slt
  test/testdrive/materialized-view-refresh-options.td
Labels: A-ADAPTER

#28089 output consistency: record type: fix function definition, add ignore entry
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/record_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/any_operation_param.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/params/same_operation_param.py
  misc/python/materialize/output_consistency/validation/error_message_normalizer.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#28195 output consistency: record type: fix error message normalization
  misc/python/materialize/output_consistency/validation/error_message_normalizer.py
Labels: T-testing

#28132 output consistency: add jsonb_agg and jsonb_object_agg
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
  misc/python/materialize/output_consistency/operation/operation.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#28200 output consistency: introduce expression hash
  misc/python/materialize/output_consistency/enum/enum_constant.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_message.py
  misc/python/materialize/output_consistency/validation/validation_outcome.py
Labels: T-testing

#28206 Fix null filter in outer join lowering to include the outer columns
  src/sql/src/plan/lowering.rs
  test/sqllogictest/github-28174.slt
  test/sqllogictest/outer_join_lowering.slt
Labels: A-optimization, A-CLUSTER

#28205 Add pg_size_pretty function
  src/environmentd/tests/testdata/http/ws
  src/expr/src/scalar.proto
  src/expr/src/scalar/func.rs
  src/expr/src/scalar/func/impls/numeric.rs
  src/sql/src/func.rs
  test/sqllogictest/oid.slt
  test/sqllogictest/pg_size_pretty.slt
Labels: T-proto

#28242 output consistency: add infinity value to double type
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
  misc/python/materialize/output_consistency/input_data/values/number_values_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28278 output consistency: expand data provided to ignore logic
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28164 output consistency: address inoperable functions
  misc/python/materialize/cli/ci_annotate_errors.py
  misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
  misc/python/materialize/output_consistency/runner/test_runner.py
  misc/python/materialize/output_consistency/status/test_summary.py
Labels: T-testing

#28256 Save plan hashes in `Fixpoint` rather than full plans
  src/expr/src/relation.rs
  src/transform/src/lib.rs
Labels: A-optimization, A-CLUSTER

#28268 output consistency: add pg_size_pretty
  misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
  misc/python/materialize/output_consistency/input_data/operations/pg_operations_provider.py
  misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28296 output consistency: add ignore for order
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/query/query_template.py
Labels: T-testing

#28267 output consistency: further date values
  misc/python/materialize/output_consistency/expression/expression_characteristics.py
  misc/python/materialize/output_consistency/input_data/types/date_time_types_provider.py
  misc/python/materialize/output_consistency/input_data/values/date_time_values_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
  misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
Labels: T-testing

#28281 tests: cluster introspection configuration
  misc/python/materialize/checks/all_checks/cluster.py
  test/testdrive/system-cluster.td
Labels: T-testing

#28297 version consistency: allow specifying other tag
  ci/nightly/pipeline.template.yml
  test/version-consistency/mzcompose.py
Labels: T-testing

#28298 version consistency: add ignore
  misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Labels: T-testing

#28301 postgres consistency: add ignore: ALL and ANY with NULL or empty array
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28302 tests: pg-cdc: verify that no replication slots exist at the beginning
  test/pg-cdc/mzcompose.py
Labels: T-testing

#28303 output consistency: rework input data filtering
  misc/python/materialize/output_consistency/common/configuration.py
  misc/python/materialize/output_consistency/data_type/data_type_with_values.py
  misc/python/materialize/output_consistency/data_value/data_value.py
  misc/python/materialize/output_consistency/generators/expression_generator.py
  misc/python/materialize/output_consistency/input_data/test_input_data.py
  misc/python/materialize/output_consistency/input_data/test_input_operations.py
  misc/python/materialize/output_consistency/input_data/test_input_types.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/postgres_consistency/postgres_consistency_test.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
  misc/python/materialize/version_consistency/version_consistency_test.py
Labels: T-testing

#28351 version consistency: align main entry point with mzcompose
  misc/python/materialize/version_consistency/version_consistency_test.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#28348 postgres consistency: extend ignore entry
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28387 tests: aws-real: also delete jump role after test
  test/aws/mzcompose.py
Labels: T-testing

#28383 postgres consistency: add ignores
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#28508 adapter,compute,controller: attach workload_class label to relevant metrics
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/cluster.rs
  src/adapter/src/coord/sequencer/inner/cluster.rs
  src/adapter/src/flags.rs
  src/catalog/src/builtin.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/protocol/command.proto
  src/compute-client/src/protocol/command.rs
  src/compute/src/compute_state.rs
  src/compute/src/metrics.rs
  src/controller/src/clusters.rs
  src/ore/src/metrics.rs
  test/cluster/mzcompose.py
Labels: release-blocker

#28342 version consistency: test explain plans
  bin/version-consistency-explain-test
  misc/python/materialize/output_consistency/common/configuration.py
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/execution/query_output_mode.py
  misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
  misc/python/materialize/output_consistency/output/base_output_printer.py
  misc/python/materialize/output_consistency/output/output_printer.py
  misc/python/materialize/output_consistency/output/reproduction_code_printer.py
  misc/python/materialize/output_consistency/output_consistency_test.py
  misc/python/materialize/output_consistency/query/query_result.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_message.py
  misc/python/materialize/postgres_consistency/postgres_consistency_test.py
  misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
  misc/python/materialize/version_consistency/version_consistency_test.py
  test/output-consistency/mzcompose.py
  test/postgres-consistency/mzcompose.py
  test/version-consistency/README.md
  test/version-consistency/mzcompose.py
Labels: T-testing

#28518 tests: add additional SLT (explain) tests for aggregations
  test/sqllogictest/aggregates_2.slt
  test/sqllogictest/explain/aggregates.slt
  test/sqllogictest/explain/physical_plan_aggregates.slt
Labels: T-testing

#28375 transform: port Monotonicity to the Analysis framework
  src/adapter/src/optimize/copy_to.rs
  src/adapter/src/optimize/dataflows.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/transform/src/analysis.rs
  src/transform/src/analysis/monotonic.rs
  src/transform/src/dataflow.rs
  src/transform/src/monotonic.rs
Labels: A-optimization, A-CLUSTER

#28551 tests: fix 0dt test
  test/0dt/mzcompose.py
Labels: T-testing

#28563 feature benchmark: fix specified unit
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/measurement.py
  misc/python/materialize/feature_benchmark/scenarios/optbench.py
Labels: T-testing

#28593 feature benchmark: measure duration for OptBench in nanoseconds
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/measurement.py
  misc/python/materialize/feature_benchmark/scenarios/optbench.py
  misc/python/materialize/test_analytics/test_analytics_db.py
Labels: T-testing

#28626 feature benchmark: print measurement unit
  misc/python/materialize/feature_benchmark/aggregation.py
  misc/python/materialize/feature_benchmark/benchmark.py
  misc/python/materialize/feature_benchmark/benchmark_versioning.py
  misc/python/materialize/feature_benchmark/comparator.py
  misc/python/materialize/feature_benchmark/measurement.py
  misc/python/materialize/feature_benchmark/measurement_source.py
  misc/python/materialize/feature_benchmark/scenarios/optbench.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#28657 postgres consistency: extend ignore regarding decimal 0s are not shown
  misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
  misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
  misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
Labels: T-testing
