Repository MaterializeInc/materialize, pull requests merged in 2024-01, with the labels that each got.

#24262 postgres consistency: remove #22024 ignore (min/max for time)
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#24268 scalability framework: fix assessment of regressions
  misc/python/materialize/scalability/regression_assessment.py
Labels: T-testing

#24067 explain: change `ExplainConfig` defaults in production
  src/repr/src/explain/mod.rs
Labels: A-optimization, A-COMPUTE

#23988 adapter: `mz_optimizer_notices` improvements
  doc/user/content/sql/system-catalog/mz_internal.md
  misc/python/materialize/checks/all_checks/optimizer_notices.py
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/builtin_table_updates/notice.rs
  src/adapter/src/catalog/open.rs
  src/adapter/src/explain/mod.rs
  src/catalog/src/builtin/notice.rs
  src/transform/src/notice/mod.rs
  test/sqllogictest/autogenerated/mz_internal.slt
  test/sqllogictest/privilege_grants.slt
  test/sqllogictest/transform/notice/index_key_empty.slt
  test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt
  test/testdrive/mz-arrangement-sharing.td
Labels: A-docs, A-optimization, A-COMPUTE, A-ADAPTER

#24295 tests: fix feature benchmark
  misc/python/materialize/feature_benchmark/benchmark.py
  misc/python/materialize/feature_benchmark/scenario.py
  test/feature-benchmark/mzcompose.py
  test/feature-benchmark/scenarios.py
Labels: T-testing

#24293 cloudtests: pull methods into mz_application
  misc/python/materialize/cloudtest/app/materialize_application.py
  test/cloudtest/test_storage.py
Labels: T-testing

#24269 adapter: wrap materialized view optimization in `catch_unwind`
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/create_view.rs
  src/adapter/src/coord/sequencer/inner/subscribe.rs
  src/adapter/src/optimize/mod.rs
  src/adapter/src/util.rs
  src/expr/src/scalar/mod.rs
  src/transform/src/fold_constants.rs
  src/transform/src/lib.rs
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#24302 explain: avoid panics in `Display for HumanizedExpr<'a, usize, M>`
  src/expr/src/explain/text.rs
  test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt
Labels: A-optimization, A-COMPUTE

#23772 tests: create SSH setup for cloudtest upgrade
  misc/python/materialize/checks/cloudtest_actions.py
  misc/python/materialize/checks/executors.py
  test/cloudtest/test_upgrade.py
Labels: T-testing

#24361 tests: fix merge skew
  test/upsert/rocksdb-cleanup/drop-source.td
Labels: T-testing

#24331 adapter: move `EXPLAIN CREATE MATERIALIZED VIEW` optimization off the coordinator thread
  misc/python/materialize/cli/ci_logged_errors_detect.py
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/repr/src/explain/tracing.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
  test/sqllogictest/explain/broken_statements.slt
Labels: A-ADAPTER

#24339 adapter: move `EXPLAIN CREATE INDEX` optimization off the coordinator thread
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement/dml.rs
Labels: A-ADAPTER

#24369 adapter: move `sequence_peek` to a separate file
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
Labels: A-ADAPTER

#24282 storage: MySQL Source Purification & Planning
  Cargo.lock
  misc/python/materialize/mzcompose/services/mysql.py
  src/mysql-util/Cargo.toml
  src/mysql-util/build.rs
  src/mysql-util/src/desc.proto
  src/mysql-util/src/desc.rs
  src/mysql-util/src/lib.rs
  src/mysql-util/src/replication.rs
  src/mysql-util/src/schemas.rs
  src/sql-parser/src/ast/defs/ddl.rs
  src/sql-parser/src/parser.rs
  src/sql/src/catalog.rs
  src/sql/src/plan/error.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/pure.rs
  src/sql/src/pure/error.rs
  src/sql/src/pure/mysql.rs
  src/sql/src/pure/postgres.rs
  src/storage-types/build.rs
  src/storage-types/src/connections.rs
  src/storage-types/src/sources.proto
  src/storage-types/src/sources.rs
  src/storage-types/src/sources/mysql.proto
  src/storage-types/src/sources/mysql.rs
  src/storage/src/healthcheck.rs
  src/storage/src/render/sources.rs
  src/storage/src/source/mod.rs
  src/storage/src/source/mysql.rs
  src/storage/src/source/mysql/timestamp.rs
  src/storage/src/storage_state/async_storage_worker.rs
  src/storage/tests/setup.rs
  test/mysql-cdc/create-source.td
  test/mysql-cdc/mzcompose.py
Labels: A-source, A-STORAGE

#24391 ci: reenable checks-backup-rollback
  ci/nightly/pipeline.template.yml
Labels: T-testing

#24393 feature benchmark: fix ExactlyOnce scenario
  test/feature-benchmark/mzcompose.py
  test/feature-benchmark/scenarios.py
Labels: T-testing

#24426 Add `EXPLAIN WITH (redacted)` support for LIR plans
  src/compute-types/src/explain/text.rs
  src/expr/src/explain/text.rs
  src/expr/src/relation/func.rs
  src/expr/src/relation/mod.rs
  src/sql/src/plan/explain/text.rs
  src/transform/src/typecheck.rs
  test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
  test/sqllogictest/explain/physical_plan_as_text_redacted.slt
Labels: A-COMPUTE

#24458 scalability framework: communicate through balancerd
  misc/python/materialize/scalability/endpoint.py
  misc/python/materialize/scalability/endpoints.py
  test/scalability/mzcompose.py
Labels: T-testing

#24463 ci: increase timeout of dbt-materialize
  ci/test/pipeline.template.yml
Labels: T-testing

#24344 tests: retain history feature
  ci/nightly/pipeline.template.yml
  misc/python/materialize/checks/all_checks/retain_history.py
  misc/python/materialize/mzcompose/__init__.py
  test/platform-checks/mzcompose.py
  test/retain-history/mzcompose
  test/retain-history/mzcompose.py
Labels: T-testing

#24465 optimize: move `PeekPlan` creation to `peek::Optimizer`
  src/adapter/src/coord/peek.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/optimize/peek.rs
Labels: A-ADAPTER

#24526 adapter: run all peek optimization stages off thread
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/optimize/peek.rs
Labels: A-ADAPTER

#24557 version consistency: add ignore
  misc/python/materialize/version_list.py
Labels: T-testing

#24552 output consistency: add OtherReturnTypeSpec
  misc/python/materialize/output_consistency/data_type/data_type_category.py
  misc/python/materialize/output_consistency/input_data/return_specs/other_return_spec.py
Labels: T-testing

#24548 tests: fix 3_number_aggfns_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_dataflow.slt
Labels: T-testing

#24551 output consistency: add jsonb operations
  misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/output_consistency/input_data/values/jsonb_values_provider.py
Labels: T-testing

#24555 output consistency: add date-time operations
  misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#24580 output consistency: provide SqlDialectAdjuster to to_sql
  misc/python/materialize/output_consistency/data_value/data_column.py
  misc/python/materialize/output_consistency/enum/enum_constant.py
  misc/python/materialize/output_consistency/expression/expression.py
  misc/python/materialize/output_consistency/expression/expression_with_args.py
  misc/python/materialize/output_consistency/query/query_template.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
Labels: T-testing

#24582 Clarify that frontier advancements past the `until` are not suppressed
  src/compute-types/src/dataflows.rs
  src/compute/src/sink/refresh.rs
Labels: A-COMPUTE

#24443 Acquire read holds after the timestamp selection of a REFRESH MV
  misc/python/materialize/parallel_workload/database.py
  src/adapter/src/coord.rs
  src/adapter/src/coord/command_handler.rs
  src/adapter/src/coord/read_policy.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/coord/sql.rs
  src/sql/src/plan.rs
  src/sql/src/plan/statement.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/pure.rs
  test/sqllogictest/materialized_views.slt
Labels: A-ADAPTER

#24581 sql: migrate some `~Plan` types from `Mir~` to `HirRelationExpr`
  src/adapter/src/coord/introspection.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/sql/src/plan.rs
  src/sql/src/plan/expr.rs
  src/sql/src/plan/statement/dml.rs
Labels: A-sql, A-ADAPTER

#24613 repr: fix some `PlanTrace` bugs
  src/adapter/src/coord/sequencer/inner.rs
  src/repr/src/explain/tracing.rs
Labels: A-optimization, A-COMPUTE

#24554 output consistency: add cast operation
  misc/python/materialize/output_consistency/data_type/data_type.py
  misc/python/materialize/output_consistency/enum/enum_constant.py
  misc/python/materialize/output_consistency/enum/enum_data_type.py
  misc/python/materialize/output_consistency/execution/sql_dialect_adjuster.py
  misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
  misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
  misc/python/materialize/postgres_consistency/execution/pg_dialect_adjuster.py
Labels: T-testing

#24560 output consistency: provide failures to mzcompose for junit.xml
  misc/python/materialize/output_consistency/execution/query_execution_manager.py
  misc/python/materialize/output_consistency/execution/test_summary.py
  misc/python/materialize/output_consistency/validation/result_comparator.py
  misc/python/materialize/output_consistency/validation/validation_message.py
  misc/python/materialize/output_consistency/validation/validation_outcome.py
  test/output-consistency/mzcompose.py
  test/postgres-consistency/mzcompose.py
  test/version-consistency/mzcompose.py
Labels: T-testing

#24569 Move `EXPLAIN SELECT` optimization off the coordinator thread
  src/adapter/src/coord.rs
  src/adapter/src/coord/message_handler.rs
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/optimize/peek.rs
Labels: A-ADAPTER

#24655 tracing: include with_channel fix in opentelemetry-otlp using git patch
  Cargo.lock
  Cargo.toml
Labels: release-blocker

#24622 scalability framework: test connection establishment (with balancerd)
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/endpoint.py
  misc/python/materialize/scalability/operation.py
  misc/python/materialize/scalability/operation_data.py
  misc/python/materialize/scalability/operations.py
  misc/python/materialize/scalability/workload.py
  misc/python/materialize/scalability/workloads.py
  test/scalability/mzcompose.py
Labels: T-testing

#24677 peek: move LIR optimization back on the main thread
  src/adapter/src/coord/sequencer/inner/peek.rs
Labels: A-ADAPTER

#24679 postgres consistency: add ignore for cast to default decimal type (inconsistency #24678)
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#24683 scalability framework: allow disabling balancerd
  misc/python/materialize/scalability/endpoints.py
  test/scalability/mzcompose.py
Labels: T-testing

#24686 postgres consistency: add ignore for cast from boolean to bigint/int8
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#24627 sql: force enable disk for new cc/C sizes
  src/catalog/src/config.rs
  src/catalog/src/memory/objects.rs
  src/sql/src/catalog.rs
  src/sql/src/plan/statement/ddl.rs
  test/testdrive/cc_cluster_sizes.td
Labels: release-blocker

#24688 postgres consistency: add ignore for .000 suffix when casting to decimal
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#24713 postgres consistency: also ignore "cannot cast type bigint to boolean"
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#24717 scalability framework: fix test operations
  misc/python/materialize/scalability/operations_test.py
Labels: T-testing

#24632 scalability framework: separate build for connection workload
  ci/nightly/pipeline.template.yml
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/workload.py
  misc/python/materialize/scalability/workload_markers.py
  misc/python/materialize/scalability/workloads.py
  misc/python/materialize/scalability/workloads_test.py
  test/scalability/mzcompose.py
Labels: T-testing

#24737 postgres inconsistency: add ignore for empty time string
  misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Labels: T-testing

#24821 tests: product limits: reduce case-when count
  test/limits/mzcompose.py
Labels: T-testing

#24805 sql: fix regression in ALTER CLUSTER ... SET (SIZE ...)
  src/sql/src/plan/statement/ddl.rs
  test/testdrive/cc_cluster_sizes.td
Labels: release-blocker

#24823 tests: simplify and align parallelism handling
  ci/test/cargo-test/mzcompose.py
  misc/python/materialize/buildkite.py
  misc/python/materialize/mzcompose/services/testdrive.py
  test/cluster/mzcompose.py
  test/feature-benchmark/mzcompose.py
  test/pg-cdc-resumption/mzcompose.py
  test/platform-checks/mzcompose.py
  test/sqllogictest/mzcompose.py
  test/upgrade-matrix/mzcompose.py
Labels: T-testing

#24722 Notice when creating an index that is identical to an already existing one
  misc/python/materialize/checks/all_checks/optimizer_notices.py
  src/adapter/src/coord/sequencer/inner.rs
  src/adapter/src/optimize/dataflows.rs
  src/adapter/src/optimize/index.rs
  src/sql/src/session/vars.rs
  src/transform/src/notice/index_already_exists.rs
  src/transform/src/notice/mod.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/transform/notice/index_already_exists.slt
Labels: A-optimization, A-COMPUTE, A-ADAPTER

#24841 tests: simplify and align parallelism handling (2)
  misc/python/materialize/buildkite.py
  test/cluster/mzcompose.py
  test/feature-benchmark/mzcompose.py
Labels: T-testing

#24648 scalability framework: add DDL operations
  ci/nightly/pipeline.template.yml
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/endpoints.py
  misc/python/materialize/scalability/operation.py
  misc/python/materialize/scalability/operation_data.py
  misc/python/materialize/scalability/operations.py
  misc/python/materialize/scalability/operations_test.py
  misc/python/materialize/scalability/workload.py
  misc/python/materialize/scalability/workload_markers.py
  misc/python/materialize/scalability/workloads.py
Labels: T-testing

#24649 scalability framework: verbose output
  misc/python/materialize/scalability/benchmark_config.py
  misc/python/materialize/scalability/benchmark_executor.py
  misc/python/materialize/scalability/operation.py
  misc/python/materialize/scalability/workload.py
  test/scalability/mzcompose.py
Labels: T-testing

#24840 adapter: Make also the new EXPLAIN pipeline not linearize
  src/adapter/src/coord/sequencer/inner/peek.rs
  src/adapter/src/explain/optimizer_trace.rs
  src/adapter/src/session.rs
  test/sqllogictest/materialized_views.slt
Labels: A-ADAPTER

#24853 tests: fix SLT
  test/sqllogictest/mzcompose.py
  test/sqllogictest/transform/notice/index_key_empty.slt
Labels: T-testing
