Repository MaterializeInc/materialize, pull requests merged in 2025-07, with the labels that each got.

#32888 compute: use protocol nonces to identify controller connections
  Cargo.lock
  src/cluster-client/Cargo.toml
  src/cluster-client/src/client.proto
  src/cluster-client/src/client.rs
  src/cluster/Cargo.toml
  src/cluster/src/client.rs
  src/compute-client/src/controller.rs
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/controller/replica.rs
  src/compute-client/src/protocol/command.proto
  src/compute-client/src/protocol/command.rs
  src/compute-client/src/service.rs
  src/compute/src/command_channel.rs
  src/compute/src/server.rs
  src/controller/src/lib.rs
  src/storage-client/src/client.proto
  src/storage-client/src/client.rs
  src/storage-controller/src/instance.rs
  src/storage-controller/src/lib.rs
  src/storage/src/server.rs
  src/storage/src/storage_state.rs
Labels: self-managed-backport-v25.2

#32984 adapter: Fix error msg for `InvalidSchemaName`
  src/sql/src/plan/error.rs
  src/sqllogictest/src/runner.rs
  test/sqllogictest/regex.slt
  test/sqllogictest/schemas.slt
Labels: A-ADAPTER

#32954 Update definitions.rs
  src/sql/src/session/vars/definitions.rs
  test/sqllogictest/attributes/mir_arity.slt
  test/sqllogictest/attributes/mir_column_types.slt
  test/sqllogictest/autogenerated/all_parts_essential.slt
  test/sqllogictest/distinct_arrangements.slt
  test/sqllogictest/explain/aggregates.slt
  test/sqllogictest/explain/physical_plan_aggregates.slt
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text_redacted.slt
  test/sqllogictest/not-null-propagation.slt
  test/sqllogictest/system-cluster.slt
  test/sqllogictest/transform/aggregation_nullability.slt
  test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_dataflow.slt
  test/testdrive/session.td
Labels: self-managed-backport-v25.2

#33021 revert: Compact command history when client connects
  src/compute-client/src/controller/instance.rs
  src/compute-client/src/controller/replica.rs
  src/compute-client/src/protocol/history.rs
  src/compute/src/compute_state.rs
  src/compute/src/server.rs
  test/cluster/mzcompose.py
Labels: release-blocker

#33035 adapter: Fix the name of `PLAN_INSIGHTS_NOTICE_FAST_PATH_CLUSTERS_OPTIMIZE_DURATION`
  misc/python/materialize/mzcompose/__init__.py
  misc/python/materialize/parallel_workload/action.py
  src/adapter-types/src/dyncfgs.rs
Labels: A-ADAPTER

#33070 Add feature flag for `compute_fast_path_clusters`
  src/adapter/src/explain/insights.rs
  src/repr/src/optimize.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/session/vars/definitions.rs
  test/sqllogictest/explain/plan_insights.slt
Labels: release-blocker, A-ADAPTER

#33076 Fix indentation in `peek_optimize`
  src/adapter/src/coord/sequencer/inner/peek.rs
Labels: A-ADAPTER

#33077 Rename `ExprPrepStyle::Index`, because we are using it for MVs and subscribes too
  src/adapter/src/optimize/dataflows.rs
  src/adapter/src/optimize/index.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/subscribe.rs
Labels: A-CLUSTER

#33150 Short circuit at LIMIT+OFFSET in peek stash
  src/compute/src/compute_state.rs
  src/compute/src/compute_state/peek_stash.rs
  src/expr/src/relation.rs
Labels: A-CLUSTER

#33175 Fix testdrive's Dockerfile
  src/testdrive/ci/Dockerfile
Labels: T-testing

#33215 Skip cardinality.slt
  test/sqllogictest/cardinality.slt
Labels: T-testing
