Repository MaterializeInc/materialize, pull requests merged in 2025-03, with the labels that each got.

#31717 [parser] Refactor the handling of complex expressions in casts
  src/environmentd/tests/testdata/http/post
  src/environmentd/tests/testdata/http/ws
  src/sql-parser/src/ast/defs/expr.rs
  src/sql-parser/src/lib.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/sqlparser_common.rs
  src/sql-parser/tests/testdata/select
  src/sql-pretty/src/doc.rs
  test/sqllogictest/cast.slt
Labels: A-ADAPTER, lts-backport-v25.1

#31801 persist: add a few more Consensus configs to dyncfg
  Cargo.lock
  src/environmentd/BUILD.bazel
  src/environmentd/Cargo.toml
  src/environmentd/src/test_util.rs
  src/persist-client/src/cfg.rs
Labels: lts-backport-v25.1

#31791 Run `ProjectionPushdown` after the last `RelationCSE`
  src/repr/src/optimize.rs
  src/sql-lexer/src/keywords.txt
  src/sql-parser/src/ast/defs/statement.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/session/vars/definitions.rs
  src/transform/src/lib.rs
  src/transform/src/movement/projection_pushdown.rs
  test/sqllogictest/advent-of-code/2023/aoc_1207.slt
  test/sqllogictest/advent-of-code/2023/aoc_1210.slt
  test/sqllogictest/advent-of-code/2023/aoc_1214.slt
  test/sqllogictest/advent-of-code/2023/aoc_1220.slt
  test/sqllogictest/autogenerated/all_parts_essential.slt
  test/sqllogictest/chbench.slt
  test/sqllogictest/explain/aggregates.slt
  test/sqllogictest/explain/physical_plan_aggregates.slt
  test/sqllogictest/joins.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/ldbc_bi_eager.slt
  test/sqllogictest/system-cluster.slt
  test/sqllogictest/timedomain.slt
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/sqllogictest/tpch_select.slt
  test/sqllogictest/transactions.slt
  test/sqllogictest/transform/join_fusion.slt
  test/sqllogictest/transform/join_index.slt
  test/sqllogictest/transform/relation_cse.slt
  test/testdrive-old-kafka-src-syntax/source-linear-operators.td
  test/testdrive/source-linear-operators.td
Labels: A-CLUSTER, lts-backport-v25.1

#31887 Implement `SHOW REDACTED CREATE ...`
  doc/user/content/sql/show-create-connection.md
  doc/user/content/sql/show-create-index.md
  doc/user/content/sql/show-create-materialized-view.md
  doc/user/content/sql/show-create-sink.md
  doc/user/content/sql/show-create-source.md
  doc/user/content/sql/show-create-table.md
  doc/user/content/sql/show-create-view.md
  doc/user/data/show_create_redacted_option.yml
  src/sql-parser/src/ast/defs/statement.rs
  src/sql-parser/src/ast/display.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/show
  src/sql/src/plan/statement/show.rs
  test/sqllogictest/redacted.slt
Labels: A-ADAPTER, lts-backport-v25.1

#31930 tests: Add newline handling to slt when `multiline` is not specified
  .github/CODEOWNERS
  src/sqllogictest/src/ast.rs
  src/sqllogictest/src/parser.rs
  src/sqllogictest/src/runner.rs
  test/sqllogictest/slt.slt
Labels: T-testing, lts-backport-v25.1

#31802 [design] better column names
  doc/developer/design/20250307_column_names.md
Labels: A-sql, T-UX, T-debug, A-optimization, A-compute, A-CLUSTER

#31979 optimizer: Make `EQProp` call `MSE::reduce` only after a change in `reduce_expr`
  src/repr/src/optimize.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  src/sql/src/session/vars/definitions.rs
  src/transform/src/equivalence_propagation.rs
Labels: A-CLUSTER
