Repository MaterializeInc/materialize, pull requests merged in 2025-05, with the labels that each got.

#32443 adapter: Support parameters in OFFSET clause
  src/environmentd/tests/pgwire.rs
  src/expr/src/relation.rs
  src/sql/src/plan/error.rs
  src/sql/src/plan/explain/text.rs
  src/sql/src/plan/hir.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
  test/sqllogictest/cockroach/aggregate.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/raw_plan_as_json.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
  test/sqllogictest/order_by.slt
  test/sqllogictest/window_funcs.slt
Labels: C-feature, A-ADAPTER

#32450 Cosmetic fixes in `OFFSET` handling
  src/sql/src/plan/hir.rs
Labels: A-ADAPTER

#32449 Remove `bind_parameter` calls from statement types that don't support `PREPARE`
  src/environmentd/tests/pgwire.rs
  src/sql/src/plan/hir.rs
  src/sql/src/plan/statement.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
Labels: A-ADAPTER

#32457 Use `SqlState::UNDEFINED_PARAMETER` for certain parameter errors
  src/adapter/src/error.rs
  src/environmentd/tests/pgwire.rs
  src/sql/src/plan/error.rs
  src/sql/src/plan/hir.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/statement/dml.rs
Labels: A-ADAPTER

#32465 adapter: Allow parameters in `RETURNING`
  src/sql/src/plan/query.rs
  src/sql/src/plan/statement/dml.rs
  test/sqllogictest/prepare.slt
Labels: A-ADAPTER

#32463 Automatically cast parameters of `EXECUTE`
  src/adapter/src/coord/sql.rs
  src/adapter/src/coord/statement_logging.rs
  src/adapter/src/session.rs
  src/sql/src/plan.rs
  src/sql/src/plan/error.rs
  src/sql/src/plan/hir.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/side_effecting_func.rs
  src/sql/src/plan/statement.rs
  src/sql/src/plan/statement/dml.rs
  test/sqllogictest/order_by.slt
Labels: A-ADAPTER

#32486 Fix types in `reduce_list_create_list_index_literal`
  src/expr/src/scalar.rs
  test/sqllogictest/list.slt
Labels: A-optimization, A-CLUSTER

#32475 Don't panic when the same parameter is coerced twice
  src/sql/src/plan/typeconv.rs
  test/sqllogictest/prepare.slt
Labels: A-ADAPTER

#32487 optimizer: Typecheck also in local optimization
  src/adapter/src/optimize/copy_to.rs
  src/adapter/src/optimize/materialized_view.rs
  src/adapter/src/optimize/peek.rs
  src/adapter/src/optimize/subscribe.rs
  src/adapter/src/optimize/view.rs
  src/transform/src/fusion/filter.rs
  src/transform/src/lib.rs
  src/transform/src/predicate_pushdown.rs
  src/transform/tests/test_runner.rs
  src/transform/tests/test_transforms.rs
Labels: A-optimization, A-CLUSTER

#32502 upgrade tests: Fix upgrade tests on old versions
  misc/python/materialize/checks/scenarios_upgrade.py
  misc/python/materialize/git.py
  misc/python/materialize/version_list.py
  test/legacy-upgrade/mzcompose.py
Labels: lts-backport-v25.1

#32490 [optimizer] typechecking errors should panic in CI
  src/transform/src/typecheck.rs
Labels: A-optimization, A-CLUSTER

#32543 ore: Fix nested `catch_unwind`
  src/ore/src/panic.rs
Labels: T-stability

#32594 tests: Skip `5_repeat_row_dataflow.slt` and `5_repeat_row_folding.slt`
  test/sqllogictest/transform/fold_vs_dataflow/5_repeat_row_dataflow.slt
  test/sqllogictest/transform/fold_vs_dataflow/5_repeat_row_folding.slt
Labels: T-testing
