Repository MaterializeInc/materialize, pull requests merged in 2025-06, with the labels that each got.

#32626 optimizer: Fix `literal_domination` when `MSE::reduce` changes the number of args of a variadic call
  src/transform/src/equivalence_propagation.rs
  test/sqllogictest/transform/column_knowledge.slt
Labels: A-optimization, A-CLUSTER

#32638 tests: Add check for negative accumulations in `pg_cdc.py`
  misc/python/materialize/checks/all_checks/pg_cdc.py
Labels: T-testing

#32673 docs: Mention `EXECUTE` parameter casting
  doc/user/content/sql/execute.md
Labels: A-docs

#32699 k8s: don't unwrap when getting disk metrics
  src/orchestrator-kubernetes/src/lib.rs
Labels: release-blocker

#32780 test: reset replicas after slts
  src/sqllogictest/src/runner.rs
Labels: T-testing

#32785 test: Fix naming of slt's replica size config
  src/sqllogictest/src/bin/sqllogictest.rs
  src/sqllogictest/src/runner.rs
  test/sqllogictest/mzcompose.py
Labels: T-testing

#32809 add new sm version to persist-client cfg.rs
  src/persist-client/src/cfg.rs
Labels: lts-backport-v25.2

#32808 Bump console version to 25.2.2
  misc/helm-charts/operator/templates/deployment.yaml
  misc/images/materialized-base/Dockerfile
Labels: self-managed-backport-v25.2

#32819 adapter: in support_execute_one drop SessionClient only after receiving result rows
  src/adapter/src/client.rs
  src/environmentd/src/telemetry.rs
Labels: release-blocker

#32838 Increase threshold for slow optimization warning in debug builds
  src/sql/src/optimizer_metrics.rs
Labels: A-optimization

#32841 Change slow optimization warning threshold from soft_assertions_enabled to cfg!(debug_assertions)
  src/sql/src/optimizer_metrics.rs
Labels: A-optimization
