Repository MaterializeInc/materialize, pull requests merged in 2025-04, with the labels that each got.

#32075 Fix OptimizationFinished in the statement lifecycle
  src/adapter/src/coord/sequencer/inner/peek.rs
Labels: A-ADAPTER

#32097 Make `transform` import `ore` with the `differential-dataflow` feature
  src/transform/Cargo.toml
Labels: A-build, A-CLUSTER

#32167 Fix positional argument name in `helm_chart_version_bump.py`
  misc/python/materialize/cli/helm_chart_version_bump.py
Labels: A-build

#32173 [persist] Be defensive when we have structured only data
  src/persist-client/src/fetch.rs
  src/persist-client/src/internal/state.rs
  src/persist-client/src/schema.rs
  src/persist-client/src/write.rs
Labels: lts-backport-v25.1

#32209 Catch more panics when calling optimizer code
  src/adapter/src/optimize.rs
  src/sql/src/plan/explain.rs
  src/transform/src/lib.rs
  src/transform/src/normalize_lets.rs
Labels: A-optimization, A-ADAPTER, A-CLUSTER

#32205 optimizer: Fix JoinImplementation's MFP lifting's inlining
  src/transform/src/join_implementation.rs
  test/sqllogictest/github-8261-8463-9156.slt
Labels: A-optimization, A-CLUSTER

#32210 Eliminate a deprecated `visit_mut_pre_post` call
  src/transform/src/join_implementation.rs
Labels: A-optimization, A-CLUSTER

#32244 optimizer: Guard `If` pushing by a type check
  src/expr/src/scalar.rs
  test/sqllogictest/jsonb.slt
Labels: A-CLUSTER
