Repository MaterializeInc/materialize, pull requests merged in 2025-01, with the labels that each got.

#30878 Eliminate unnecessary `.typ()` call from `keys_with_input_keys`
  src/expr/src/relation.rs
Labels: A-optimization, A-CLUSTER

#30879 Eliminate some typ() calls and an arity() call from MIR lowering
  src/compute-types/src/plan/lowering.rs
Labels: A-CLUSTER

#30881 Sometimes we can give the type to MRE::take_safely
  src/expr/src/explain.rs
  src/expr/src/relation.rs
  src/transform/src/canonicalization/flatmap_to_map.rs
  src/transform/src/canonicalization/topk_elision.rs
  src/transform/src/equivalence_propagation.rs
  src/transform/src/fold_constants.rs
  src/transform/src/fusion/top_k.rs
  src/transform/src/non_null_requirements.rs
  src/transform/src/predicate_pushdown.rs
Labels: A-optimization, A-CLUSTER

#30964 emulator: Fix MZ_SEGMENT_CLIENT_SIDE
  src/materialized/ci/entrypoint.sh
Labels: release-blocker

#30899 [docs] document LIR attribution
  doc/user/content/transform-data/troubleshooting.md
  doc/user/data/query_attribution_computation_time_output.yml
  doc/user/data/query_attribution_memory_usage_output.yml
  doc/user/data/query_attribution_memory_usage_w_hint_output.yml
  doc/user/data/query_attribution_topk_hints_output.yml
  doc/user/data/query_attribution_worker_skew_output.yml
  doc/user/layouts/partials/yaml-tables/generic-table.html
  doc/user/layouts/shortcodes/yaml-table.html
Labels: A-docs, A-optimization, T-observability

#31108 Add Mandelbrot set to WMR slt
  src/sqllogictest/src/parser.rs
  test/sqllogictest/mztimestamp.slt
  test/sqllogictest/with_mutually_recursive.slt
Labels: T-testing

#31124 Minor refactorings around HIR
  src/sql/src/plan.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/transform_hir.rs
Labels: A-ADAPTER

#31142 Rename `sql/src/plan/expr.rs` to `hir.rs`
  src/sql/src/func.rs
  src/sql/src/plan.rs
  src/sql/src/plan/hir.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/lowering/variadic_left.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/scope.rs
  src/sql/src/plan/transform_hir.rs
  src/sql/src/plan/typeconv.rs
  src/sql/src/pure/postgres.rs
Labels: A-ADAPTER

#31146 Remove some deprecated HIR visitation functions
  src/sql/src/plan/hir.rs
  src/sql/src/plan/lowering.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/transform_hir.rs
Labels: A-ADAPTER, A-CLUSTER

#31190 Fix EXPLAIN column names for Project
  src/expr/src/explain/text.rs
  src/transform/src/analysis.rs
  src/transform/tests/test_transforms/humanized_exprs.spec
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
  test/sqllogictest/ldbc_bi.slt
  test/sqllogictest/ldbc_bi_eager.slt
  test/sqllogictest/limit_expr.slt
  test/sqllogictest/outer_join_lowering.slt
  test/sqllogictest/tpch_create_index.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/sqllogictest/tpch_select.slt
Labels: A-optimization, A-CLUSTER

#31079 loosen version upgrade checks to allow for lts version upgrades
  ci/nightly/pipeline.template.yml
  misc/python/materialize/checks/scenarios_upgrade.py
  misc/python/materialize/version_list.py
  src/persist-client/src/cfg.rs
  src/persist-client/src/internal/encoding.rs
  test/legacy-upgrade/mzcompose.py
Labels: lts-backport

#31140 Fix cached hash clash in `Fixpoint`
  src/transform/src/lib.rs
  test/sqllogictest/github-8906.slt
Labels: A-optimization, A-CLUSTER

#31247 docs: Add an important note about index keys
  doc/user/content/transform-data/optimization.md
Labels: A-docs

#31240 fix error detecting azure blobstore scheme
  src/persist/src/cfg.rs
Labels: lts-backport
