Repository MaterializeInc/materialize, pull requests merged in 2025-02, with the labels that each got.

#31201 docs: Improvements in EXPLAIN docs
  doc/user/content/sql/explain-plan.md
  doc/user/content/transform-data/optimization.md
  doc/user/data/explain_plan_operators.yml
Labels: A-docs

#30576 storage: track latest reported status and report on reconnect
  src/storage/src/render.rs
  src/storage/src/storage_state.rs
Labels: release-blocker

#31293 0dt: in preflight checks, notice DDL changes and restart read-only envd
  misc/python/materialize/cli/ci_annotate_errors.py
  src/adapter-types/src/dyncfgs.rs
  src/adapter/src/catalog/transact.rs
  src/catalog/src/durable.rs
  src/catalog/src/durable/initialize.rs
  src/catalog/src/durable/persist.rs
  src/catalog/src/durable/transaction.rs
  src/environmentd/src/deployment/preflight.rs
  src/environmentd/src/lib.rs
  test/0dt/mzcompose.py
Labels: release-blocker

#31402 Fix a minor EXPLAIN bug around `count(*)`
  src/adapter/src/explain/insights.rs
  src/expr/src/relation.rs
  src/sql/src/func.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
Labels: A-CLUSTER

#31403 Disable activity log for self managed
  misc/helm-charts/operator/templates/deployment.yaml
  misc/helm-charts/operator/tests/deployment_test.yaml
  misc/images/materialized-base/Dockerfile
  src/orchestratord/src/controller/materialize.rs
  src/orchestratord/src/controller/materialize/environmentd.rs
Labels: lts-backport-v25.1

#31471 Tweak aoc slts to use more EXPLAIN options
  test/sqllogictest/advent-of-code/2023/aoc_1201.slt
  test/sqllogictest/advent-of-code/2023/aoc_1202.slt
  test/sqllogictest/advent-of-code/2023/aoc_1203.slt
  test/sqllogictest/advent-of-code/2023/aoc_1204.slt
  test/sqllogictest/advent-of-code/2023/aoc_1205.slt
  test/sqllogictest/advent-of-code/2023/aoc_1206.slt
  test/sqllogictest/advent-of-code/2023/aoc_1207.slt
  test/sqllogictest/advent-of-code/2023/aoc_1208.slt
  test/sqllogictest/advent-of-code/2023/aoc_1209.slt
  test/sqllogictest/advent-of-code/2023/aoc_1210.slt
  test/sqllogictest/advent-of-code/2023/aoc_1211.slt
  test/sqllogictest/advent-of-code/2023/aoc_1212.slt
  test/sqllogictest/advent-of-code/2023/aoc_1213.slt
  test/sqllogictest/advent-of-code/2023/aoc_1214.slt
  test/sqllogictest/advent-of-code/2023/aoc_1215.slt
  test/sqllogictest/advent-of-code/2023/aoc_1216.slt
  test/sqllogictest/advent-of-code/2023/aoc_1217.slt
  test/sqllogictest/advent-of-code/2023/aoc_1218.slt
  test/sqllogictest/advent-of-code/2023/aoc_1219.slt
  test/sqllogictest/advent-of-code/2023/aoc_1220.slt
  test/sqllogictest/advent-of-code/2023/aoc_1222.slt
  test/sqllogictest/advent-of-code/2023/aoc_1223.slt
  test/sqllogictest/advent-of-code/2023/aoc_1224.slt
  test/sqllogictest/advent-of-code/2023/aoc_1225.slt
Labels: T-testing

#31482 explain: Switch default to global plan instead of physical plan
  src/sql-parser/src/ast/defs/statement.rs
Labels: release-blocker

#31399 fixes issue where we panic when gracefully altering cluster with sources
  src/sql/src/plan.rs
  src/sql/src/plan/statement/ddl.rs
  test/cloudtest/test_managed_cluster.py
Labels: C-bug

#31452 conditionally create mz_system and mz_probe cluster replicas
  Cargo.lock
  misc/helm-charts/operator/README.md
  misc/helm-charts/operator/templates/deployment.yaml
  misc/helm-charts/operator/values.yaml
  src/adapter-types/src/bootstrap_builtin_cluster_config.rs
  src/adapter-types/src/lib.rs
  src/adapter/src/catalog.rs
  src/adapter/src/catalog/open.rs
  src/adapter/src/coord.rs
  src/catalog-debug/BUILD.bazel
  src/catalog-debug/Cargo.toml
  src/catalog-debug/src/main.rs
  src/catalog/src/builtin.rs
  src/catalog/src/config.rs
  src/environmentd/BUILD.bazel
  src/environmentd/src/environmentd/main.rs
  src/environmentd/src/lib.rs
  src/environmentd/src/test_util.rs
  src/environmentd/tests/bootstrap_builtin_clusters.rs
  src/orchestratord/src/controller/materialize.rs
  src/orchestratord/src/controller/materialize/environmentd.rs
  src/sqllogictest/BUILD.bazel
  src/sqllogictest/Cargo.toml
  src/sqllogictest/src/runner.rs
Labels: lts-backport-v25.1

#31539 Change catalog server default size to 25cc
  misc/helm-charts/operator/README.md
  misc/helm-charts/operator/values.yaml
Labels: lts-backport-v25.1

#31533 Fix EXPLAIN around Char and Varchar
  src/adapter/src/catalog.rs
  src/adapter/src/coord/timestamp_selection.rs
  src/compute-types/src/explain/text.rs
  src/expr-parser/src/catalog.rs
  src/expr-test-util/src/lib.rs
  src/expr/src/scalar/func/impls/string.rs
  src/repr/src/explain.rs
  src/sql/src/func.rs
  src/sql/src/plan/hir.rs
  src/sql/src/plan/query.rs
  src/sql/src/plan/statement.rs
  src/sql/src/plan/statement/ddl.rs
  src/sql/src/plan/typeconv.rs
  src/sql/src/pure/postgres.rs
  src/transform/src/typecheck.rs
  test/sqllogictest/array_fill.slt
  test/sqllogictest/char.slt
  test/sqllogictest/cockroach/aggregate.slt
  test/sqllogictest/github-5536.slt
  test/sqllogictest/map.slt
  test/sqllogictest/tpch_create_materialized_view.slt
  test/sqllogictest/tpch_select.slt
  test/sqllogictest/type-promotion.slt
  test/testdrive/char-varchar-distinct.td
Labels: A-CLUSTER

#31566 Add `introspection/*.slt` to the normal CI
  test/sqllogictest/mzcompose.py
Labels: T-testing

#31597 Refactor soft assertion enablement checks
  src/catalog/src/durable/persist.rs
  src/expr/src/explain/text.rs
  src/ore/src/assert.rs
  src/persist-client/src/batch.rs
  src/repr/src/explain.rs
  src/sql/src/plan/statement/dml.rs
Labels: C-refactoring

#31596 Fix `EXPLAIN` for constant views
  src/adapter/src/optimize/view.rs
  src/catalog/src/memory/objects.rs
  test/sqllogictest/explain/locally_optimized_plan.slt
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/raw_plan_as_text.slt
Labels: T-testing, A-ADAPTER

#31603 Update `LICENSE` to allow cluster use
  LICENSE
Labels: lts-backport-v25.1

#31628 Fix HIR explain's `count(*)` handling
  src/expr/src/relation.rs
  src/sql/src/func.rs
  src/sql/src/plan/hir.rs
  test/sqllogictest/explain/raw_plan_as_text.slt
Labels: A-CLUSTER

#31614 Fix EXPLAIN's humanization/redaction of the equivalences analysis
  src/expr/src/explain/text.rs
  src/transform/src/analysis.rs
  src/transform/src/analysis/equivalences.rs
  test/sqllogictest/explain/optimized_plan_as_text.slt
  test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
Labels: A-CLUSTER

#31634 Bump console image tag to 25.2.0
  misc/helm-charts/operator/templates/deployment.yaml
  misc/images/materialized-base/Dockerfile
  misc/images/materialized-base/console_nginx.template
Labels: lts-backport-v25.1

#31692 fix: return an `AdapterError::Internal` instead of panicking
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
Labels: lts-backport-v25.1

#31705 sql: Wrap subscripted expression in parens when it ends with a type name
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/select
  test/sqllogictest/arrays.slt
  test/sqllogictest/list.slt
Labels: release-blocker, A-ADAPTER, lts-backport-v25.1
