Repository MaterializeInc/materialize, pull requests merged in 2025-08, with the labels that each got.

#33162 Reorder the fields of LIR nodes to the order they happen
  src/compute-types/src/explain/text.rs
  src/compute-types/src/plan.rs
  src/compute-types/src/plan/interpret/api.rs
  src/compute-types/src/plan/interpret/physically_monotonic.rs
  src/compute-types/src/plan/lowering.rs
  src/compute-types/src/plan/render_plan.rs
  src/compute/src/render.rs
  src/compute/src/render/flat_map.rs
  src/compute/src/render/reduce.rs
  test/sqllogictest/explain/default.slt
  test/sqllogictest/explain/physical_plan_aggregates.slt
  test/sqllogictest/explain/physical_plan_as_json.slt
  test/sqllogictest/explain/physical_plan_as_text.slt
  test/sqllogictest/explain/physical_plan_as_text_redacted.slt
  test/sqllogictest/github-2746.slt
  test/sqllogictest/outer_join.slt
  test/sqllogictest/reduce_mfp.slt
  test/sqllogictest/transform/literal_constraints.slt
  test/sqllogictest/transform/normalize_lets.slt
  test/sqllogictest/transform/relax_must_consolidate.slt
  test/sqllogictest/window_funcs.slt
Labels: A-CLUSTER

#33272 Fix parse order of WITH ORDINALITY and table alias
  src/sql-parser/src/ast/defs/query.rs
  src/sql-parser/src/parser.rs
  src/sql-parser/tests/testdata/select
  test/sqllogictest/table_func.slt
Labels: release-blocker, A-ADAPTER

#32994 Followups to the new subquery guard
  src/expr/src/relation/func.rs
  src/transform/src/canonicalization.rs
  src/transform/src/canonicalization/flat_map_elimination.rs
  src/transform/tests/test_transforms.rs
  src/transform/tests/test_transforms/flatmap_to_map.spec
Labels: A-optimization

#33288 Allow setting service account name in Materialize CR
  src/cloud-provider/src/lib.rs
  src/cloud-resources/src/crd/materialize.rs
  src/orchestratord/src/controller/materialize.rs
  src/orchestratord/src/controller/materialize/environmentd.rs
Labels: self-managed-backport-v25.2

#33276 Rewrite `FlatMapElimination`
  src/expr/src/relation/func.rs
  src/expr/src/scalar.rs
  src/transform/src/canonicalization/flat_map_elimination.rs
  src/transform/tests/test_transforms/flat_map_elimination.spec
  test/sqllogictest/table_func.slt
  test/sqllogictest/window_funcs.slt
Labels: A-optimization

#33301 Set a restrictive security context for orchestratord
  misc/helm-charts/operator/templates/deployment.yaml
Labels: self-managed-backport-v25.2

#33327 add replica name annotations to replica statefulset
  src/adapter/src/coord.rs
  src/adapter/src/coord/sequencer/inner/cluster.rs
  src/controller/src/clusters.rs
  src/orchestrator-kubernetes/src/lib.rs
  src/orchestrator/src/lib.rs
Labels: self-managed-backport-v25.2

#33336 Do `least_valid_read` on `ReadHolds` instead of `Catalog`
  src/adapter/src/coord/command_handler.rs
  src/adapter/src/coord/ddl.rs
  src/adapter/src/coord/sequencer/inner/create_index.rs
  src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
  src/adapter/src/coord/timestamp_selection.rs
Labels: A-ADAPTER

#33389 Disable the legacy WITH ORDINALITY implementation fallback
  src/sql/src/func.rs
  src/sql/src/plan/query.rs
  src/sql/src/session/vars/definitions.rs
  test/sqllogictest/cockroach/rows_from.slt
  test/sqllogictest/github-2996.slt
  test/sqllogictest/regex.slt
  test/sqllogictest/table_func.slt
Labels: A-ADAPTER
